### PR TITLE
fix(html/parser): span

### PR DESCRIPTION
**Pull request by alexander-akait**
**Description:**

Fixes:
- `DUMMY_SP` for auto generated elements when they dont exist - `body`/`head`/`html`/`tbody`/etc
- fix span for tables

**BREAKING CHANGE:**

No

**Related issue (if exists):**

No

### CODE REVIEW

**Review by kdy1 — DISMISSED** [review]
Thanks!
---

swc-bump:
 - swc_html_parser

**Comment by alexander-akait** [comment]
Rebased

**Comment by kdy1** [comment]
Seems like CI is failing?

**Comment by alexander-akait** [comment]
@kdy1 Fixed, forget to update some tests

**Pull request merged**
