### PR TITLE
fix(es/minifier): Force rename synthesized identifiers

### PR DESCRIPTION
**Pull request by kdy1**
**Description:**

**Related issue:**

 - Closes https://github.com/swc-project/swc/issues/9468

### CODE REVIEW

**Comment by Austaras** [comment]
Wait, so we could know what identifier is synthesized all this time along?

**Comment by Austaras** [comment]
Tests failed. Otherwise PR looks good.

**Comment by kdy1** [comment]
Yeap. All `Mark`s used for user-specified identifiers inherit from the `top_level_mark`.

**Comment by Austaras** [comment]
Consider me shocked.

**Review by Austaras — APPROVED** [review]

**Pull request merged**
