### PR TITLE
refactor(swc/ecma_ast): apply rkyv-bytecheck flag

### PR DESCRIPTION
**Pull request by kwonoj**
**Description:**

This PR updates ast* related package's rkyv bytecheck flags.

**BREAKING CHANGE:**

**Related issue (if exists):**

### CODE REVIEW

**Comment by kdy1** [comment]
Can you rebase?
Also, you don't need to bump version by yourself.

We now use `-D` flag while invoking `cargo mono bump`, which bump all dependants

**Comment by kwonoj** [comment]
OK, updated. manual bump was for the previous cases where transitive deps bump missing, but hope it won't happen again.

**Comment by kwonoj** [comment]
@kdy1 Somehow this PR slipped through the cracks. I've rebased and resolved conflict to attempt to land again. 🤞

**Comment by kdy1** [comment]
Can you revert version changes?

**Comment by kwonoj** [comment]
reverted. I think that's redundant but harmless though.

**Review by kdy1 — APPROVED** [review]
swc-bump:
 - ast_node
 - swc_plugin_proxy

**Comment by kdy1** [comment]
Oh benchmark action failed

**Comment by kwonoj** [comment]
@kdy1 yes, 

```
 env:
    RUST_LOG: off
Error: No benchmark result was found in /Users/runner/work/swc/swc/output.txt. Benchmark output was ''
```

Not sure why this fails?

**Comment by kdy1** [comment]
You have to look at `Run benchmark` step

**Comment by kwonoj** [comment]
```
error[E0275]: overflow evaluating the requirement `at_rule::AtRule: Archive`
  --> crates/swc_css_ast/src/at_rule.rs:10:1
   |
10 | #[ast_node("AtRule")]
```

🤔 

I'll dig bit more.

**Comment by kwonoj** [comment]
For futther digging: `css_ast` fails with rkyv:

```
cargo check -p swc_css_ast --features rkyv-impl
```

**Comment by kwonoj** [comment]
@kdy1 , ok, all CI issues seems resolved.

**Review by kdy1 — APPROVED** [review]

**Pull request merged**
