### PR TITLE
Fix a number of typos

### PR DESCRIPTION
**Pull request by wycats**
This pull requests fixes a large number of typos across the codebase. For the most part, these typos are in comments. In one case (a typo in `doc(hidden)`), it has a code consequence. In a few cases, I changed the names (and uses) of internal functions.

### CODE REVIEW

**Comment by wycats** [comment]
Once all the tests pass, I'll squash all of the incremental steps into a single commit. I'm leaving them separate right now so I have a history of the failures.

**Comment by wycats** [comment]
The tests pass, so I squashed and rebased.

**Comment by wycats** [comment]
@kdy1 now that all of the tests pass, is there anything else I need to do to get this merged?

**Comment by kdy1** [comment]
Thanks!

**Review by kdy1 — APPROVED** [review]
LGTM

**Pull request merged**
