### PR TITLE
fix(es/parser): parse decorators after export

### LINKED ISSUE #6984: legacy decorators with decorate before exports makes bugs
### Describe the bug

When I use the legacy decorator while using the esm default export, swc will transform the code be like this:

image
Then when running the code, an error will be reported: Uncaught ReferenceError: App is not defined.

**I think the decorate method should be executed inside the iife.**

### Input code
```javascript

import React from 'react'
import { withRouter } from 'react-router-dom'

export default
@withRouter
class App extends React.Component {
    render() {
        console.log(this.props)
        return <div>134</div>
    }
}
```

### Config
```json
{
  "jsc": {
    "externalHelpers": true,
    "parser": {
      "syntax": "ecmascript",
      "jsx": true,
      "decorators": true,
      "dynamicImport": true,
      "decoratorsBeforeExport": true
    },
    "transform": {
      "legacyDecorator": true,
      "decoratorMetadata": true
    },
    "minify": {
      "compress": false
    }
  },
  "isModule": "unknown",
  "env": {
    "mode": "usage",
    "coreJs": "3",
    "dynamicImport": true
  }
}
```

### Playground link

https://play.swc.rs/?version=1.3.36&code=H4sIAAAAAAAAA02NwQ6CQAxE7%2F2K3sADGKNHYjT%2BAX9A2CKbLNtNtyiJ4d9dwKhzms6bZuwQWBRralrFTnjATBafgd3IC59W%2B5pHJcH5v1LIGhaGhwyAprVuqGtGp3D5fUHrmhjxGgLSpORN3ObKG6cJTz6NACZJYiT57nMuatlHdlQ6vufa21gG4RB3Xy6ko3isjH2cD8dTtV%2FMSmeY4Q2v7l5S3QAAAA%3D%3D&config=H4sIAAAAAAAAA22PvW7DQAyD30Wzt24egxRIC%2BQhhDs6uPb%2BIMmtjcDvHjlAmiFdSX6UeKUvDTReCYtBKucTcocojSYzBuosCtkDulbjhUZCKKxBUjcanF4e0YjQhK094bhWLil8lN7EXmMHTE3wvjzdbSATrup62W9mXDisxwfxUnGGcWTjP7qkmqZ1R0MrXaD%2By8RZsbmZ9NzinOEb5vpd22%2F1Aag%2Fe7y0eNeVL3DV%2B%2FHpLL3RvzO27QYUx7KWOQEAAA%3D%3D

### Expected behavior

 The class should be correctly decorated before exporting

### Actual behavior

The decorate method call with using the no define class, then make an error: Uncaught ReferenceError: App is not defined.

### Version

1.3.36

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by magic-akari**
**Description:**

**BREAKING CHANGE:**

**Related issue (if exists):**
- fix #6984

### CODE REVIEW

**Comment by magic-akari** [comment]
I should put some parser-related test cases, but I'm not sure where to put them.

**Comment by kdy1** [comment]
You can add one to https://github.com/swc-project/swc/tree/e7911ee594ec1c85b4f0a4fe19833f737d4576dd/crates/swc_ecma_parser/tests/js or https://github.com/swc-project/swc/tree/e7911ee594ec1c85b4f0a4fe19833f737d4576dd/crates/swc_ecma_parser/tests/typescript

**Comment by magic-akari** [comment]
```
thread 'errors_tests__typescript_errors__esDecorators__classDeclaration__esDecorators_classDeclaration_exportModifier__file6_ts' panicked at 'assertion failed: `(left == right)`
  left: `
  x Decorators may not appear after `export` or `export default` if they also appear before `export`.
   ,-[$DIR/tests/typescript-errors/esDecorators/classDeclaration/esDecorators-classDeclaration-exportModifier/file6.ts:3:1]
 3 | // error
 4 | @dec export @dec class C6 {}
   :             ^^^^
 4 | 
   `----
`,
 right: `
  x Decorators may not appear after `export` or `export default` if they also appear before `export`.
   ,-[$DIR/tests/typescript-errors/esDecorators/classDeclaration/esDecorators-classDeclaration-exportModifier/file6.ts:3:1]
 3 | // error
 4 | @dec export @dec class C6 {}
   :             ^^^^
   `----
`:
```

It appears that there is a formatting error present, with an extra `4` added to the line number.

**Review by kdy1 — APPROVED** [review]
Thank you!

---

swc-bump:
 - swc_ecma_parser

**Pull request merged**
