### PR TITLE
feat(swc): enable bytecheck

### PR DESCRIPTION
**Pull request by kwonoj**
**Description:**

Second attempt to enable bytecheck. This PR does not have cersioned struct yet, just enabling bytecheck whereever possible. Also it is for the ast only yet, so transformmetadata and other might need this later.

PR seems to passing all the ci, but as we've experienced before there might be some unexpected outcome with release. Maybe better to hold this until clear https://github.com/swc-project/swc/issues/7238, then land as separate release.

### CODE REVIEW

**Review by kdy1 — APPROVED** [review]
Thank you! Let's postpone merging this..

**Comment by kwonoj** [comment]
@kdy1 Resolved conflict, I think we can land this now (which.. requires another bump for swc_core and @swc/core probably though)

**Comment by kwonoj** [comment]
@kdy1 thoughts on this? I think this is now ready to go in.

**Comment by kdy1** [comment]
I agree, but I'm curious if this is a breaking change of `swc_core`

**Comment by kwonoj** [comment]
I may wrong, but I guess not? This PR enables `repr` and bytecheck, however does not enable versioned struct we attempted previously (https://github.com/swc-project/swc/pull/5062/commits/1f3eba7f240b5d08e4688be450d5c00e6e38c2b1#diff-ef22f81d236ee08fd2bed74657c8eddc2dbef9f02f454a25941daa453b0ab2e0R173) so unless anyone explicitly relies on some of repr-based struct layout, it would work (again, I _guess_ though)

**Review by kdy1 — APPROVED** [review]
swc-bump:
 - swc_plugin_proxy
 - swc_atoms
 - ast_node

**Pull request merged**
