### PR TITLE
fix(es/minifier): Don't remove exports

### PR DESCRIPTION
**Pull request by lewisl9029**
**Description:**

Hi there! I recently upgraded SWC from 1.3.60 to the latest 1.3.78 and discovered that some of my builds were broken because SWC's minifier was removing exports.

I've added some minimal repros of the cases I encountered as failing test cases, and a small change to the minifier to fix them.

Happy to iterate on this as you see fit. Cheers!

### CODE REVIEW

**Review by kdy1 — APPROVED** [review]
Thank you!

---
swc-bump:
 - swc_ecma_minifier

**Comment by lewisl9029** [comment]
Oops, this seems to be causing some new issues around comments being moved to the wrong places...

Working on a test case and fix.

**Comment by lewisl9029** [comment]
@kdy1 looks like we commented at the same time haha... 

Closing for now to make sure this doesn't get merged as is since it's causing some issues in my local testing. Working on an update, will reopen once it's ready for another look!

**Comment by kdy1** [comment]
Well, you don't need to worry about it. SWC has a good CI process, and once CI issue is fixed by https://github.com/swc-project/swc/pull/7857 the @swc-bot will rebase this

**Comment by lewisl9029** [comment]
Got it, will keep looking into the issue from my side, and send in another PR if needed! :)

**Comment by kdy1** [comment]
스크린샷 2023-08-25 오후 12 02 00


image

**Comment by kdy1** [comment]
@lewisl9029 Please enable `Allow edit by maintainers`

**Comment by lewisl9029** [comment]
Hey @kdy1, didn't realize this before, but it looks like GitHub doesn't [actually support enabling that option for forks in organizations](https://github.com/orgs/community/discussions/5634) 🤦 

If the edits you're looking to make are small, just let me know what they are and I'd be happy to go and make them. Alternatively, feel free to just cherry pick the changes here onto your own branch if that's easier. I'll remember to make a fork under my personal account the next time I need to contribute. Thanks!

**Comment by kdy1** [comment]
Then can you rebase this PR?

**Comment by kdy1** [comment]
Pressing `Update branch` button is fine

**Comment by lewisl9029** [comment]
Done!

**Review by kdy1 — APPROVED** [review]

**Pull request merged**
