### PR TITLE
feat: add key_in_props to avoid importing react for modern JSX

### LINKED ISSUE #6987: SWC does not honour pragma when spread is used before additional props
### Describe the bug

Hello, 

We recently switched from using babel to SWC for our transpilation purposes. We noticed an issue with SWC not honouring `jsc.transform.react.importSource` when a spread operator is used before additional props.

In our case we are using typescript, emotion and react as can be seen in the SWC config provided. I will provide an example component the expected SWC output and the one obtained.

### Input code

```tsx
import type { FC, ReactNode } from "react";
import { isValidElement, Children } from "react";

import * as styles from "./CheckmarkList.styles";

interface Props {
  children: ReactNode;
}

const CheckmarkList: FC<Props> = ({ children}) => {
  const listItems = () =>
    Children.map(children, (child, index) => {
      if (!isValidElement(child)) {
        return null;
      }
      const { children: liChildren, css: liCss, ...otherProps } = child.props;

      return (
        <li {...otherProps} key={`checkmark-list-item-${index}`} css={[styles.listItem, liCss]}>
          {liChildren}
        </li>
      );
    });

  return <ul css={styles.list}>{listItems()}</ul>;
};

export { CheckmarkList };
```

### Config

```json
{
  "$schema": "http://json.schemastore.org/swcrc",
  "jsc": {
    "externalHelpers": true,
    "parser": {
      "syntax": "typescript",
      "tsx": true,
      "dynamicImport": true
    },
    "experimental": {
      "plugins": [
        ["@fullscript/swc-plugin-translation-converter", {}],
        [
          "@fullscript/swc-plugin-jsx-remove-attribute",
          {
            "attributesToRemove": ["data-testid"]
          }
        ],
        [
          "@swc/plugin-emotion",
          {
            "autoLabel": "always",
            "labelFormat": "[dirname]"
          }
        ],
        ["@swc/plugin-loadable-components", {}]
      ]
    },
    "transform": {
      "react": {
        "runtime": "automatic",
        "importSource": "@emotion/react",
        "pragma": "React.createElement",
        "pragmaFrag": "React.Fragment",
        "throwIfNamespace": true,
        "useBuiltins": true,
        "refresh": true
      }
    }
  },
  "env": {
    "mode": "usage",
    "coreJs": "3.23",
    "shippedProposals": true,
    "targets": "defaults, last 1 version, > 0.2%, not dead, not IE > 0, ios_saf >= 10, safari >= 10, not op_mini all, not baidu <= 100, not kaiOS <= 100, not android <= 5.0, not and_uc <= 100, not and_qq <= 100"
  }
}
```

### Playground link

_No response_

### Expected behavior

SWC should honour `jsc.transform.react.importSource` and have the following output as it does when the `{...otherProp}` spread is used after non spread props 

```JS
import _object_spread_props from "@swc/helpers/src/_object_spread_props.mjs";
import _object_without_properties from "@swc/helpers/src/_object_without_properties.mjs";
import { jsx as _jsx } from "@emotion/react/jsx-runtime";
import { isValidElement, Children } from "react";
import * as styles from "./CheckmarkList.styles";
var CheckmarkList = param => {
  var { children } = param;
  var listItems = () =>
    Children.map(children, (child, index) => {
      if (!(/*#__PURE__*/ isValidElement(child))) {
        return null;
      }
      var _child_props = child.props,
        { children: liChildren, css: liCss } = _child_props,
        otherProps = _object_without_properties(_child_props, ["children", "css"]);
      return /*#__PURE__*/ _jsx(
        "li",
        _object_spread_props(
          _object_spread(
            {
              css: [styles.listItem, liCss],
            },
            otherProps
          ),
          {
            children: liChildren,
          }
        ),
        "checkmark-list-item-".concat(index)
      );
    });
  return /*#__PURE__*/ _jsx("ul", {
    css: styles.list,
    children: listItems(),
  });
};
export { CheckmarkList };
```

### Actual behavior

Instead SWC does not honour `jsc.transform.react.importSource` and uses `React.createElement`

```JS
import _object_spread from "@swc/helpers/src/_object_spread.mjs";
import _object_spread_props from "@swc/helpers/src/_object_spread_props.mjs";
import _object_without_properties from "@swc/helpers/src/_object_without_properties.mjs";
import { jsx as _jsx } from "@emotion/react/jsx-runtime";
import { createElement as _createElement } from "react";
import { isValidElement, Children } from "react";
import * as styles from "./CheckmarkList.styles";
var CheckmarkList = param => {
  var { children } = param;
  var listItems = () =>
    Children.map(children, (child, index) => {
      if (!(/*#__PURE__*/ isValidElement(child))) {
        return null;
      }
      var _child_props = child.props,
        { children: liChildren, css: liCss } = _child_props,
        otherProps = _object_without_properties(_child_props, ["children", "css"]);
      return /*#__PURE__*/ _createElement(
        "li",
        _object_spread_props(_object_spread({}, otherProps), {
          key: "checkmark-list-item-".concat(index),
          css: [styles.listItem, liCss],
        }),
        liChildren
      );
    });
  return /*#__PURE__*/ _jsx("ul", {
    css: styles.list,
    children: listItems(),
  });
};
export { CheckmarkList };
```

This results in an error for emotion when rendering the component and results in styles being rendered as `[object Object],`
Screenshot 2023-02-24 at 12 14 08 PM

### Version

1.3.32

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by manucorporat**
fixes #6987

### CODE REVIEW

**Comment by manucorporat** [comment]
Might need some help with the API naming and tests, happy to add that with some input

**Comment by manucorporat** [comment]
This is a critically important issue for us, months before it was not that much, but now we are forcing developer to always use key, this is triggering this issue way more offen. Happy to focus time and energy to get it fixed!

**Comment by manucorporat** [comment]
Trying to come up with the last impact PR, so it's more likely to get merged. Happy to remove it all together, but not sure it would break some react code.

**Comment by kdy1** [comment]
Can you sign the CLA?

**Comment by kdy1** [comment]
And actually, I consider this a bigger change than the solution suggested by @magic-akari and I'm not going to accept this PR

**Comment by kdy1** [comment]
Closing as #6987 is fixed in the correct way

**Pull request closed without merging**
