### PR TITLE
feat(preset-env): Upgrade `browserslist-rs`

### PR DESCRIPTION
**Pull request by g-plane**
**Description:**

Compilation time of browserslist-rs has beed reduced by 32%. See: https://github.com/browserslist/browserslist-rs/pull/23

But, it's still slower that oxc-browserslist:

image

while browserslist-rs costs about 3.9s.

**BREAKING CHANGE:**

**Related issue (if exists):**

Close #9014

### CODE REVIEW

**Comment by chenjiahan** [comment]
The CI is failed, can you take a look? ❤️

**Comment by g-plane** [comment]
I failed to fix it. Let's ask help to @kdy1 .

**Review by kdy1 — DISMISSED** [review]
swc-bump:
 - preset_env_base --breaking

**Comment by kdy1** [comment]
Can you check failing tests?

**Review by kdy1 — DISMISSED** [review]

**Review by kdy1 — APPROVED** [review]

**Comment by kdy1** [comment]
- `time cargo build --release --features swc_ecma_minifier/concurrent`

Before this PR:


```
    Finished `release` profile [optimized] target(s) in 37.52s
cargo build --release --features swc_ecma_minifier/concurrent  365.78s user 11.74s system 1004% cpu 37.592 total
```

**Comment by g-plane** [comment]
Does it look slower? That's weird.

**Comment by kdy1** [comment]
I think it's a noise

**Pull request merged**
