### PR TITLE
fix(ecma/codegen): emit sourcemap more careful in kv_prop

### LINKED ISSUE #4112: The sourcemaps bug is still extant
### Describe the bug

The sourcemaps are breaking both Mozilla's `source-map` package and `esbuild`. I reported this issue previously:

https://github.com/swc-project/swc/issues/3772

I have found a simpler repository to test. Please try this one:

https://github.com/djalbat/easy-richtextarea

Clone this repository then run the usual `npm install` followed by `npm run build-debug` and you will see the errors. Alternatively, try the input code below and test with the `source-map` package.

### Input code

```typescript
"use strict";

import { React, window } from "easy";

window.assign({
  React
});
```

### Config

```json
{
    "jsc": {
        "parser": {
            "syntax": "ecmascript",
            "jsx": true
        }
    },
    "module": {
        "type": "commonjs"
    }
}
```

### Playground link

_No response_

### Expected behavior

There should be no errors produced when the transpiled code is passed to bundlers or the `source-map` package.

### Actual behavior

This is the output:

```
"use strict";
var _easy = require("easy");
_easy.window.assign({
    React: _easy.React
});

//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbIi4uLy4uL3NyYy9leGFtcGxlL3ByZWFtYmxlLmpzIl0sInNvdXJjZXNDb250ZW50IjpbIlwidXNlIHN0cmljdFwiO1xuXG5pbXBvcnQgeyBSZWFjdCwgd2luZG93IH0gZnJvbSBcImVhc3lcIjtcblxud2luZG93LmFzc2lnbih7XG4gIFJlYWN0XG59KTtcbiJdLCJuYW1lcyI6WyJ3aW5kb3ciLCJhc3NpZ24iLCJSZWFjdCJdLCJtYXBwaW5ncyI6IkFBQUEsWUFBWSxDQUFDO0FBRWlCLElBQUEsS0FBTSxXQUFOLE1BQU0sQ0FBQTtBQUVwQ0EsS0FBTSxRQUFDQyxNQUFNLENBQUM7SUNKZCxBREtFQyxLQUFLLEVBQUxBLEtBQUssTUFBTEE7Q0FDRCxDQUFDLENBQUMifQ==
```

It results in the following error from `esbuild`:

```
 lib/example/preamble.js#sourceMappingURL:1:295: warning: Bad "mappings" data in source map at character 75: Invalid source index value: 1
    1 │ ... React, window } from \"easy\";\n\nwindow.assign({\n  React\n});\n"],"names":["window","assign","React"],"mappings":"AAAA,YAAY,CAAC;AAEiB,IAAA,KAAM,WAAN,MAAM,CAAA;AAEpCA,KAAM,QAACC,MAAM,CAAC;ICJd,ADKEC,KAAK,EAALA,KAAK,MAALA;CACD,CAAC,CAAC"}
      ╵                                                                                                                                                                                                    ^
```

The `source-map` package produces a similar error.

### Version

1.2.159

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by RiESAEX**
**Description:**
if KeyValueProp.value has a dummy span, KeyValueProp.span() will return a wrong span, so check and emit key and value to sourcemap separately.
fold_ident in transforms_module can cause this case, so I make the memberExpr has the origin ident's span.
**BREAKING CHANGE:**

**Related issue (if exists):**
fix #4112

### CODE REVIEW

**Review by kdy1 — DISMISSED** [review]
Thank you!


---

swc-bump:
 - swc_ecma_codegen

**Comment by kdy1** [comment]
Can you fix the clippy error?

**Comment by RiESAEX** [comment]
fixed

**Review by kdy1 — APPROVED** [review]
Thank you!

---

swc-bump:
 - swc_ecma_codegen

**Pull request merged**
