### PR TITLE
fix(es/transforms/compat): comment position in class and arrow

### LINKED ISSUE #3846: Comments before class is striped when targeting es5
### Describe the bug

When targeting es6 or higher, comments would be preserved.

### Input code

```typescript
// abcabc
class C {}
```

### Config

_No response_

### Playground link

_No response_

### Expected behavior

Comments shall be preserved.

### Actual behavior

_No response_

### Version

1.2.148

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Austaras**
**Description:**

code
```js
// 123
class A extends B {
}
```

before
```js
var A = // 123
(function (B) {})(B)
```

after
```js
// 123
var A = (function (B) {})(B)
```

code
```js
const a = () => /* 123 */ 1
```

before
```js
const a = function a() {
   /* 123 */ return 1
}
```

after
```js
const a = function a() {
  return /* 123 */ 1
}
```
**BREAKING CHANGE:**

**Related issue (if exists):**
fixes #3846

### CODE REVIEW

**Comment by kdy1** [comment]
Some spans were intentionally removed by https://github.com/swc-project/swc/pull/3242
cc @0xe

**Comment by Austaras** [comment]
> Some spans were intentionally removed by #3242 cc @0xe

#3242 only removed span of function args like
```js
function (B) {} (B)
//              ^
```

**Comment by kdy1** [comment]
Thanks! Then I'll review it

**Review by kdy1 — APPROVED** [review]
LGTM. Thank you!

---

swc-bump:
  - swc_ecma_codegen
  - swcc_

**Pull request merged**
