### PR TITLE
Fix transform enums with keys/value

### PR DESCRIPTION
**Pull request by gus3inov**
Hi! Tried to fix transformation enums with keys/value from https://github.com/swc-project/swc/issues/729.
Also added test for this case.

### CODE REVIEW

**Comment by gus3inov** [comment]
Fixes #729

**Comment by kdy1** [comment]
Thank you very much for the pr!

**Comment by leebenson** [comment]
Thanks for this!

**Comment by leebenson** [comment]
@kdy1 - I know this is tagged with the 1.1.36 milestone, but would you be open to releasing a hotfix with this please? It'd unblock a relatively large auto-generated GraphQL codebase I'm working on where keys/values tend to have different casing. Many thanks!

**Comment by kdy1** [comment]
@leebenson It seems like a good idea.
I started publishing a hotfix.
But please note that building prebuilt binaries take some time

**Comment by kdy1** [comment]
@leebenson I published a new version

**Comment by leebenson** [comment]
thanks @kdy1, but it looks like https://github.com/swc-project/swc/releases/tag/v1.1.36 doesn't contain this PR?

**Pull request merged**
