### PR TITLE
Fix jemalloc

### PR DESCRIPTION
**Pull request by Brooooooklyn**
**Description:**

**BREAKING CHANGE:**

**Related issue (if exists):**

### CODE REVIEW

**Review by kdy1 — CHANGES_REQUESTED** [review]
We should use a better allocator for other linux, too.

See https://github.com/swc-project/swc/issues/4790

**Comment by Brooooooklyn** [comment]
after this PR  jemalloc will be applied to `linux-x64-gnu` and `linux-aarch64-gnu`:

`[target.'cfg(all(target_os = "linux", target_env = "gnu", any(target_arch = "x86_64", target_arch = "aarch64")))'.dependencies]`

**Comment by kdy1** [comment]
Oh, I see. Thank you!
I-ll mergr this PR tomorrow

**Review by kdy1 — APPROVED** [review]
Thank you!

---

swc-bump:
 - swc_node_base

**Pull request merged**
