### PR TITLE
fix(html/minifier): fix comments removing

### PR DESCRIPTION
**Pull request by alexander-akait**
**Description:**

There are two things:
- A lot of tests for tests (and avoid future regressions)
- Fix removing comments document and document fragment

**BREAKING CHANGE:**

No

**Related issue (if exists):**

No

### CODE REVIEW

**Comment by alexander-akait** [comment]
@kdy1 Fixed :+1:

**Review by kdy1 — DISMISSED** [review]
Thank you!

---

swc-bump:
 - swc_html_minifier

**Comment by alexander-akait** [comment]
@kdy1 Rebased :+1:

**Review by kdy1 — APPROVED** [review]
Thanks!

**Pull request merged**
