### PR TITLE
expose Fold in swc_ecma_visit

### PR DESCRIPTION
**Pull request by bartlomieju**
Trying to use `Fold` I hit this error:
```
error[E0432]: unresolved import `swc_ecma_visit::Fold`
  --> src/rules/no_dupe_args.rs:12:5
   |
12 | use swc_ecma_visit::Fold;
   |     ^^^^^^^^^^^^^^^^^^^^ no `Fold` in the root

error: aborting due to previous error
```

### CODE REVIEW

**Comment by kdy1** [comment]
Oh... I made a mistake. Thanks :)

**Comment by kdy1** [comment]
I noticed that Folder had a bug. I'll fix it today (if possible) or tomorrow (absolutely possible).

**Comment by bartlomieju** [comment]
@kdy1 can you release `swc_ecma_visit` when you'll get the moment?

**Comment by kdy1** [comment]
@bartlomieju I fixed it and published it. :)

**Pull request merged**
