### PR TITLE
fix(es): Resolve the inline sourcemap decode error

### PR DESCRIPTION
**Pull request by limerickgds**
**Description:**
The decode error caused by other content after resolving sourceMappingURL. Babel doesn't have this issue because it judges based on the comments, which is more accurate.
https://github.com/babel/babel/blob/master/packages/babel-core/src/transformation/normalize-file.js#L63

**BREAKING CHANGE:**

no

**Related issue (if exists):**

### CODE REVIEW

**Comment by limerickgds** [comment]
Whether it is necessary to align with Babel and process based on the last map `comment` in process_js_inner?

**Comment by kdy1** [comment]
I think we can follow the behavior of babel here, although we don't _need_ to follow it.

**Comment by limerickgds** [comment]
> I think we can follow the behavior of babel here, although we don't _need_ to follow it.

So, would this be a solution for now? It seems to cover most use cases. After all, Babel doesn't handle inline sourcemaps perfectly either, and it doesn't solve the problem of multiple inline sourcemaps.

**Comment by kdy1** [comment]
Yeah, I will review it soon (today or tomorrow)

**Review by kdy1 — APPROVED** [review]
Thanks!

---

swc-bump:
 - swc

**Pull request merged**
