### PR TITLE
chore: Bump `libc` crate

### PR DESCRIPTION
**Pull request by huajingyun01**
Upgrade libc to v0.2.155 to support LoongArch64.

Libc release notes : https://github.com/rust-lang/libc/releases
The relevant change: https://github.com/rust-lang/libc/pull/3606

Resolve the following errors:
```
help: if you import `c_char`, refer to it directly
    |
219 - pub unsafe extern "C" fn stat64(pathname: *const ::c_char, statbuf: *mut ::stat64) -> ::c_int {
219 + pub unsafe extern "C" fn stat64(pathname: *const c_char, statbuf: *mut ::stat64) -> ::c_int {
    |

error[E0573]: expected type, found function `stat64`
   --> /home/alpine/.cargo/registry/src/index.crates.io-6f17d22bba15001f/libc-0.2.153/src/unix/linux_like/linux/musl/lfs64.rs:219:74
    |
219 | pub unsafe extern "C" fn stat64(pathname: *const ::c_char, statbuf: *mut ::stat64) -> ::c_int {
    |                                                                          ^^^^^^^^ not a type

error[E0412]: cannot find type `c_char` in the crate root
   --> /home/alpine/.cargo/registry/src/index.crates.io-6f17d22bba15001f/libc-0.2.153/src/unix/linux_like/linux/musl/lfs64.rs:224:54
    |
224 | pub unsafe extern "C" fn statfs64(pathname: *const ::c_char, buf: *mut ::statfs64) -> ::c_int {
    |                                                      ^^^^^^
    |
   ::: /home/alpine/.cargo/registry/src/index.crates.io-6f17d22bba15001f/libc-0.2.153/src/unix/mod.rs:6:1

```

Thanks.

### CODE REVIEW

**Review by kdy1 — CHANGES_REQUESTED** [review]
Preventing merging for now. I'm not sure what's the point of this PR.

**Comment by kdy1** [comment]
Do you want to contribute to SWC but you use LoongArch64?

**Comment by huajingyun01** [comment]
> Do you want to contribute to SWC but you use LoongArch64? Otherwise, you don't need to modify `Cargo.lock` of SWC

@kdy1  yes, I  can build and run swc on LoongArch64 using this change. I also submitted [this patch to alpine](https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/66903)

If it is possible to upgrade libc from upstream, it will be very friendly for package swc for alpine.

Thanks.

**Comment by kdy1** [comment]
Why do you `build` swc from there? SWC provides a prebuilt binary for arm linux

**Comment by huajingyun01** [comment]
> Why do you `build` swc from there? SWC provides a prebuilt binary for arm linux

I am working on [the Alpine Linux LoongArch64 port]( https://gitlab.alpinelinux.org/alpine/tsc/-/issues/72). 
During this process, I found that a large number of software failed to compile due to low libc versions（loongarch64 architecture support is not added to src/unix/linux_like/linux/musl). swc is one of them.

**Comment by kdy1** [comment]
Can you sign the CLA?

**Comment by huajingyun01** [comment]
> Can you sign the CLA?

Have done, thanks.

**Review by kdy1 — APPROVED** [review]
swc-bump:
 - dbg-swc

**Pull request merged**
