### PR TITLE
feat(es/transforms/react): Support fast refresh

### PR DESCRIPTION
**Pull request by Austaras**
Continue on @vovacodes 's great work to port react fast refresh to swc. Due to fundamental difference between babel and swc it's not feasible to produce exact same output, but I managed to pass all original tests.

I'll figure out option tomorrow. There's still one thing need help @kdy1 : How to iterate over every comment in a single file like in [original code](https://github.com/facebook/react/blob/634cc52e6174b506dee79d908f50ce1ee19f4fbf/packages/react-refresh/src/ReactFreshBabelPlugin.js#L263)? Maybe you could add an extra method in `Comments` trait?

### CODE REVIEW

**Comment by kdy1** [comment]
Do you mean literally all comments of a file?
If then, I'll add a method to `Comments`.

**Comment by Austaras** [comment]
Yes I do mean every comment. It's  quite confusing why react team chooses to do so though.

**Comment by kdy1** [comment]
Hmm.. I found that it's very hard to get all comments without knowing spans.
Also, because rust does not have a gc, so... storing same comment multiple times is not an option.

So I used a bit different approach. `CommentCollector` can be used to check all comments.

**Comment by Austaras** [comment]
I have tested your apporach, however comment in following code doesn't seem like to be detected
``` js
    function Bar() {
      const [foo, setFoo] = useState(0);
      React.useEffect(() => {
        // @refresh reset
      });
      return <h1>{foo}</h1>;
    }
```
seems like any comment in a empty `BlockStmt` will be ignored, could you fix it?

**Comment by kdy1** [comment]
Nice catch! I'll fix it with another pr asap.

**Comment by kdy1** [comment]
I fixed the issue, but I guess you should get comments by getting leading comments of `Span.hi`.

**Comment by Austaras** [comment]
Updated. Another problem: why does swc generate
```js
    const bar = _hooks.useFancyState();
```
instead of
```js
    const bar = (0, _hooks).useFancyState();
```
when targeting commonjs?

**Review by kdy1 — APPROVED** [review]
LGTM. Thank you a lot!

**Comment by Austaras** [comment]
Thanks for taking your time to review this! I'll continue to work on this branch to catch up with the update to the original implementation this morning, and provide a rich config options to end user

**Pull request merged**
