### PR TITLE
fix(es/decorators): Resolve enum for `design:returntype`

### PR DESCRIPTION
**Pull request by ZakisM**
**Description:**

Resolve enum types in `design:returntype`.

### CODE REVIEW

**Comment by kdy1** [comment]
cc @magic-akari What's your thought about this? We cannot support enums in other files due to some fundamental reasons.

**Comment by magic-akari** [comment]
> cc @magic-akari What's your thought about this? We cannot support enums in other files due to some fundamental reasons.

I have no idea. I suppose that tsc will emit error for this case.

**Comment by ZakisM** [comment]
I don't think `isolatedModules: true` will highlight this as an issue. This change was meant to match the behaviour that we are [currently](https://github.com/swc-project/swc/blob/97d57f0e4fcaca2e03241ddb4fbe19f449b33ecd/crates/swc_ecma_transforms_proposal/src/decorators/legacy/metadata.rs#L202) doing for `design:type` where if the enum is declared in the same file then the type is resolved correctly. For enums imported from other files we will need to re-look at https://github.com/swc-project/swc/issues/1584.

**Review by kdy1 — APPROVED** [review]
Thanks!

---


swc-bump:
 - swc_ecma_transforms_proposal

**Pull request merged**
