### PR TITLE
fix(plugin-runner): More details on pointer conversion failures

### PR DESCRIPTION
**Pull request by stahlbauer**
**Description:** This change set provides (1) additional debug infos in cases when conversions of pointers between the Rust world and the WASM world fail, and (2) fixes an existing misleading error message. 

**Related issue (if exists):** This should help to make progress addressing https://github.com/swc-project/swc/issues/6249.

### CODE REVIEW

**Comment by kdy1** [comment]
You can build by yourself and replace node binding to check the cause. This PR is not required

**Comment by kdy1** [comment]
You need `--features plugin`

**Comment by stahlbauer** [comment]
Thanks for the hint on the `plugin` feature. That is, actually the `musl` target has to be build to work with Napi? https://github.com/swc-project/swc/blob/410ec6f6c7cc234a7bf7b512508e2578989d4a33/.github/workflows/publish-node.yml#L62

**Comment by kdy1** [comment]
I'm sorry, but I didn't get what you are saying. Can you explain in other words? (sorry for my bad English, I'm not an English native)

**Comment by stahlbauer** [comment]
We are trying to build the SWC binaries such that they can be used within the NodeJs package, that is, to copy them in the end into `./node_modules/@swc/core` of our NodeJs project to use our the build of SWC with the modifications we made for debugging purposes.

I think that having a list of steps to perform (starting with a fork of the SWC repo with some modifications) for such debugging endeavors would be helpful for the community as a whole. At least, I would appreciate it ;)

I am on a recent Linux machine with Ubuntu and 64bit.

**Comment by stahlbauer** [comment]
One problem I am facing at the moment is that the SWC crates are used from the registry and not from the monorepo itself.

**Comment by stahlbauer** [comment]
By patching the Cargo.toml as indicated above, I was able to reproduce use my own SWC binary. The plugin runner now fails with:
```
thread '<unnamed>' panicked at 'Should be able to convert the value -2147188304 to u32', /swc-fork/crates/swc_plugin_runner/src/memory_interop.rs:37:29
```
This is the adjusted output proposed by this pull request.

**Comment by kdy1** [comment]
cc @kwonoj Any thoughts? I think it's `-1`. So it can be 32bit (wasm) vs 64 bit (host) I guess, but not sure if it's the case.

**Comment by kwonoj** [comment]
Yes, seems like it's some kind overflow peeking by number only, but to confirm we need to see if host created number larger than u32 really. I'm not sure either if  memory interop supposed to create 64 as allocation happens in wasm runtime would create wasm's memory boundary.

**Comment by stahlbauer** [comment]
Would it make sense to use `u32` for pointer values instead of `i32`? I am missing some Rust and WASM background here.

The code uses `i32` for pointers where I would expect `u32` to be more appropriate, for example:
```
#[tracing::instrument(level = "info", skip_all)]
pub fn allocate_return_values_into_guest(
    memory: &Memory,
    alloc_guest_memory: &NativeFunc<u32, i32>,
    allocated_ret_ptr: i32,
    serialized_bytes: &PluginSerializedBytes,
) {
```

**Comment by stahlbauer** [comment]
I have changed the pointer types to `u32` locally and things got better. Now I touched the 4GB barrier and got OOM errors. The memory graph with several invocations of SWC looks as follows: 
image

I have produced this plot using `mprof`, a set of Python scripts that can also record memory consumed by child processes; it performs memory sampling.

**Comment by kdy1** [comment]
Are you facing it with next dev server?

**Comment by kdy1** [comment]
I mean, a long-running process

**Comment by stahlbauer** [comment]
I am facing the problem when instrumenting a larger JS bundle with https://github.com/kwonoj/swc-plugin-coverage-instrument . I am invoking that plugin programatically. I am doing some additional transformations on the resulting AST.

**Comment by stahlbauer** [comment]
The process is short lived.

**Comment by kdy1** [comment]
I'm aware of the memory issue, but I didn't think someone would process a such big bundle

**Comment by kdy1** [comment]
How big is it? What's the sum of all inputs to swc within a single process?

**Comment by stahlbauer** [comment]
The file that is passed to SWC has 500KB (only) and is a small react application that was bundled using Vite/ESbuild. I would have bundles of 100MBs and more to work on.

**Comment by stahlbauer** [comment]
(The size of the bundles to work on is actually the reason to use SWC instead of Babel).

**Comment by kdy1** [comment]
Hmm... Then it's not the issue I was aware of

**Comment by stahlbauer** [comment]
What do you think about changing the pointers from `i32` to `u32` in a first step? Does this make sense from your perspective?

**Comment by stahlbauer** [comment]
At least, the real cause of the problem is no longer masked then:
```
    1: RuntimeError: unreachable
           at abort (<module>[35215]:0x935d9c)
           at std::sys::wasi::abort_internal::h58865237df468a7d (<module>[35129]:0x92f141)
           at std::process::abort::h74127d44f02b51e4 (<module>[35162]:0x9315d9)
           at rust_oom (<module>[35172]:0x931bb5)
           at __rg_oom (<module>[35260]:0x9379e3)
           at __rust_alloc_error_handler (<module>[12390]:0x431f7b)
           at alloc::alloc::handle_alloc_error::rt_error::he27203bd7d9482b1 (<module>[35249]:0x9374ba)
```

**Comment by kdy1** [comment]
I think it's fine, but I want to ask @kwonoj about opinions

**Comment by kwonoj** [comment]
I think it is no harm to try, at least it shouldn't be a breaking changes. But as discussed above, if the input size is real culprit we don't have lot of options to solve it. wasm64 is probably not available in a short timeframe.

**Comment by stahlbauer** [comment]
@kdy1 @kwonoj  I have pushed my changes. In case you would like to integrate my changes, I would welcome a review and would also be willing to do the necessary rework.

**Review by kdy1 — APPROVED** [review]
swc-bump:
 - swc_common

**Comment by kdy1** [comment]
@stahlbauer  Please allow editing PR

**Comment by stahlbauer** [comment]
@kdy1 : You should have the permissions now. Thanks.

**Comment by stahlbauer** [comment]
As a follow-up, I have created the following ticket: https://github.com/swc-project/swc/issues/6404

**Review by kdy1 — CHANGES_REQUESTED** [review]
CI failed

**Comment by stahlbauer** [comment]
@kdy1: I will have a look.

**Review by kdy1 — APPROVED** [review]

**Pull request merged**
