### PR TITLE
feat(html/minifier): Remove `script` `type` attribute

### PR DESCRIPTION
**Pull request by g-plane**
**Description:**

```html
<script type="text/javascript"></script>
```

to

```html
<script></script>
```

cc @alexander-akait

### CODE REVIEW

**Review by alexander-akait — COMMENTED** [review]
Let's add tests where type is not text/javascript + with type="module".

Also there are other types https://github.com/terser/html-minifier-terser/blob/master/src/htmlminifier.js#L155, make sense to remove them too

**Comment by g-plane** [comment]
Those types shouldn't be removed, I think. For example, whether there's `type="module"` or not can introduce different behaviors.

**Comment by alexander-akait** [comment]
@g-plane Yep, `type="module"` should be keeped, just to avoid regressions

**Comment by alexander-akait** [comment]
But `application/javascript` is unnecessary (and other), there is logic https://github.com/terser/html-minifier-terser/blob/master/src/htmlminifier.js#L555

**Comment by g-plane** [comment]
I think it shouldn't.

From [WHATWG HTML spec](https://html.spec.whatwg.org/multipage/scripting.html#script-processing-model):

the step 8 of **prepare a script**:

> if the script element has neither a type attribute nor a language attribute, then let the script block's type string for this script element be `"text/javascript"`.

Only `text/javascript` can be omitted.

**Comment by alexander-akait** [comment]
@g-plane Other types are legacy, if we look at current spec we even don't found these types, they are depcrecated and no used in modern code, but I think it is safe to remove them right now, but yes, we should keep `type` for other, because for example it can be `text/babel` (for runtime in babel) and not only

**Review by alexander-akait — APPROVED** [review]
Thanks, looks good

**Review by kdy1 — APPROVED** [review]
Thank you!

---

swc-bump:
 - swc_html_minifier

**Review by kdy1 — APPROVED** [review]

**Comment by g-plane** [comment]
@kdy1 Can you re-run CI? Some failed to install dependencies.

**Pull request merged**
