### PR TITLE
fix(es/codegen): Remove extra spaces in `AssignPatProp` and `KeyValuePatProp`

### PR DESCRIPTION
**Pull request by dsherret**

### CODE REVIEW

**Comment by dsherret** [comment]
I'm not sure what's up with the swc tests. I always get: `Lazy instance has previously been poisoned` locally

**Comment by kwonoj** [comment]
> I'm not sure what's up with the swc tests. I always get: Lazy instance has previously been poisoned locally

Try to `recursively` cargo clean, there are some tests not belong to cargo's workspace and leftover build artifact can affect tests. Usually this error means test runner failed to build those internal projects.

**Comment by dsherret** [comment]
@kwonoj thanks, I tried running `cargo clean` and `cargo clean-recursive`, but the error still persists.

**Comment by kdy1** [comment]
I'll update test refs

**Review by kdy1 — APPROVED** [review]
swc-bump:
 - swc_ecma_codegen

**Pull request merged**
