### PR TITLE
fix(es/preset-env): realign with babel-polyfills

### LINKED ISSUE #2209: core-js definitions are not fully injected with useBuiltIns: usage
**Describe the bug**

When using `env: mode: "entry"` with TypeScript and `Promise.any`, the output file should include not only `promise.any` module but also `esnext.agregate-error` module. 

For reference: https://github.com/zloirock/core-js/issues/737 https://github.com/babel/babel/issues/10910

**Input code**

```ts
Promise.any([]);
```

**Config**

```json
{
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "tsx": false,
      "dynamicImport": false,
      "decorators": false
    },
    "target": "es2015"
  },
  "env": {
    "target": {
      "node": "10"
    },
    "mode": "usage",
    "coreJs": "3.17",
    "shippedProposals": true
  },
  "module": {
    "type": "commonjs"
  },
  "sourceMaps": true
}
```

**Expected behavior**

Considering the output file:

```js
"use strict";
require("core-js/modules/es.promise");
require("core-js/modules/es.object.to-string");
require("core-js/modules/esnext.promise.any");
require("core-js/modules/es.string.iterator");
require("core-js/modules/es.array.iterator");
require("core-js/modules/web.dom-collections.iterator");
Promise.any([]);
```

It should also include `require("esnext.agregate-error")` according to https://github.com/zloirock/core-js/issues/737.

**Version**

```bash
$ yarn swc --version
yarn run v1.22.11
$ /Users/pan93412/Projects/check_env/node_modules/.bin/swc --version

@swc/cli: 0.1.49
@swc/core: 1.2.84

✨  Done in 0.24s.
```

**Additional context**

Thanks a lot! :)

### PR DESCRIPTION
**Pull request by Austaras**
**Description:**

It's weird that it's a must to use macro for static array concat in rust.

**BREAKING CHANGE:**

**Related issue (if exists):**
closes #2209

### CODE REVIEW

**Review by kdy1 — APPROVED** [review]
Thanks!

---

swc-bump:
 - swc_ecma_preset_env

**Comment by zloirock** [comment]
It's still incomplete. For example, I don't see features like `AsyncIterator` or [modules from the latest versions](https://github.com/zloirock/core-js/blob/master/packages/core-js-compat/src/modules-by-versions.mjs).

**Comment by Austaras** [comment]
> It's still incomplete. For example, I don't see features like `AsyncIterator` or [modules from the latest `core-js` versions](https://github.com/zloirock/core-js/blob/master/packages/core-js-compat/src/modules-by-versions.mjs).

`AsyncIterator` has been added

**Comment by zloirock** [comment]
Also need to add new modules to `data.rs`. For example, add `.indexed` similarly to `.toIndexedPairs`; `.push`, `.unshift`, maybe something else. Some features stabilized, for example `esnext.array.find-last` -> `es.array.find-last`.

**Comment by Austaras** [comment]
> Also need to add new modules to `data.rs`. For example, add `.indexed` similarly to `.asIndexedPairs`; `.push`, `.unshift`, maybe something else. Some features stabilized, for example `esnext.array.find-last` -> `es.array.find-last`.

Maybe we should wait for babel people to change them, or at least add them in a seperate pr.

**Review by kdy1 — APPROVED** [review]
Thank you!

---

swc-bump:
 - preset_env_base --breaking

**Comment by zloirock** [comment]
> Maybe we should wait for babel people to change them, or at least add them in a seperate pr.

It seems Babel people wait when I'll add it for them.

**Review by kdy1 — APPROVED** [review]

**Comment by zloirock** [comment]
@Austaras https://github.com/babel/babel-polyfills/pull/138

**Pull request merged**
