### PR TITLE
chore(ci): Fix publish action

### PR DESCRIPTION
**Pull request by kdy1**
**Description:**

### CODE REVIEW

**Comment by Brooooooklyn** [comment]
@kdy1 hey, I'm working on this at the same time, I'll push to your branch with my works

**Review by Brooooooklyn — APPROVED** [review]

**Comment by Brooooooklyn** [comment]
@kdy1 done

**Comment by kdy1** [comment]
Thanks! I'll review/merge once I get back to my pc.

**Review by kdy1 — COMMENTED** [review]
swc-bump:
 - dbg-swc

**Comment by kdy1** [comment]
@Brooooooklyn Thank you!

**Pull request merged**
