### PR TITLE
fix(es/compat): Fix `classes` pass

### LINKED ISSUE #3106: Methods with non-identifier characters transpile with invalid output
### Describe the bug

When methods have non-identifier characters (and use quotes in the input), the output contains a function with an invalid name.

### Input code

```typescript
class ValidationStrategy {
    static "object?"(value) {
        return 1;
    }

    static "string!"(value) {
        return 2;
    }
}
console.log(ValidationStrategy);
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "ecmascript",
      "jsx": false
    },
    "target": "es5",
    "loose": false,
    "minify": {
      "compress": false,
      "mangle": false
    }
  },
  "module": {
    "type": "es6"
  },
  "env": {
    "coreJs": 3,
    "mode": "usage"
  },
  "minify": false,
  "isModule": true
}
```

### Playground link

https://play.swc.rs/?version=1.2.115&code=H4sIAAAAAAAAA0vOSSwuVghLzMlMSSzJzM8LLilKLElNr1So5lIAguISoGiyglJ%2BUlZqcom9kkZZYk5pqiZUFgSKUktKi%2FIUDK3BIrVcKNqKS4oy89IVcWszgmmr5UrOzyvOz0nVy8lP18B0j6Y1FwD2vn2wqwAAAA%3D%3D&config=H4sIAAAAAAAAA0WNTQoDIQxG75K1u9Iu5giFHiLYjFj8I9FSEe9enTp0J997eTZ4iYatQUIW4vmSGjJ%2BYAPSHkWzTRnU0Ma0oxPqCjKyoTwVuQ7mYhRaVIG3we51lnT0iUnkjzAYd5p9hHx8ljk0yDXREbzB2Cm8fwGm%2Bzi%2FHObkRdDQNM5fVtnKY6UyF%2BpfKYX%2FzdcAAAA%3D

### Expected behavior

The output should be valid JS

### Actual behavior

```js
    _createClass(ValidationStrategy, null, [
        {
            key: "object?",
            value: function object?(value) { // <----------
                return 1;
            }
        },
```

### Version

1.2.115

### Additional context

https://github.com/parcel-bundler/parcel/issues/7468

### PR DESCRIPTION
**Pull request by kdy1**
swc_ecma_ast:
 - Add `Ident::verify_symbol`.

swc_ecma_transforms_compat:
 - Don't generate invalid identifiers. (Closes #3106)

### CODE REVIEW

**Comment by magic-akari** [comment]
https://github.com/babel/babel/blob/69ae3b5a250d60618702751aa2aa4f56ccd43988/packages/babel-types/src/converters/toIdentifier.ts#L4-L26

Babel uses algorithms to normalize Identifier.
But can we use anonymous functions without names here?

**Comment by kdy1** [comment]
@magic-akari What do you mean by

> But can we use anonymous functions without names here?

**Comment by magic-akari** [comment]
> @magic-akari What do you mean by
> 
> > But can we use anonymous functions without names here?

```diff
{
    key: "object?",
-   value: function object?(value) {
+   value: function(value) {
        return 1;
    }
},
```

**Comment by kdy1** [comment]
Yeah, it's possible but it will result in a bad stack trace. (I expect js engines to assign the name `value` to those functions)

**Comment by magic-akari** [comment]
> Yeah, it's possible but it will result in a bad stack trace. (I expect js engines to assign the name `value` to those functions)

It makes sense. I forgot the stack trace.
Developers experience is important.

**Pull request merged**
