### PR TITLE
fix(es/transforms/compat/es2015): fix for-of variable scope in generator

### PR DESCRIPTION
**Pull request by hi-ogawa**
Fixes https://github.com/swc-project/swc/issues/2624

I found that by reordering `block_scoping` and `regenerator` passes in `es2015` compat, it would mitigate the scoping issue since this enables for `"_loop"` temporary function to be correctly introduced for the body of `for_of` pass.
I'm not too sure if this doesn't bring any regression but I thought this could be a reasonable idea to try, so here is my first PR.
I would appreciate any feedback and thanks a lot for the review!

### CODE REVIEW

**Review by kdy1 — APPROVED** [review]
Thanks!

I think your approach was correct.

**Comment by kdy1** [comment]
I'll revert this as this caused a serious bug. 
See https://github.com/vercel/next.js/issues/31479 for more details

**Comment by hi-ogawa** [comment]
Sorry about that. I should've been more careful.
Let me think again if I can find a legitimate fix.

**Comment by kdy1** [comment]
Don't worry the actual problem is that there was a no test for it.

**Pull request merged**
