### PR TITLE
feat(html/minifier): compress default attributes for svg

### PR DESCRIPTION
**Pull request by alexander-akait**
**Description:**

Compress SVG attributes (default values)

**BREAKING CHANGE:**

No

**Related issue (if exists):**

No

### CODE REVIEW

**Review by kdy1 — APPROVED** [review]
Thank you!

---

swc-bump:
 - swc_html_minifier

**Review by kdy1 — CHANGES_REQUESTED** [review]
CI failed

**Comment by alexander-akait** [comment]
@kdy1 Fixed

**Review by kdy1 — APPROVED** [review]
Thank you!

**Pull request merged**
