### PR TITLE
fix(html/parser): bugs

### PR DESCRIPTION
**Pull request by alexander-akait**
**Description:**

Here:
- refactor test - move tests with errors in recovery + snapshots errors and rename restructure test
- fix found bugs in tokenizer and parser which were found duing refactor

After this I will add https://github.com/html5lib/html5lib-tests/ (used all HTML parser) to ensure we output the same AST as other parsers

**BREAKING CHANGE:**

No

**Related issue (if exists):**

No

### CODE REVIEW

**Review by kdy1 — APPROVED** [review]
Thanks!

---

swc-bump:
 - swc_html_parser

**Review by kdy1 — CHANGES_REQUESTED** [review]
CI failed after rebasing

**Comment by alexander-akait** [comment]
@kdy1 Rebased and fixed

**Review by kdy1 — APPROVED** [review]
Thanks!

---

swc-bump:
 - swc_html_parser

**Pull request merged**
