### PR TITLE
fix(es/codegen): Remove extra space of import decl

### PR DESCRIPTION
**Pull request by nuintun**
See: #1690

### CODE REVIEW

**Review by kdy1 — APPROVED** [review]
Thanks!

**Comment by kdy1** [comment]
Semes like CLA bot has a bug. It said all contributors signed, but it now says you didn't sign it.
Anyway, change is very trivial and I don't think reverting worths it.

**Comment by nuintun** [comment]
@kdy1 I've already signed it, but I don't know why CLA didn't pass the test.

企业微信截图_20210730092323

**Comment by kdy1** [comment]
Maybe email address is problematic.

**Comment by nuintun** [comment]
@kdy1 Fixed~

**Pull request merged**
