### PR TITLE
WIP: A Rudimentary Plugin System

### PR DESCRIPTION
**Pull request by Michael-F-Bryan**
This adds the basic infrastructure for a binary plugin system. We essentially use `LibLoading` or `dlopen` to load a DLL at runtime and execute a couple well known symbols to register a plugin.

Later on we may want to create a small utility which can download a plugin repo (e.g. from GitHub), compile it, then copy the DLL to some user-specific plugins directory. We'd also need some sort of plugin discovery mechanism (e.g. a `SWC_PLUGIN_PATH` environment variable which defaults to the plugin directory) to know where to look when loading plugins as part of the build process. 

Outstanding questions:

- What should a plugin look like? Does it implement a special `Plugin` trait, is it just an implementation of `Fold<T>`, etc? This probably ties in with #41.
- `rustc` doesn't guarantee ABI compatibility between versions, meaning each plugin would have to be compiled with *exactly* the same version of `rustc` as `swc`
- How do you declare a plugin? Should we have an equivalent of `.babelrc`, or maybe take a different approach?
- Do we want to support writing plugins in other languages?
- How will the rest of the system want to use loaded plugins?

This works towards #18.

### CODE REVIEW

**Comment by kdy1** [comment]
Is loading dll safe? I'm not sure about it.

**Comment by Michael-F-Bryan** [comment]
> Is loading dll safe? I'm not sure about it.

That's a bit of an open question and depends on how you implement it. You normally create a safe interface which everyone needs to go through in order to register a plugin (e.g. using a `Plugin` trait object). In this case, we use a `register_plugin!()` macro to generate functions with known symbol names that the plugin loader can use. 

Because we would have complete control over the exported functions, we can make sure everything stays type safe. ABI problems can be avoided by also exporting functions which return the `rustc` and plugin library versions and checking for compatibility before starting the main registration procedure.

From a security standpoint it's no less safe than any other plugin mechanism. At some point we're letting 3rd party code be executed, and that code can do whatever it wants.

> It exposes plugin api from binding and plugin can be written is node js. I also think plugins should be implemented in javascript (considering rust's learning curve).
(Best is being drop-in-replacement of the babel, but I don't think it's possible)

Considering we're targeting the JavaScript community, I agree that it makes sense to write plugins in JavaScript. That said, you'd need to write loads of boilerplate code to allow NodeJS to access Rust data, which is arguably a lot less safe than using a Rust DLL which imports and uses the `swc` crates internally.

Considering code transformations are normally small functions called in tight loops and that each FFI call adds a lot of overhead (due to inhibiting optimisations, marshalling data back and forth, etc.), I wouldn't be surprised if we actually get *worse* performance than Babel by using JavaScript plugins...

**Comment by kdy1** [comment]
I'm not sure which feature should be implemented as a plugin. I mean, almost features of babel / closure compiler / webpack will be statically linked.

I want to make swc as a final step of compilation. (for initial release)


e.g.)

**v0.1**:
    - jsx  -> (babel) -> ecmascript -> (swc) -> bundle.js

**v0.2**:
    - jsx / stage 0 ~ 3  -> (swc) -> bundle.js

**Comment by memchk** [comment]
@Michael-F-Bryan If you are using macros to generate the plugin interface, could you not also mark those interfaces as `#[repr(C)]`, and generate the translation code? This would allow the plugin and swc to be built with differing rustc versions.

**Comment by ishitatsuyuki** [comment]
Personally, I'm not in favor of dynamic linking based plugin approaches. Version or ABI mismatch can easily occur, plus it's simply too hard to get unloading right.

Making things too dynamic can degrade performance; before deciding on the interface, what are the things that we want to be pluggable?

**Comment by kdy1** [comment]
I don't want compiler passes to be pluggable.
I prefer something like javascript plugin or https://github.com/kentcdodds/babel-plugin-macros

Most preferable way I think is implementing https://github.com/kentcdodds/babel-plugin-macros as a static plugin and encourage user to use macros instead of developing plugin.

**Pull request closed without merging**
