### PR TITLE
Derive a few common traits for simple public types

### PR DESCRIPTION
**Pull request by alvra**
This project contains three identical versions of two simple public enums: `IndentType` and `LineFeed`.

For a project I would like to be able to write tests with `assert_eq!()`, but that requires `Eq` and `Debug`. I thought it would make sense to also implement `Clone` and `Copy`.

### CODE REVIEW

**Comment by alvra** [comment]
I also added for `Eq` for ecma `EsConfig`, `TsConfig`, and `Syntax`.

**Review by kdy1 — APPROVED** [review]
Thanks!

---

swc-bump:
 - swc_css_codegen
 - swc_ecma_parser
 - swc_html_codegen
 - swc_xml_codegen

**Comment by alvra** [comment]
The "binary size check" encountered some network issue; but I assume the size hasn't changed. Everything else is green. Do you need anything else to get this in?

**Comment by kdy1** [comment]
I'll not merge PR because of an issue related to plugin.
After merging two PRs related to plugins, I'll publish a new version and if it's working I'll resume merging PRs

**Comment by alvra** [comment]
Great, thanks!

**Pull request merged**
