### PR TITLE
fix(ecma/codegen): don't print whitespaces for comments in minify mode

### PR DESCRIPTION
**Pull request by alexander-akait**
**Description:**

We don't need extra whitespace for comments when we print minified output

**BREAKING CHANGE:**

No

**Related issue (if exists):**

No

### CODE REVIEW

**Review by kdy1 — DISMISSED** [review]
swc-bump: 
 - swc_ecma_codegen

**Comment by alexander-akait** [comment]
@kdy1 Sounds like bug on CI (maybe cache)? No bugs on `CI / Test node bindings - ubuntu-latest (pull_request)` :confused:

**Review by kdy1 — DISMISSED** [review]

**Comment by alexander-akait** [comment]
@kdy1 I really don't undestand when I run it locally it removes spaces (i.e. `CI / Test node bindings - ubuntu-latest (pull_request) ` is `green`), but when it is on CI - `windows` failed, maybe cache here? Really don't undestand, why OS changes it

**Comment by alexander-akait** [comment]
@kdy1 Can you remove CI cache?

**Comment by kdy1** [comment]
It's not problem of CI.
Use cargo patch to use correct version for testing

**Comment by alexander-akait** [comment]
@kdy1 But I think the problem is not my side, if I remove whitespaces in tests it:
- `CI / Test node bindings - ubuntu-latest (pull_request)` - Green
- `CI / Test node bindings - windows-latest (pull_request)` - Red

If I return whitespaces, it:
- `CI / Test node bindings - ubuntu-latest (pull_request)` - Red
- `CI / Test node bindings - windows-latest (pull_request)` - Green

But I can do nothing with CI

**Review by kdy1 — APPROVED** [review]

**Pull request merged**
