### PR TITLE
Feature/transform react fast refresh

### PR DESCRIPTION
**Pull request by vovacodes**
This is still work-in-progress but any early comments are welcome.
 
Implements https://github.com/swc-project/swc/issues/588

### CODE REVIEW

**Comment by kdy1** [comment]
Cool, thanks a lot!
Please ping me if you need any help.

**Comment by kdy1** [comment]
If you want, I can finish this pr.
I have some spare time to do so.

**Comment by vovaguguiev** [comment]
@kdy1 Thanks, I'd love to finish it just to get a code review from you so I can learn more how to contribute to swc, will be a great learning exercise for me as well, but I'll let you know if I'm stuck 🙏🏼

**Comment by vovaguguiev** [comment]
@kdy1 I got no time to focus on  it in the past week 😞, so feel free to take it over, otherwise, I will try to continue working on that later when I have a spare moment

**Comment by Austaras** [comment]
any progress in this pr?

**Comment by kdy1** [comment]
@Austaras Not yet, I'm currently too busy.

**Comment by ije** [comment]
my implement: https://github.com/alephjs/aleph.js/blob/master/compiler/src/fast_refresh.rs, will make a PR when it is stable.

**Comment by devongovett** [comment]
@ije any updates on that? I tried out your transform in Parcel and it seems to work well so far. Found one bug that I sent you a PR for: https://github.com/alephjs/aleph.js/pull/213. Would be great to get this into SWC core though! 😄

**Comment by ije** [comment]
@devongovett thanks, will merge it into SWC after alephjs 0.3 released.

**Comment by kdy1** [comment]
@ije I'm sorry for bothering you, but I want to know if you are going to send a pr.

**Comment by ije** [comment]
@kdy1 yes, i will do it later!

**Comment by piotrpalek** [comment]
sorry to bother, but is this implemented, or was it abandoned? I'm trying to use swc-loader with react fast refresh as well :)

**Comment by kdy1** [comment]
It's implemented

**Pull request closed without merging**
