### PR TITLE
fix(es/minifier): Check type of assignment target before merging assignments

### PR DESCRIPTION
**Pull request by CPunisher**
**Description:**

Collect types of vars, maybe other optimization could benefit from this: `merged_var_type: Option<Value<Type>>`

When the variable is reassigned, the we merge the types with some simple rules:
`None` + `None` = `None`
`None` + `Some(ty)` = `Some(ty)`
`Some(ty1)` + `Some(ty2)` if `ty1` == `ty2` = `Some(ty1)`
Otherwise = Unknown

**Related issue (if exists):**
closes https://github.com/swc-project/swc/issues/8718

### CODE REVIEW

**Comment by kdy1** [comment]
Is collecting initial types enough? I think it can be useful for `const` but not for others

**Comment by CPunisher** [comment]
> Is collecting initial types enough? I think it can be useful for `const` but not for others

No, it's not enough. I realize that the usage analyzer is flow-insensitive, so it's hard to know the accurate type of a variable and I get stuck.

**Comment by CPunisher** [comment]
@kdy1 What do you think of this implementation? This looks more sound than the main branch at the cost of losing some completeness (some cases that can be optimized are not).

**Comment by kdy1** [comment]
I think it's quite a clever idea. Yeah, we have a merging function for merging characteristics of variables, and reusing it for types make sense I think.

**Pull request merged**
