### PR TITLE
fix(bindings/types): Add missing mangle options

### PR DESCRIPTION
**Pull request by chenjiahan**
**Description:**

Add missing mangle options to be consistent with the SWC documentation:

https://swc.rs/docs/configuration/minification#jscminifymangle

image

### CODE REVIEW

**Comment by Austaras** [comment]
You may refer to https://github.com/swc-project/swc/blob/76fe139334b64c9ba62a98dc5319523d21d633f4/crates/swc_ecma_minifier/src/js.rs#L14

**Comment by chenjiahan** [comment]
@Austaras I don't understand what you want me to change specifically. The purpose of this PR is to make TS type definitions consistent with Rust's implementation and SWC's documentation.

image

**Comment by Austaras** [comment]
Sorry, I find the wrong config struct.

**Review by Austaras — APPROVED** [review]

**Comment by chenjiahan** [comment]
Haha, Terser's options are a bit confusing 😂

**Pull request merged**
