### PR TITLE
fix(es/codegen): Fix codegen of ArrowExpr return_type

### LINKED ISSUE #4305: swc_ecma_codegen not rendering ArrowExpr return_type
### Describe the bug

swc_ecma_codegen does not render the `return_type` property of `ArrowExpr`

### Input code

```typescript
let cm = Lrc::new(SourceMap::default());
let code = {
	let mut buf = vec![];

	{
		let mut emitter = Emitter {
			cfg: swc_ecma_codegen::Config {
				..Default::default()
			},
			cm: cm.clone(),
			comments: None,
			wr: JsWriter::new(cm.clone(), "\n", &mut buf, None),
		};

		emitter
			.emit_module(&Module {
				body: vec![ModuleItem::Stmt(Stmt::Expr(ExprStmt {
					span: Default::default(),
					expr: boxed(Expr::Arrow(ArrowExpr {
						span: Default::default(),
						params: vec![],
						type_params: None,
						is_async: false,
						is_generator: false,
						body: BlockStmtOrExpr::Expr(boxed(Expr::Lit(Lit::Bool(Bool {
							span: Default::default(),
							value: true,
						})))),
						return_type: Some(TsTypeAnn {
							span: Default::default(),
							type_ann: boxed(TsType::TsLitType(TsLitType {
								span: Default::default(),
								lit: TsLit::Bool(Bool {
									span: Default::default(),
									value: true,
								}),
							})),
						}),
					})),
				}))],
				span: Default::default(),
				shebang: None,
			})
			.unwrap();
	}

	String::from_utf8_lossy(&buf).to_string()
};
```

### Config

```json
N/A
```

### Playground link

_No response_

### Expected behavior

The return type should be rendered if given, like it is for normal functions.

### Actual behavior

The return type is not rendered.

### Version

0.96.0 local, but issue also exists on the source of `main` branch

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Dionysusnu**
**Description:**
Adds a render for the return_type property of the ArrowExpr node. Impl copied from `emit_fn_trailing`.

**Related issue (if exists):**
Fixes #4305

### CODE REVIEW

**Comment by Dionysusnu** [comment]
Hm, that test seems to be failing because it _expects_ the return type to get stripped from the output. I'm definitely not familiar enough to know what the way to go is here.

**Comment by kdy1** [comment]
The failure of codegen will be fixed by `UPDATE=1 cargo test` in it, and ts issue seems like a bug.
I think it's not removing return type annotation from arrow expressions.

**Comment by kdy1** [comment]
@Dionysusnu If you are busy, I can take on this.
Can you sign the CLA?

**Review by kdy1 — APPROVED** [review]
swc-bump:
 - swc_ecma_codegen

**Pull request merged**
