### PR TITLE
fix(es/decorators): Minimize class declarations transformation

### PR DESCRIPTION
**Pull request by magic-akari**
**Description:**

**BREAKING CHANGE:**

**Related issue (if exists):**

### CODE REVIEW

**Review by kdy1 — COMMENTED** [review]
I think we should check if the mutability of the variable (let/class) is identical, and if not we should add an assumption entry.

I'll check it using chrome

**Comment by kdy1** [comment]
```js

class Foo {
    static {
         Foo = 1;
    }

}
```


```js

let Foo = class Foo {
    static {
         Foo = 1;
    }

}
```


```js

class Foo {
    static field = Foo = 1;

}
```


```js

let Foo = class Foo {
    static field = Foo = 1;

}
```

**Review by kdy1 — APPROVED** [review]
Thank you!

---

swc-bump:
 - swc_ecma_transforms_proposal

**Comment by kdy1** [comment]
Oops there's a merge conflict

**Review by kdy1 — APPROVED** [review]

**Comment by magic-akari** [comment]
There are some broken snapshots introduced in #8257.

**Comment by kdy1** [comment]
Can you update them too?

**Comment by kdy1** [comment]
`Ok` action of CI is bit broken, but not sure about the reason

**Comment by kdy1** [comment]
🤣 CI is so broken so it passed again

**Pull request merged**
