### PR TITLE
feat(node/swc): support for named export `Visitor`

### PR DESCRIPTION
**Pull request by xnuk**
In some environment, default exporting can be problematic.

### CODE REVIEW

**Review by kdy1 — CHANGES_REQUESTED** [review]
Is this useful?
I'm not sure about this.

**Comment by xnuk** [comment]
Currently `@swc/core/Visitor.js` is detected as **CommonJS module** by Node.js' ESM mode (`.mjs`, I know swc doesn't support ESM config files yet, but anyway), and it looks like this:

```javascript
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
class Visitor {
  // ...
}

exports.default = Visitor;
```

And following this:

> The ECMAScript Module Namespace representation of a CommonJS module is always a namespace with a `default` export key pointing to the CommonJS `module.exports` value.
>
> - [Node.js 16 documentation: "CommonJS Namespaces" section in "ECMAScript modules"](https://nodejs.org/dist/latest-v16.x/docs/api/esm.html#esm_commonjs_namespaces)

I need some workaround to import `Visitor` since the default export would be `{ default: Visitor }`:

```javascript
import SwcVisitor from '@swc/core';
const Visitor = SwcVisitor.default;
```

And named export would cause less problem I think?:

```javascript
import { Visitor } from '@swc/core';
```

**Review by kdy1 — COMMENTED** [review]
I'm not sure if `Visitor` itself is useful, and I'm not sure if it's right to encourage usage of it.

**Review by kdy1 — APPROVED** [review]
I decided to merge this.
Thanks!

**Pull request merged**
