### PR TITLE
fix(es/helpers): Add `addInitializer` to field decorators

### LINKED ISSUE #8525: addInitializer missing on class field decorators
### Describe the bug

```ts
function bar(_, ctx) {
  console.log("should not be undefined", ctx.addInitializer);
}
class Foo {
  @bar baz = 1
}


new Foo()
```

outputs undefined

### Input code

```typescript
function bar(_, ctx) {
  console.log("should not be undefined", ctx.addInitializer);
}
class Foo {
  @bar baz = 1
}


new Foo()
```

### Config

```json
{
  "jsc": {
    "parser": { "syntax": "typescript", "decorators": true },
    "transform": { "decoratorVersion": "2022-03" }
  }
}
```

### Playground link (or link to the minimal reproduction)

https://play.swc.rs/?version=1.3.100&code=H4sIAAAAAAAAAyWNwQrCMBAF7%2FsVj55SkILnIngS%2FApJk60uhF1oEiwV%2F920nmeYmauGIqaY%2FOIeJ4Sy9vgQEEyzJR6SPV2XX1ZThFrBxKgaeRbl2B3%2B4GO8qxTxSTZe%2Fo2RvhSSzxk3syN4bYd22XDBuUEi5fcOXU8%2FkPoNpIUAAAA%3D&config=H4sIAAAAAAAAAz2MwQqEMAxE7%2F2KkLOCdG%2F7Id5LjeDCtmWShRXpvxsRvL1h5s0RiPijmd90OHpoCSq4MrHuxdLfmW1vohlbMx6IF8kVySrUO8NPqA%2B3bUhF14rvffAMZ4FutVxXcYpxnF5M3ZUeejgB%2BD%2B8W4QAAAA%3D

### SWC Info output

_No response_

### Expected behavior

addInitializer should be defined on class property decorators as well as .

The same code works on babel and tsc. I thought it was an issue there since the proposal readme says addInitializer does not exist, but apparently the readme is outdated against the actual spec.

### Actual behavior

_No response_

### Version

1.3.104

### Additional context

image

https://github.com/microsoft/TypeScript/issues/57096

### PR DESCRIPTION
**Pull request by phiresky**
**Description:**

At some point the spec text of ES decorators was changed to also have addInitializer for field decorators. This is already used e.g. in mobx. This simple change removes the special case that was present for field decorators and seems to fix the issue for me.

This change is backwards compatible since it only affects code that was broken before.

**Related issue:**

 - Closes #8525

### CODE REVIEW

**Review by kdy1 — COMMENTED** [review]
Please patch https://github.com/swc-project/swc/blob/da0ad79ed344141ececa839aa44dab51b65ed951/crates/swc_ecma_transforms_base/src/helpers/_apply_decs_2203_r.js, too

**Comment by phiresky** [comment]
Ah, I assumed that was auto copied somehow. I modified that file as well.

**Review by kdy1 — APPROVED** [review]
swc-bump:
 - swc_ecma_transforms_base

**Review by kdy1 — CHANGES_REQUESTED** [review]
CI failed. Can you fix it? Possibly by removing some obsolete tests

**Comment by phiresky** [comment]
fixed the test case by now expecting function

**Comment by kdy1** [comment]
CI is still failing

**Review by kdy1 — APPROVED** [review]

**Comment by phiresky** [comment]
sorry, there's so many checks that it looks so green

**Comment by kdy1** [comment]
No worries. I made similar mistakes at the past. 😄 And thank you!

**Pull request merged**
