### PR TITLE
refactor(swc/cli): setup subcommands for the features

### PR DESCRIPTION
**Pull request by kwonoj**
**Description:**

Minor refactor with new empty subcommands we'll support.

**BREAKING CHANGE:**

**Related issue (if exists):**

### CODE REVIEW

**Review by kdy1 — COMMENTED** [review]
I think we have to support linting/minifying css.
How should we support it?

`swc css lint`?
`swc css minify`?

**Comment by kwonoj** [comment]
Since we have existing practices for nested subcommand (plugin)

maybe we can

```
swc minify (css | ecma) ...?
```

**Comment by kdy1** [comment]
Oh, yeah it's possible.

**Review by kdy1 — APPROVED** [review]
swc-bump:
 - swc_cli

**Pull request merged**
