### PR TITLE
Add pure comment when transpiling classes

### PR DESCRIPTION
**Pull request by mischnic**
Closes https://github.com/swc-project/swc/issues/1644

Is this the correct approach? This also requires adding a comments parameter to preset-env, is that a problem?

### CODE REVIEW

**Comment by kdy1** [comment]
Yeah, it's a correct approach I think.

**Comment by mischnic** [comment]
Not sure why so many tests are failing like this...

Bildschirmfoto 2021-05-05 um 20 27 02

**Comment by kdy1** [comment]
Hmm... I'm not sure about the reason, but seems like a sequence expression with a single element is created.

**Comment by mischnic** [comment]
It also seems like `test!` completely ignores comments, otherwise some tests that already contain the pure comment in the expected code would already failed
https://github.com/swc-project/swc/blob/28bb61fb8d2b2ef8940354e7fc2c5c64244ab579/ecmascript/transforms/compat/tests/es2015_classes.rs#L370-L403

I can't quite figure out how to make that happen in the test helpers: [`10bcdce` (#1646)](https://github.com/swc-project/swc/pull/1646/commits/10bcdce633874308e314019a9f03edceb88757db)
```
mismatched types
expected enum `std::option::Option<&dyn Comments>`
   found enum `std::option::Option<Arc<C>>`
```

**Comment by kdy1** [comment]
https://github.com/swc-project/swc/pull/1564/files#diff-9fa4b09c003b4e10b0c37f6c503310cd71dce5869e4d38b4e41e4e28e77ada7fR94-R309

I think this approach can be used for classes, too.

**Comment by kdy1** [comment]
I can take on this if you want.

**Comment by mischnic** [comment]
> I can take on this if you want.

Sure, thanks

**Pull request merged**
