### PR TITLE
feat(swc/cli): setup packages for binary

### PR DESCRIPTION
**Pull request by kwonoj**
**Description:**

This PR attempts to set up initial binary packages for `@swc/cli`. PR **intentionally** does not contain actual implementations yet. Actual implementation will come later once after we get agreement on the migration paths.

1. `@swc/core` v2 

- `swc_cli` will be built as native binary, supports a single subcommand `compile` which current `@swc/cli` supports.
- `@swc/core`'s platform specific optional deps will includes binary to swc_cli for each platform
- `@swc/cli` provides interop to subcommand-less invocation
```
// pseudo 
// `@swc/cli/index.ts

if (args[0] != 'compile') {
  console.warn(`deprecated: v3 will require to invoke cli with subcommand only');
  exec('swc_cli_bin', 'compile', ...args);
}
else {
 exec('swc_cli_bin', ...args);
}
```

2. `@swc/core` v3
- retiring, let `@swc/cli` mark as deprecated 
- `@swc/core` specifics `bin` property in package.json to point native binary directly or have wrapper shell script to do those. Either cases, node.js should not be required to invoke binaries
- all of cli development consolidated into main repo

**Pros**
- full rust binary
- aligned development in single repo
- 0 v8 warmup time: invoking cli becomes very effective, similar to esbuild's cli performs.

**Cons**
- binary size: this effectively increases pkg size as we need to ship additional binary
- compilation time: may increase time to create binary & node bindings

**Related issue (if exists):**
- relates with #1589

### CODE REVIEW

**Review by kdy1 — COMMENTED** [review]
As an alternative native binary, we can add `runCli` to `@swc/core` and use it.
This would result in slower startup, though.

Another alternative is using a shared dynamic library between node bindings and CLI.

**Comment by kwonoj** [comment]
> we can add runCli to @swc/core and use it

That's first thing I was considered, but eventually came to approach native binary instead. If we were to accept node.js being entrypoint to cost warmup time in my opinion it doesn't have a lot of gain we're trying to migrate logics into rust.

> Another alternative is using a shared dynamic library between node bindings and CLI.

This sounds intriguing. What do we need to do exactly?

**Comment by kdy1** [comment]
We should allow compiling the crate `swc` as dylib.

https://github.com/swc-project/swc/blob/25a17e8b115452474f1010e373abac9ed32caa18/crates/swc_common/Cargo.toml#L15-L16

then we can use 
```toml
[build]
rustflags = ["-C", "prefer-dynamic"]
```

But I'm not sure about the way to force `dylib` only for the crate `swc`.

I expect replacing

```toml
[lib]
crate-type = ["lib", "dylib"]
```

with

```toml
[lib]
crate-type = ["dylib"]
```

on ci will work

**Comment by kwonoj** [comment]
Thanks, I'll try few and get back if I'm stuck.

**Comment by kwonoj** [comment]
Marking as draft for now while trying dylib.

**Comment by kwonoj** [comment]
OK, I tried this bit and _looks_ like dylib based binary can be generated at least. 

But while trying, I noticed few things

- As you already noted, there isn't way to have fine-grained control over specific dependencies link type. Once we enable `prefer-dynamic`, All deps gets dynamically linked including any external dependencies.
- This could cause some trouble, first external deps are out of our control so any abi breakage might occur any time. Also, for the distribution we need to pkging several list of files instead of single statically linked binary.

I think it's worth topic to pursue but also this could be considered as `future optimization`. Thoughts on if we do this? @kdy1 

- Accept current approach (separate bin / node bindings with static linked)
- Trying to implement few features actually using swc_common in swc_cli
- See how badly dev workflow affected (CI times, etcs) and think about further
- @swc/cli won't include to use this binary for those time being, so we can safely introduce any breaking changes depends on outcome.

**Comment by kdy1** [comment]
I think it's fine, but I'm not sure about

> Trying to implement few features actually using swc_common in swc_cli

What feature did you mean?

**Comment by kwonoj** [comment]
> What feature did you mean?

Port over what `@swc/cli` does into this binary. Currently this PR is empty and does nothing as you can see already. What I meant was make progress to port over cli logics and see how does it affect to build time & others.

**Comment by kdy1** [comment]
I see. Thank you for the clarification!

**Comment by kwonoj** [comment]
Changed status to ready for review again - once this goes in I'll try to port over `compile` subcommand into this binary crate.

**Review by kdy1 — APPROVED** [review]
Thanks!

**Pull request merged**
