### PR TITLE
Fix: Dead loop parser if parse jsx content as normal js.

### LINKED ISSUE #6961: Dead loop parser if parse jsx content as normal js.
### Describe the bug

The swc parser will dead loop at parser jsx content using js syntax, it should be a print syntax error.

### Input code

```typescript
export default function ViewItemLabel(props) {
            const labelContent = <Text color="dark-gray">1</Text>;
            if (fieldLabelPlacement === 'top') return <Label>{labelContent}</Label>;
            return <Label>{labelContent}</Label>;
          }
```

### Config

_No response_

### Playground link

_No response_

### Expected behavior

Should be print syntax error.

### Actual behavior

Dead loop, the program isn't exit.

### Version

master code

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by IWANABETHATGUY**
**Description:**

**BREAKING CHANGE:**

**Related issue (if exists):**
Fixed https://github.com/swc-project/swc/issues/6961

### CODE REVIEW

**Comment by kdy1** [comment]
Will you work on this?

**Comment by IWANABETHATGUY** [comment]
> **Related issue (if exists):**

Yes, but I guess I would push forward this weekend, feel free to take over it if this issue has high priority.

**Comment by kdy1** [comment]
No worries, it's not a high priority task 😄

**Comment by kdy1** [comment]
Closing as this is fixed by https://github.com/swc-project/swc/issues/7189

**Pull request closed without merging**
