### PR TITLE
feat: add import assertion to dep analyzer

### PR DESCRIPTION
**Pull request by bartlomieju**

### CODE REVIEW

**Review by kdy1 — DISMISSED** [review]
LGTM

**Comment by bartlomieju** [comment]
@kdy1 I'm getting:
```
test tests::test_parsed_module_get_dependencies ... FAILED

failures:

---- tests::test_parsed_module_get_dependencies stdout ----
thread 'tests::test_parsed_module_get_dependencies' panicked at 'encountered error with `-Z treat_err_as_bug', common/src/errors.rs:508:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

There's no failed assertion that I can check, any hints?

**Comment by kdy1** [comment]
@bartlomieju You can change the first parameter of the call to `testing::run_test` to `false`.

https://swc.rs/rustdoc/testing/fn.run_test.html

**Comment by bartlomieju** [comment]
> @bartlomieju You can change the first parameter of the call to `testing::run_test` to `false`.
> 
> https://swc.rs/rustdoc/testing/fn.run_test.html

Thanks, fixed. 

Also one more question; according to proposal exports can also have assertions, but I haven't found them in appropriate AST node (https://github.com/tc39/proposal-import-assertions#re-export-statements)

**Comment by kdy1** [comment]
Oh, I missed the `export` part.
I can do it tomorrow and I'll rebase this pr after doing so.

**Pull request merged**
