### PR TITLE
fix: 🐛 fix https://github.com/swc-project/swc/issues/906

### PR DESCRIPTION
**Pull request by IWANABETHATGUY**

### CODE REVIEW

**Comment by kdy1** [comment]
Thanks for the pr!
But ast nodes are changed and it isn't reflected to typescript types yet.

**Comment by IWANABETHATGUY** [comment]
i change the type defination because the defination is not match with the rust implementation, 
here is my debugging shortcut , you can see runtime ObjectPattern has the **prop** `properties` instead of `props`, 
so i change the `type defination`

**Comment by IWANABETHATGUY** [comment]
image

**Comment by kdy1** [comment]
I meant there are many changes to rust ast, which is not reflected in typescript ast.

**Pull request closed without merging**
