### PR TITLE
fix(trace): filter cranelift, log events

### PR DESCRIPTION
**Pull request by kwonoj**
**Description:**

This PR filters out cranelift and other log records from trace generation. I feel there maybe better, effecient way - but couldn't find it for now. Will try to dig time to time. Also I realized release build doesn't generate any trace due to compile time loglevel flag. PR changes it to runtime level to allow trace to be collected.

**Related issue (if exists):**

- https://github.com/swc-project/swc/issues/3799

### CODE REVIEW

**Comment by kdy1** [comment]
> Also I realized release build doesn't generate any trace due to compile time loglevel flag

Oh, maybe that's the reason performance was not dropped

**Review by kdy1 — DISMISSED** [review]
This seems to have some overhead considering https://github.com/swc-project/swc/runs/5373632744?check_suite_focus=true and https://github.com/swc-project/swc/runs/5373616644?check_suite_focus=true but I think it's small enough.

---

swc-bump:
 - ''

**Comment by kdy1** [comment]
Oh. I found one problem.
The performance of minifier will be greatly affected, because it assumes `release_max_level_info`.

I'll merge this after fixing the minifier.

**Comment by kwonoj** [comment]
@kdy1 Curious if this is still blocked / what to fix if that's the case?

**Comment by kdy1** [comment]
Can you revert `release_max_level_info`?
This requires more investigation, because it breaks an important assumption

**Comment by kwonoj** [comment]
OK, guess need some time to let release build have tracing features.

I'll file separate issue for tracking it.

**Review by kdy1 — DISMISSED** [review]
swc-bump:
 - swc_cli

**Comment by kwonoj** [comment]
ref: https://github.com/swc-project/swc/issues/3863

**Comment by kdy1** [comment]
Oh.. Can you rebase?

**Comment by kwonoj** [comment]
suuuure thing, done.

**Review by kdy1 — APPROVED** [review]

**Comment by kdy1** [comment]
Why did you close this? Is there a better way?

**Comment by kwonoj** [comment]
@kdy1 sorry, I accidentally deleted branch while cleaning up and it caused to cancel automerge. 😭

**Review by kdy1 — APPROVED** [review]

**Comment by kdy1** [comment]
Totally understandable, I did same thing lots of time, because branch list view of `kdy1/swc` does not show active PR numbers

**Pull request merged**
