### PR TITLE
fix(es/parser): Reject invalid `new.target`

### PR DESCRIPTION
**Pull request by g-plane**
**Description:**

`new.target` is only allowed in function declarations, function expressions or classes.

[Babel REPL](https://babel.dev/repl#?browsers=&build=&builtIns=false&corejs=3.6&spec=false&loose=false&code_lz=HYUw7gdALghgTgcxFIA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=&prettier=false&targets=&version=7.17.9&externalPlugins=&assumptions=%7B%7D)

### CODE REVIEW

**Comment by kdy1** [comment]
Seems like there are some test cases which is rejected after this PR?

**Comment by g-plane** [comment]
It should work now, some tests failed to install dependencies.

**Comment by g-plane** [comment]
@kdy1 Can you review this?

**Review by kdy1 — APPROVED** [review]
Thank you!

---

swc-bump:
 - swc_ecma_parser

**Review by kdy1 — APPROVED** [review]

**Pull request merged**
