### PR TITLE
feat(es/minifier): Improve invokation of IIFEs

### PR DESCRIPTION
**Pull request by kdy1**
**Description:**

**Related issue (if exists):**

 - https://github.com/swc-project/swc/issues/5559

### CODE REVIEW

**Comment by Austaras** [comment]
This seems have too much edge case to consider, e.g.
```js
var x = 1
function foo(a) {
  console.log(!!a)
  a = 10
}

foo(x)
```

**Comment by kdy1** [comment]
@Austaras Do you have any idea about the way to implement this optimization?

**Comment by Austaras** [comment]
> @Austaras Do you have any idea about the way to implement this optimization?

In your example, terser simply refuses to inline that function call

**Comment by kdy1** [comment]
Oh lol you are right

**Comment by Austaras** [comment]
#5365 is not enough because at the time of inline, function args could be some very complex expression, but later they could be turned into literal. So in the end we still need to be able to compress
```js
var a
a = 10
console.log(a)
```

**Comment by kdy1** [comment]
Closing as this seems this seems like a too risky optimization

**Comment by kdy1** [comment]
I updated the tasklist issue

**Pull request closed without merging**
