### PR TITLE
feat(es/minifier): Update `defaults`

### PR DESCRIPTION
**Pull request by kdy1**
**Description:**

**Related issue (if exists):**

 - https://github.com/swc-project/swc/issues/2934#issuecomment-1094186669

### CODE REVIEW

**Comment by kdy1** [comment]
cc @Austaras Seems like terser tests are still passing.

image

**Comment by kdy1** [comment]
Oh there was some regressions

**Review by kdy1 — COMMENTED** [review]
swc-bump:
 - swc_ecma_minifier --breaking

**Comment by Austaras** [comment]
Do `crates/swc_ecma_minifier/src/option/mod.rs` need update too?

**Comment by kdy1** [comment]
Oh I think so, thanks!

**Comment by kdy1** [comment]
I think we should enable rules on by one. (Because of bugs)
Closing, and I updated https://github.com/swc-project/swc/issues/2934

**Pull request closed without merging**
