### PR TITLE
build(cargo): dedupe swc_common

### PR DESCRIPTION
**Pull request by kwonoj**
**Description:**

This PR bumps up swc_plugin_comments (https://github.com/swc-project/swc/compare/main...kwonoj:dedupe-common?expand=1#diff-3e6e03a99597d39766266450bfe5b476c2988cd9fbbad61850e1dca516ca7f75R8) to get latest changes published to crates.io, also aligns version to swc_common to dedupe as much.

**BREAKING CHANGE:**

**Related issue (if exists):**

### CODE REVIEW

**Comment by kwonoj** [comment]
Guess needs to publish new version for swc_plugin?

**Review by kdy1 — APPROVED** [review]
Thanks

---

swc-bump:
 - swc_plugin_comments

**Comment by kwonoj** [comment]
@kdy1 is it possible to bump `swc_plugin` itself? There's some transitive dep version need to be bumped altogether with swc_plugin.

**Comment by kdy1** [comment]
Of course, did it

**Comment by kwonoj** [comment]
Great, Thanks! 🙇

**Pull request merged**
