### PR TITLE
feat(swc): coerce fallback bindings async interface to sync

### PR DESCRIPTION
**Pull request by kwonoj**
**Description:**

Similar to https://github.com/vercel/next.js/pull/38780, coerce async interface of bindings to sync for the fallback binding (wasm) to make most of code works seamlessly. There are some non existent interfaces (like bundle) we can't support still.

**BREAKING CHANGE:**

**Related issue (if exists):**

### CODE REVIEW

**Comment by kwonoj** [comment]
CI failure seems interesting, not related to PR's change?

**Comment by kdy1** [comment]
Oh... You are right I think?

**Comment by kwonoj** [comment]
Yes, PR doesn't contain any rust code changes. 


```
error[E0277]: `RefCell<bool>` cannot be shared between threads safely
   --> crates/swc_ecma_transforms_optimization/src/json_parse.rs:57:1
    |
57  | #[parallel]
    | ^^^^^^^^^^^
    | |
    | `RefCell<bool>` cannot be shared between threads safely
    | within this `[closure@crates/swc_ecma_transforms_optimization/src/json_parse.rs:57:1: 57:12]`
    |
    = help: within `[closure@crates/swc_ecma_transforms_optimization/src/json_parse.rs:57:1: 57:12]`, the trait `std::marker::Sync` is not implemented for `RefCell<bool>`
    = note: required because it appears within the type `Lock<bool>`
    = note: required because it appears within the type `LockCell<bool>`
    = note: required because it appears within the type `swc_common::errors::Handler`
    = note: required because it appears within the type `&swc_common::errors::Handler`
    = note: required because it appears within the type `[closure@crates/swc_ecma_transforms_optimization/src/json_parse.rs:57:1: 57:12]`
note: required by a bound in `rayon::iter::ParallelIterator::map`
   --> /home/runner/.cargo/registry/src/github.com-1ecc6[299](https://github.com/swc-project/swc/runs/7402187983?check_suite_focus=true#step:18:300)db9ec823/rayon-1.5.2/src/iter/mod.rs:586:34
    |
586 |         F: Fn(Self::Item) -> R + Sync + Send,
    |                                  ^^^^ required by this bound in `rayon::iter::ParallelIterator::map`
    = note: this error originates in the attribute macro `parallel` (in Nightly builds, run with -Z macro-backtrace for more info)
```

Not sure where it comes from.

**Review by kdy1 — APPROVED** [review]
Thanks!

---

swc-bump:
 - ''

**Pull request merged**
