### PR TITLE
fix(css/parser): fix `supports()` parsing

### PR DESCRIPTION
**Pull request by alexander-akait**
**Description:**

`supports()` can be empty + tests

**BREAKING CHANGE:**

No

**Related issue (if exists):**

No

### CODE REVIEW

**Review by kdy1 — APPROVED** [review]
swc-bump:
 - swc_css_ast

**Comment by alexander-akait** [comment]
Need more work, found more bugs, will fix in near future

**Review by kdy1 — CHANGES_REQUESTED** [review]
CI failed

**Comment by alexander-akait** [comment]
@kdy1 Ready to review

**Comment by kdy1** [comment]
Seems like ci is still failing?

**Comment by alexander-akait** [comment]
@kdy1 Shoudl be fixed, my fail

**Review by kdy1 — APPROVED** [review]

**Pull request merged**
