### PR TITLE
fix(trace): adjust tracing span level

### PR DESCRIPTION
**Pull request by kwonoj**
**Description:**

- closes https://github.com/swc-project/swc/issues/3863.

I tried various approach to preserve compile time trace level but only enable Level::TRACE for `span` only. However, it simply not seems possible. The reason I choose trace level at the moment is I was under assumption it's the only level tracing spans will try to use and would possible to enable it selectively. Both seems incorrect - first, trace level can be used for logging any span-less event, or other places. Secondly, as said above we can't opt in to enable span's trace level.

PR changes span's level into `info`. This is not a regression or defeating back: https://tracing.rs/tracing_attributes/attr.instrument.html# If we didn't choose level intentionally it would been `info` all the time and we won't hit this problem from beginning.

> instruments a function to create and enter a tracing [span](https://docs.rs/tracing/latest/tracing/span/index.html) every time the function is called.
> Unless overriden, a span with info level will be generated.

WIth this PR, only tracing `spans` will be recorded as info. Any other traces, logs, or events can use TRACE | DEBUG level and `@swc/core` release binary will not emit those at all.

**BREAKING CHANGE:**

**Related issue (if exists):**

### CODE REVIEW

**Comment by kdy1** [comment]
I profiled it locally.

PR:
```
test full_es2015                  ... bench:  80,136,808 ns/iter (+/- 7,580,107)
test full_es2016                  ... bench:  85,148,904 ns/iter (+/- 30,743,348)
test full_es2017                  ... bench:  87,605,962 ns/iter (+/- 16,405,189)
test full_es2018                  ... bench:  84,212,345 ns/iter (+/- 13,840,869)
test full_es2019                  ... bench:  85,074,516 ns/iter (+/- 12,216,482)
test full_es2020                  ... bench:  80,233,583 ns/iter (+/- 14,899,070)
test full_es3                     ... bench: 111,405,208 ns/iter (+/- 10,115,031)
test full_es5                     ... bench: 103,204,875 ns/iter (+/- 9,714,975)
test parser                       ... bench:     246,809 ns/iter (+/- 8,527)
```

Main:
```
test full_es2015                  ... bench:  62,123,141 ns/iter (+/- 5,155,507)
test full_es2016                  ... bench:  61,233,145 ns/iter (+/- 6,222,669)
test full_es2017                  ... bench:  61,224,904 ns/iter (+/- 6,650,323)
test full_es2018                  ... bench:  60,357,304 ns/iter (+/- 4,089,180)
test full_es2019                  ... bench:  60,029,079 ns/iter (+/- 4,770,494)
test full_es2020                  ... bench:  57,809,924 ns/iter (+/- 4,155,606)
test full_es3                     ... bench:  81,534,441 ns/iter (+/- 4,828,373)
test full_es5                     ... bench:  76,303,150 ns/iter (+/- 4,709,092)
test parser                       ... bench:     246,544 ns/iter (+/- 3,130)
```

So it makes swc 15%~20% slower.

**Comment by kwonoj** [comment]
What do you think? Go vs no-go?

Personally, I think it's acceptable as likely we'll optimize / remove unnecessary spans by improving this. Currently we eagerly expands across every transform visitor, but based on real codebase observation we can cut some obvious paths. 

It'll still add overheads to runtime always, tradeoff to giving user level profiling features to end users.

**Comment by kdy1** [comment]
But I think it's too much to go with. Maybe we can use `swcx` binary for profiling instead

**Comment by kwonoj** [comment]
In current number I agree it's somewhat lot. My expectation is we can reduce those number by optimizing spans.

Not supporting trace in `@swc/core` means all of programattic access cannot profile, like `swc-loader` or jest or anything else.

**Comment by kwonoj** [comment]
I got curious about numbers, so ran it locally:

Main
```
test full_es2015                  ... bench: 222,920,918 ns/iter (+/- 8,316,859)
test full_es2016                  ... bench: 222,653,579 ns/iter (+/- 6,525,643)
test full_es2017                  ... bench: 225,245,446 ns/iter (+/- 7,668,584)
test full_es2018                  ... bench: 220,806,417 ns/iter (+/- 6,522,804)
test full_es2019                  ... bench: 223,732,250 ns/iter (+/- 11,723,803)
test full_es2020                  ... bench: 140,139,454 ns/iter (+/- 5,810,154)
test full_es3                     ... bench: 252,597,317 ns/iter (+/- 12,477,837)
test full_es5                     ... bench: 246,717,748 ns/iter (+/- 11,739,469)
test parser                       ... bench:     419,726 ns/iter (+/- 26,972)
```

PR
```
test full_es2015                  ... bench: 220,594,474 ns/iter (+/- 5,399,636)
test full_es2016                  ... bench: 220,703,386 ns/iter (+/- 11,409,377)
test full_es2017                  ... bench: 220,279,684 ns/iter (+/- 7,768,127)
test full_es2018                  ... bench: 219,599,446 ns/iter (+/- 13,968,280)
test full_es2019                  ... bench: 217,291,666 ns/iter (+/- 9,412,638)
test full_es2020                  ... bench: 134,070,813 ns/iter (+/- 4,670,114)
test full_es3                     ... bench: 250,844,650 ns/iter (+/- 7,959,047)
test full_es5                     ... bench: 244,216,406 ns/iter (+/- 7,729,769)
test parser                       ... bench:     415,734 ns/iter (+/- 20,809)
```

For both of cases, cpu utilization doesn't go over 20~25% in general. I'm curious how does benchmark intenrally works and if we could have some deterministic numbers. 

For optimization side, along with my above suggestion to optimize span itself, the part I'm hoping to get is  upstream support for sampling (https://github.com/tokio-rs/tracing/discussions/1474#discussioncomment-1022805) . I believe having both will allow reasonable overhead to runtime

**Comment by kdy1** [comment]
For cpu core, `cargo bench` intentionally uses only one cpu core, so it can't go high

**Comment by kwonoj** [comment]
Rebased to use latest `tracing`, may need to run numbers again to see if it gives suffecient gains for us.

**Comment by kdy1** [comment]
Seems like it's quite better.

First run:

```

test full_es2015                  ... bench:  61,109,499 ns/iter (+/- 2,305,026)
test full_es2016                  ... bench:  60,443,100 ns/iter (+/- 2,172,061)
test full_es2017                  ... bench:  60,217,412 ns/iter (+/- 5,933,569)
test full_es2018                  ... bench:  59,623,216 ns/iter (+/- 2,349,659)
test full_es2019                  ... bench:  59,241,583 ns/iter (+/- 2,840,240)
test full_es2020                  ... bench:  57,035,162 ns/iter (+/- 2,649,858)
test full_es3                     ... bench:  80,850,679 ns/iter (+/- 2,534,178)
test full_es5                     ... bench:  77,287,612 ns/iter (+/- 7,292,843)
test parser                       ... bench:     245,276 ns/iter (+/- 3,550)
```

Second run:

```
test full_es2015                  ... bench:  61,017,462 ns/iter (+/- 3,549,847)
test full_es2016                  ... bench:  60,511,858 ns/iter (+/- 2,967,864)
test full_es2017                  ... bench:  60,331,804 ns/iter (+/- 6,185,472)
test full_es2018                  ... bench:  59,419,608 ns/iter (+/- 4,134,257)
test full_es2019                  ... bench:  59,293,133 ns/iter (+/- 2,414,775)
test full_es2020                  ... bench:  56,766,325 ns/iter (+/- 3,164,065)
test full_es3                     ... bench:  80,697,641 ns/iter (+/- 2,591,066)
test full_es5                     ... bench:  75,963,858 ns/iter (+/- 4,211,157)
test parser                       ... bench:     246,035 ns/iter (+/- 12,311)
```


I'll rebase this PR to compare with the main branch.

**Comment by kwonoj** [comment]
@kdy1 anything left to resolve in here?

**Review by kdy1 — APPROVED** [review]
swc-bump:
 - swc_trace_macro

**Pull request merged**
