### PR TITLE
fix(es/compat): handle string literial spread

### LINKED ISSUE #4190: Spread Operator Failed to be Converted
### Describe the bug

The spread operator in the function parameter cannot be converted to Es5 code format.

### Input code

```typescript
v3 = String.raw({ raw: 'abcd' }, ...'___');
console.log(v3);
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "ecmascript",
      "jsx": false,
      "dynamicImport": false,
      "privateMethod": false,
      "functionBind": false,
      "exportDefaultFrom": false,
      "exportNamespaceFrom": false,
      "decorators": false,
      "decoratorsBeforeExport": false,
      "topLevelAwait": false,
      "importMeta": false
    },
    "transform": null,
    "target": "es5",
    "loose": false,
    "externalHelpers": false
  },
  "module": {
    "type": "commonjs",
    "strict": false,
    "strictMode": false,
    "lazy": false,
    "noInterop": false
  }
}
```

### Playground link

https://play.swc.rs/?version=1.2.161&code=H4sIAAAAAAAAAyszVrBVCC4pysxL1ytKLNeoVgCSVgrqiUnJKeoKtToKenp66vHx8eqa1lzJ%2BXnF%2BTmpejn56RplxprWAIqBgjk8AAAA&config=H4sIAAAAAAAAA0WNwQ6DQAhE%2F4Wz1178gvbgR5AtNmtY2AAmWuO%2Fd01tPcFMZt5sMHmCfoOK5mTH56sELtADpYKeLNeArsWaNSI77R2EofioVqCXmbkZaC%2BKo%2BO3FmZVpzPeAS1BJsh34krmF6boc2Y6NmOt7ULSUlQmbwgPyyn%2BjK8c9HlhGd%2FrX4g%2BpK1ovejZh5N%2FZkqWPP4q%2Bwfiymdk%2BgAAAA%3D%3D

### Expected behavior

The spread operator can be converted to ES5 code format.

### Actual behavior

_No response_

### Version

1.2.161

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by magic-akari**
**Description:**

**BREAKING CHANGE:**

**Related issue (if exists):**
- fix #4190

### CODE REVIEW

**Review by kdy1 — APPROVED** [review]
Thank you!

---

swc-bump:
 - swc_ecma_transforms_compat

**Review by kdy1 — APPROVED** [review]

**Comment by magic-akari** [comment]
I have found some regressions in this PR, please wait for me to fix them.

**Comment by kdy1** [comment]
Oh, thanks!

**Comment by magic-akari** [comment]
Nothing to fix. 
I thought I had broken the `objectSpread`, but then found out that it had not been introduced into the test.

**Pull request merged**
