### PR TITLE
test(swc/wasm): add test cases for minify

### PR DESCRIPTION
**Pull request by kwonoj**
**Description:**

- relates to https://github.com/swc-project/swc/issues/5275

PR adds simple test cases for the wasm, as we are moving towards to make @swc/wasm as first class citizen. This PR actually fails since newly added test case not able to pass.

**BREAKING CHANGE:**

**Related issue (if exists):**

### CODE REVIEW

**Comment by kwonoj** [comment]
Interesting thing is it shows different failure than original issue.

```
   RangeError: Maximum call stack size exceeded

      at swc_ecma_parser::lexer::state::<impl core::iter::traits::iterator::Iterator for swc_ecma_parser::lexer::Lexer<I>>::next::{{closure}}::h33d6f7aea7ae9423 (wasm:/wasm/17487d42:1:9174010)
      at swc_ecma_parser::lexer::state::<impl core::iter::traits::iterator::Iterator for swc_ecma_parser::lexer::Lexer<I>>::next::h07de51b652b79274 (wasm:/wasm/17487d42:1:18208348)
      at swc_ecma_parser::parser::input::Buffer<I>::bump_inner::{{closure}}::h947975deb7378d5c (wasm:/wasm/17487d42:1:67380653)
      at core::option::Option<T>::or_else::hb735b09add21ca84 (wasm:/wasm/17487d42:1:30757873)
      at swc_ecma_parser::parser::input::Buffer<I>::bump_inner::h4372a3cb4430fd0b (wasm:/wasm/17487d42:1:28925442)
      at swc_ecma_parser::parser::input::Buffer<I>::cur::h39d003bfad042fa1 (wasm:/wasm/17487d42:1:52676026)
      at swc_ecma_parser::parser::expr::<impl swc_ecma_parser::parser::Parser<I>>::parse_subscript::h6df51f4270d7254d (wasm:/wasm/17487d42:1:1043749)
      at swc_ecma_parser::parser::expr::<impl swc_ecma_parser::parser::Parser<I>>::parse_subscripts::h79f99ead3e8e0bd6 (wasm:/wasm/17487d42:1:35258862)

```

**Comment by kdy1** [comment]
Oh?
Interesting..

**Comment by kwonoj** [comment]
I don't have good explanations. Fyi, @swc/core works fine.

**Comment by kwonoj** [comment]
@kdy1 one more: weirdly, this seems only happening on the debug build. 🤔

**Comment by kdy1** [comment]
Closing as stale

**Pull request closed without merging**
