### PR TITLE
chore: Publish `v1.3.45` with `swc_core` `v0.74.0`

### PR DESCRIPTION
**Pull request by kdy1**

### CODE REVIEW

**Review by kdy1 — COMMENTED** [review]
swc-bump:
 - dbg-swc

**Comment by kdy1** [comment]
I published it

**Comment by kdy1** [comment]
https://github.com/swc-project/swc/commit/b7d9fc5535876a97d43fbaf7c3147fe819942161

**Comment by maruware** [comment]
The following error occured.

> npm ERR! notarget No matching version found for @swc/helpers@>0.4.14 <0.5.

`<=0.5` is correct?

**Comment by magic-akari** [comment]
> The following error occured.
> 
> > npm ERR! notarget No matching version found for @swc/helpers@>0.4.14 <0.5.
> 
> `<=0.5` is correct?

Yes, the peerDependencies should be `^0.5.0`.
@kdy1

**Comment by magic-akari** [comment]
It's recomended to deprecte `@swc/core@1.3.45` and republish `@swc/core@1.3.46` with peerDependencies `@swc/helpers@^0.5.0`

**Pull request merged**
