### PR TITLE
[typescript] 4.1 mapped type 'as' clause

### PR DESCRIPTION
**Pull request by g-plane**
Syntax:

```ts
let map: { [P in string as string]: number };
```

### CODE REVIEW

**Comment by kdy1** [comment]
@g-plane Are you still willing to work on the pr? If not, I'll implement ts 4.1 support.

**Comment by g-plane** [comment]
Yes. Can you review this PR?

**Comment by kdy1** [comment]
Changes look good to me, but test is failing.

**Comment by g-plane** [comment]
Let me rebase.

**Comment by g-plane** [comment]
How can I fix the tests? I can't find those files whose tests are failed.

**Comment by kdy1** [comment]
Those tests are hidden to reduce crate size.
Actaully, it lives at https://github.com/swc-project/ts-parser-test-ref

I'll make it submodule in future (if I have time).

For now, I'll update them and re-run the tests.

**Review by kdy1 — APPROVED** [review]
Thanks a lot!

**Pull request merged**
