### PR TITLE
feat(swc/core): provide build-time metadata diagnostics

### PR DESCRIPTION
**Pull request by kwonoj**
**Description:**

Recent debugging experiences made me feel it'd be easier to have some metadata we can ask in runtime to figure out `what exact code we are running?` Especially this'll be valuable when we try to diagnose host-guest mismatches.

PR introduces build time metadata. previously we have one for the pkg version but it was mostly utility for the cli bootstrap. Newly introduced metadata includes pkg version, as well as some meaningful information like git sha + cargo features enabled at the build time to ensure we're running the codes we want.

Once this goes in, all of bindings (node, wasm, cli) can adapt this to display / or expose interfaces. Previous target triple, or pkg constant will be consolidated into this. 

Vergen have lot more useful variable (https://docs.rs/vergen/latest/vergen/#environment-variables) we can add more if we need.

**BREAKING CHANGE:**

**Related issue (if exists):**

### CODE REVIEW

**Comment by kwonoj** [comment]
With current PR, we'll get output like this (building swc_core for the plugin)

```
CoreEngineDiagnostics {
    build_semver: "0.7.12",
    git_branch: "main",
    git_sha: "5efac7237c02d8d37e9bb7ce2c2417df1111eecb",
    cargo_features: "ast,once_cell,plugin_transform,quote,swc_atoms,swc_common,swc_ecma_ast,swc_ecma_quote_macros,swc_ecma_transforms_testing,swc_ecma_visit,swc_plugin,swc_plugin_macro,swc_plugin_proxy,visit,__common,__plugin_transform,__plugin_transform_schema_v1,__testing_transform",
    cargo_target_triple: "wasm32-wasi",
}
```

**Review by kdy1 — APPROVED** [review]
Thanks!

---

swc-bump:
 - swc_core

**Comment by kwonoj** [comment]
Looks like there was a lockfile conflict, rebased to resolve.

**Review by kdy1 — APPROVED** [review]

**Comment by magic-akari** [comment]
How to configure vergen?
I have run into an error while publishing a plugin.
Is there a step I'm missing?

```
Compiling swc_core v0.7.13
[239](https://github.com/magic-akari/jest_workaround/runs/7836272382?check_suite_focus=true#step:10:240)
error: failed to run custom build command for `swc_core v0.7.13`
[240](https://github.com/magic-akari/jest_workaround/runs/7836272382?check_suite_focus=true#step:10:241)

[241](https://github.com/magic-akari/jest_workaround/runs/7836272382?check_suite_focus=true#step:10:242)
Caused by:
[242](https://github.com/magic-akari/jest_workaround/runs/7836272382?check_suite_focus=true#step:10:243)
  process didn't exit successfully: `/home/runner/work/jest_workaround/jest_workaround/target/package/jest_workaround-0.1.7/target/debug/build/swc_core-7361547c5c0aeb0d/build-script-build` (exit status: 101)
[243](https://github.com/magic-akari/jest_workaround/runs/7836272382?check_suite_focus=true#step:10:244)
  --- stderr
[244](https://github.com/magic-akari/jest_workaround/runs/7836272382?check_suite_focus=true#step:10:245)
  thread 'main' panicked at 'Build time metadata should be available: could not find repository from '/home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/swc_core-0.7.13'; class=Repository (6); code=NotFound (-3)', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/swc_core-0.7.13/build.rs:27:31
[245](https://github.com/magic-akari/jest_workaround/runs/7836272382?check_suite_focus=true#step:10:246)
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[246](https://github.com/magic-akari/jest_workaround/runs/7836272382?check_suite_focus=true#step:10:247)
error: failed to verify package tarball
[247](https://github.com/magic-akari/jest_workaround/runs/7836272382?check_suite_focus=true#step:10:248)
Error: Process completed with exit code 101.
```

https://github.com/magic-akari/jest_workaround/runs/7836272382?check_suite_focus=true

**Comment by kdy1** [comment]
@magic-akari Although it's an uneducated guess, you may need to checkout the git repository with git history (i.e. `fetch-depth: 0`)

**Comment by magic-akari** [comment]
I ran the `cargo publish` command locally and got the same error.

**Comment by magic-akari** [comment]
> @magic-akari Although it's an uneducated guess, you may need to checkout the git repository with git history (i.e. `fetch-depth: 0`)

Do you mean that I should only have only 1 depth git history locally?

**Comment by kdy1** [comment]
No, it's a wrong guess if local publish failed

**Comment by kwonoj** [comment]
It could be my mistake. I'll try repro to see if this happens on my end.

**Comment by kwonoj** [comment]
@kdy1 @magic-akari https://github.com/swc-project/swc/pull/5501 - it is my mistake indeed. For now, simply reverting it.

**Pull request merged**
