### PR TITLE
style: fix various spelling errors

### PR DESCRIPTION
**Pull request by sisp**
Just a small fix of various spelling errors or improvements in spelling.

### CODE REVIEW

**Comment by kdy1** [comment]
Sorry but I don't think this is required.

**Comment by sisp** [comment]
Not required in the sense of correctness of the software or its usability - yes. But among many other things, proper spelling adds to the quality of a project and its perception by developers as a high-quality project. I don't insist on these changes, but I'm slightly puzzled why this perfectly valid PR is rejected. :thinking:

**Comment by kdy1** [comment]
Because I don't think javascript vs JavaScript is an important difference. Actually I'm more familiar with the former.

**Comment by sisp** [comment]
Well, that's how the "authorities" spell them, e.g.:
- JavaScript: https://nodejs.org, https://developer.mozilla.org/en-US/docs/Web/javascript, ...
- TypeScript: https://www.typescriptlang.org
- Babel: https://babeljs.io

It's not like I'm making it up.

**Pull request closed without merging**
