### PR TITLE
refactor(bindings/wasm): deprecate jsvalue::*_serde

### PR DESCRIPTION
**Pull request by kwonoj**
**Description:**

Second attempts to https://github.com/swc-project/swc/pull/6436, with various fixes to ensure things are not breaking.

PR also adds naive testing to swc_core to test with latest workspace root to build. This allows to catch problems upfront before publish swc_core (not @swc/core). It actually caught various failures while I'm working on this PR.

Also, PR updates `bindings_macro` to reflect latest changes.

**BREAKING CHANGE:**

**Related issue (if exists):**

### CODE REVIEW

**Review by kdy1 — APPROVED** [review]
swc-bump:
 - binding_macros

**Review by kdy1 — CHANGES_REQUESTED** [review]
There's a merge conflict

**Comment by kwonoj** [comment]
Thanks, looks like rebased on passes ci now.

**Review by kdy1 — APPROVED** [review]

**Comment by kwonoj** [comment]
I recall I resolved conflicts.. 🤔 anyway, re-rebased.

**Review by kdy1 — APPROVED** [review]

**Pull request merged**
