### PR TITLE
feat(es/typescript): Support `deferred` modifier

### PR DESCRIPTION
**Pull request by magic-akari**
**Related issue (if exists):**

- https://github.com/microsoft/TypeScript/pull/58729

### CODE REVIEW

**Comment by magic-akari** [comment]
https://github.com/swc-project/swc/blob/bd2509bafa35baa52db10385f0aae720768e5538/crates/swc_ecma_ast/src/function.rs#L15-L17

I need to update the type of params from `Vec<Param>` to `Vec<ParamOrTsParamProp>`, which will cause a lot of changes.

**Comment by kdy1** [comment]
Merging the two types sounds good to me

**Comment by magic-akari** [comment]
I have observed that Babel also distinctly differentiates between `TSParameterProperty` and `Pattern`.
It might be necessary to communicate with Babel to explore better implementation methods.

**Comment by magic-akari** [comment]
TypeScript has adopted the `immediate` keyword. Moreover, we should await the completion of #9313.

**Pull request closed without merging**
