### PR TITLE
feat(es/minifier): Drop variable from the sequential inliner

### PR DESCRIPTION
**Pull request by kdy1**
**Description:**

We now drop variable declarations if we are going to eliminate the only usage.

**Related issue:**

 - Closes https://github.com/swc-project/swc/issues/5693

### CODE REVIEW

**Review by kdy1 — COMMENTED** [review]
swc-bump:
 - swc_ecma_minifier

**Comment by kdy1** [comment]
cc @Austaras Can you take a look?

**Comment by Austaras** [comment]
Seems pretty good, but maybe this should be under flag of `unused`. Terser code is really cryptic

**Comment by kdy1** [comment]
Thank you!
I forgot checking the options 😄

**Comment by Austaras** [comment]
Chnage to golden.txt can be reverted now.

**Comment by kdy1** [comment]
Is reverting required? It's generally good to have more entries in `golden.txt` as we enable test for it. Are you worried about something?

**Comment by Austaras** [comment]
Oh, I mistake it for ignore list.

**Comment by kdy1** [comment]
I renamed it to `passing.txt`

**Pull request merged**
