### PR TITLE
fix(swc): Fix bugs

### LINKED ISSUE #1704: Optional chaining is transpiled for ios 13.4
**Describe the bug**

```rust
                swc_ecma_preset_env::Config {
                    targets: Some(Targets::Versions(BrowserData {
                        ios: Some(Version::from_str("13.4").unwrap()),
                        ..Default::default()
                    })),
                    ..Default::default()
                },
```

transpiles optional chaining, even though iOS Safari 13.4 supports it.

**Input code**

```java
document?.querySelector?.(".xyz")?.remove?.();
```

**Current output**

```java
var ref, ref1, ref2;
document === null || document === void 0 ? void 0 : (ref = document.querySelector) === null || ref === void 0 ? void 0 : (ref1 = ref.call(document, ".lol")) === null || ref1 === void 0 ? void 0 : (ref2 = ref1.remove) === null || ref2 === void 0 ? void 0 : ref2.call(ref1);
```

**Config**

<details>
<summary>Example</summary>

```rust
use std::{path::PathBuf, str::FromStr};

use swc_common::comments::SingleThreadedComments;
use swc_common::{chain, sync::Lrc, FileName, Globals, Mark, SourceMap};
use swc_ecma_preset_env::{preset_env, BrowserData, Query, Targets, Version};
use swc_ecmascript::codegen::text_writer::JsWriter;
use swc_ecmascript::codegen::{Config, Emitter};
use swc_ecmascript::parser::lexer::Lexer;
use swc_ecmascript::parser::{EsConfig, PResult, Parser, StringInput, Syntax};
use swc_ecmascript::transforms::{
    compat::reserved_words::reserved_words, fixer, helpers, hygiene,
    optimization::simplify::expr_simplifier, react, resolver::resolver_with_mark,
};
use swc_ecmascript::visit::FoldWith;
use swc_ecmascript::{ast::Module, parser::TsConfig};

fn main() {
    let cm = Lrc::<SourceMap>::default();
    let src = r#"
document?.querySelector?.(".lol")?.remove?.();
"#;
    let (module, comments) = parse(src, "test.js", &cm).unwrap();

    swc_common::GLOBALS.set(&Globals::new(), || {
        helpers::HELPERS.set(&helpers::Helpers::default(), || {
            let global_mark = Mark::fresh(Mark::root());
            let module = module.fold_with(&mut resolver_with_mark(global_mark));

            // let transform = &mut expr_simplifier();
            // let module = module.fold_with(transform);
            let transform = &mut preset_env(
                global_mark,
                Some(&comments),
                swc_ecma_preset_env::Config {
                    targets: Some(Targets::Versions(BrowserData {
                        ios: Some(Version::from_str("13.4").unwrap()),
                        ..Default::default()
                    })),
                    ..Default::default()
                },
            );
            let module = module.fold_with(transform);

            let module = module.fold_with(&mut chain!(
                helpers::inject_helpers(),
                reserved_words(),
                hygiene(),
                fixer(Some(&comments))
            ));

            let code = emit(&module, &comments, cm);
            println!("{}", code);
        });
    });
}

fn parse(
    code: &str,
    filename: &str,
    cm: &Lrc<SourceMap>,
) -> PResult<(Module, SingleThreadedComments)> {
    let source_file = cm.new_source_file(FileName::Real(filename.into()), code.into());
    let comments = SingleThreadedComments::default();

    let lexer = Lexer::new(
        Syntax::Es(EsConfig {
            jsx: true,
            ..Default::default()
        }),
        // Syntax::Typescript(TsConfig {
        //     ..Default::default()
        // }),
        Default::default(),
        StringInput::from(&*source_file),
        Some(&comments),
    );
    let mut parser = Parser::new_from(lexer);
    match parser.parse_module() {
        Err(err) => Err(err),
        Ok(module) => Ok((module, comments)),
    }
}

fn emit(module: &Module, comments: &SingleThreadedComments, cm: Lrc<SourceMap>) -> String {
    let mut buf = vec![];
    {
        let writer = Box::new(JsWriter::new(cm.clone(), "\n", &mut buf, None));
        let config = Config { minify: false };
        let mut emitter = Emitter {
            cfg: config,
            comments: Some(&comments),
            cm,
            wr: writer,
        };
        emitter.emit_module(&module).unwrap();
    }

    String::from_utf8(buf).unwrap()
}
```

</details>

**Expected behavior**

It should keep the optional chaning: https://babeljs.io/repl#?browsers=ios%2013.4&build=&builtIns=false&corejs=3.6&spec=false&loose=false&code_lz=CYewxgrgtgpgdgFwPwDoCOEYCcCeBlGAGxjARC1QAoAiFQkQ6gSlSxihADcYqmBuIA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env&prettier=false&targets=&version=7.14.2&externalPlugins=

**Version**
```toml
name = "swc_ecma_preset_env"
version = "0.20.0"
```

### LINKED ISSUE #1711: Calls to private methods rely on `this` being the instance object
**Describe the bug**

When transpiled, calls to private methods rely on `this` being the instance object, which doesn't have to be the case.

(It works correctly if `#value` is a field and not a method.)

**Input code**

```js
class Foo {
	#value() {
		return 1;
	}
	// #value = 1;

	get(target) {
		return target.#value;
	}
}

let foo = new Foo();
let getter = foo.get;
console.log(getter(foo));
```

**Current behaviour**

```js
function _classPrivateMethodGet(receiver, privateSet, fn) {
    if (!privateSet.has(receiver)) {
        throw new TypeError("attempted to get private field on non-instance");
    }
    return fn;
}
var _value = new WeakSet();
class Foo {
    // #value = 1;
    get(target) {
        return _classPrivateMethodGet(this, _value, value);
    }
    constructor(){
        _value.add(this);
    }
}
function value() {
    return 1;
}
let foo = new Foo();
let getter = foo.get;
console.log(getter(foo));
```

**Expected behavior**
It seems like it doesn't matter what `XYZ` is in this method
```js
	get(target) {
		return XYZ.#value;
	}
```
, it always gets transpiled to 
```js
    get(target) {
        return _classPrivateMethodGet(this, _value, value);
    }
```
if `#value` is a class method. Maybe `XYZ` should be passed instead of `this`?

**Version**
latest version of the crates

**Additional context**
https://github.com/parcel-bundler/parcel/issues/6305

cc @danieltroger

### PR DESCRIPTION
**Pull request by kdy1**
swc_ecma_preset_env:
 - [x] Update compat data. (Close #1704)
 - [x] Support `export-namespace-from`.

swc_ecma_transforms_compat:
 - [x] Use proper argument for private field accesses in a private method. (Closes #1711)

### CODE REVIEW

**Comment by zloirock** [comment]
It seems you used obsolete `core-js-compat` in this PR.

**Comment by kdy1** [comment]
@zloirock Do you mean https://github.com/babel/babel/tree/main/packages/babel-compat-data is outdated?
If I remember correctly, I copied from the babel package.

**Comment by kdy1** [comment]
Ah, I installed `core-js-compat` locally and I'll update compat data with a new PR. Thanks a lot!

**Comment by zloirock** [comment]
`babel-compat-data` is not the proper source. Now `@babel/preset-env` uses `babel-plugin-polyfill-corejs3` which uses `core-js-compat` directly.

**Pull request merged**
