### PR TITLE
[Merged by Bors] - Async generator

### LINKED ISSUE #612: Parsing an async generator function returns a syntax error
**Input code**

```ts
async function* agf() {}
```

**Expected behavior**

Ability to parse this.

ECMAScript 2018 proposal: https://github.com/tc39/proposal-async-iteration#async-generator-functions

**Version**

Latest

**Additional context**

The code that causes this in swc is here: https://github.com/swc-project/swc/blob/480015d407c74f12f8454e553dd8e65e131ab0ce/ecmascript/parser/src/parser/class_and_fn.rs#L764

### PR DESCRIPTION
**Pull request by kdy1**
Change parser to accept async generator.

Closes #612.

### CODE REVIEW

**Comment by Mouvedia** [comment]
Does [this page](https://swc.rs/docs/comparison-babel) need to be updated?

**Comment by kdy1** [comment]
@Mouvedia Yes, I forgot updating it.

**Comment by Mouvedia** [comment]
@kdy1 dunno why but babel-plugin-syntax-async-generators swc row is empty.

**Comment by kdy1** [comment]
@Mouvedia Fixed it, thanks!

**Pull request closed without merging**
