### PR TITLE
fix(html/parser): raw ast for comment token

### PR DESCRIPTION
**Pull request by alexander-akait**
**Description:**

`raw` should be always `Option<...>`

**BREAKING CHANGE:**

Yes

**Related issue (if exists):**

No

### CODE REVIEW

**Review by kdy1 — APPROVED** [review]
swc-bump:
 - swc_html_ast --breaking

**Review by kdy1 — CHANGES_REQUESTED** [review]
ci failed

**Comment by alexander-akait** [comment]
@kdy1 Fixed

**Review by kdy1 — APPROVED** [review]
swc-bump: 
 - swc_html_ast --breaking

**Pull request merged**
