### PR TITLE
fix(bundler): Fix statement ordering issue

### PR DESCRIPTION
**Pull request by kdy1**
Note: I postponed denoland/deno#8597.

---

swc_bundler:
 - [x] Reduce binary size by reducing usage of visitor / folders.
 - [x] Handle `export *` and `export { default }` from same source. (denoland/deno#8530, denoland/deno#8679)
 - [x] Fix ordering of statements. (denoland/deno#8545)
 - [x] Sort statements in wrapped modules. (https://github.com/denoland/deno/issues/8211#issuecomment-741070299)
 - [x] Exclude default export while handling `export *`.
 - [x] Exclude `export { default }` and `export { foo as default }` while handling `export *`.
 - [x] Make statements from same module to be injected together. (denoland/deno#8620)

swc_ecma_transforms:
 - [x] fixer: Handle assignments in the callee of `new`  correctly.
 - [x] fixer: Handle seqence expression in the callee of `new`  correctly.

---

I investigated further.

8620 fails, and it's expected.

With lots of logging code and in debug build, all other tests pass.

But when I removed logging code and tested in release mode, 

 - deno_8211_1

also fails.

# Try: 8620

```rust 
  for &dep in &deps {
            let cycles = self.graph.all_simple_paths(dep, idx);
            dbg!(&cycles);  
            if !cycles.is_empty() {
                self.emit_cycles(cycles);
                continue;
            }
            // We jump to another module.
            eprintln!("Jumping to dep: `{}`", dep);
            self.insert_inner(dep, false, dejavu, delayed, &[]);

            eprintln!("Done: one dep of `{}`: `{}`", idx, dep);
        }
        eprintln!("Done: deps of `{}`: `{:?}`", idx, deps);
```

hangs with

```
[bundler/src/bundler/modules/sort.rs:601] next_idx = 195
Checking `195`
[bundler/src/bundler/modules/sort.rs:519] &cycles = []
Jumping to dep: `194`
Checking `194`
Skipping `194`
Done: one dep of `195`: `194`

```

So... all_simple_paths hangs in certain condition. 

# Fix for petgraph

I'm trying to capture all graph operations in parsable form, and I'll use it to debug petgraph.

# Tests

 - [x] deno_7288_1: 
 - [x] deno_8188_01: 
 - [x] deno_8188_02: 
 - [x] deno_8188_03: 
 - [x] deno_8188_full: 
 - [x] deno_8189: 
 - [x] deno_8211_1: 
 - [x] deno_8246: 
 - [x] deno_8302: 
 - [x] deno_8314_1: 
 - [x] deno_8314_2: 
 - [x] deno_8399_1: 
 - [x] deno_8399_2: 
 - [x] deno_8481_1: 
 - [x] deno_8486_1: 
 - [x] deno_8530: 
 - [x] deno_8573:
 - [x] deno_8620: 
 - [x] deno_8627: 
 - [x] exec_deno_exec__deno_8211__case2__entry_ts: 
 - [x] exec_deno_exec__deno_8545__entry_ts: 
 - [x] merging_order_01: 
 - [x] oak_6_3_1_application: 
 - [x] oak_6_3_1_example_server: 
 - [x] oak_6_3_1_example_sse_server: 
 - [x] oak_6_3_1_mod: 
 - [x] reexport_01: 
 - [x] std_0_74_0_http_server:

### CODE REVIEW

**Comment by kdy1** [comment]
I found lots of bugs of petgraph...
I just workarounded most of them to reduce time, but I found a bug which is hard to workaround.

Currently failing tests except `8620` fails due to bug of petgraph.

**Comment by ije** [comment]
thanks for your fabulous work! will wait you to fix `8620`.

**Comment by kdy1** [comment]
I found that almost all tests pass if I wrap `DiGraphMap` from petgraph with custom struct.
I'm not sure what's going on...

**Comment by ije** [comment]
thanks!

**Pull request merged**
