### PR TITLE
fix(es/preset-env): Fix compilation issue

### LINKED ISSUE #3971: `node_modules/core-js-compat/data.json: No such file or directory`
Probably caused by https://github.com/swc-project/swc/pull/3968

```
error: couldn't read /Users/niklas/.cargo/registry/src/github.com-1ecc6299db9ec823/swc_ecma_preset_env-0.105.0/src/corejs3/../../../../node_modules/core-js-compat/data.json: No such file or directory (os error 2)
  --> /Users/niklas/.cargo/registry/src/github.com-1ecc6299db9ec823/swc_ecma_preset_env-0.105.0/src/corejs3/compat.rs:9:26
   |
9  |       serde_json::from_str(include_str!(
   |  __________________________^
10 | |         "../../../../node_modules/core-js-compat/data.json"
11 | |     ))
   | |_____^
```

### PR DESCRIPTION
**Pull request by kdy1**
**Description:**

I added copy script to the `prepare` yarn script so invoking `yarn` will update the json files.

**Related issue (if exists):**

 - Closes #3971

### CODE REVIEW

**Review by kdy1 — COMMENTED** [review]
swc-bump:
 - swc_ecma_preset_env

**Comment by kdy1** [comment]
Oh, thank you! I'll do it with https://github.com/swc-project/swc/pull/3973

**Comment by kdy1** [comment]
I reverted the removal of `.json` files as windows CI failed.
Seems like `yarn` on windows does not execute the required shell script? I'm not sure...

**Comment by Austaras** [comment]
Maybe because windows doesn't have bash? It's better to use a nodejs script

**Comment by kdy1** [comment]
Oh, you are right. I forgot that it's possible.
Thank you!

**Pull request merged**
