### PR TITLE
feat(wasm): Add json error

### PR DESCRIPTION
**Pull request by kdy1**
**Description:**

I'm not sure if it's generally useful, so I added it only to wasm.
But I think we need some `experimental` flag here.

**Related issue (if exists):**

 - https://github.com/swc-project/swc-playground/pull/19#issuecomment-1140815636

### CODE REVIEW

**Comment by kwonoj** [comment]
Am I reqding correct this makes error emits into json formatted insted of current format?

**Comment by kdy1** [comment]
Yeah, but I'm not sure about this api.

cc @g-plane

**Comment by kwonoj** [comment]
Yes, this would be useful if someone want to consume swc as separate step for build pipeline and reads its output as machine-readable. Main q is do we have actual usecase.

**Comment by kdy1** [comment]
We have one known usecase at the moment. SWC playground can show errors with better formatting

**Comment by kwonoj** [comment]
I'm in for having as experimental for those case.

**Comment by g-plane** [comment]
Should we pass those options as the third argument in those `parseSync`, `transformSync` function? Two reasons:

- Keep the second argument be focusing on SWC config, nothing else.
- If we have more WebAssembly-specific options in the future, we can reuse that options, instead of mixing the second argument.

**Comment by kdy1** [comment]
Sounds reasonable, thanks!

**Comment by g-plane** [comment]
SWC config's `experimental` property can be used everywhere, not only WebAssembly. Will it confuse those non-WebAssembly users?

**Comment by kwonoj** [comment]
I expect if we'll have this, at least native cli would want same (as experimental). Stdout with structured output is quite common usecase.

**Comment by g-plane** [comment]
Sounds reasonable.

**Review by kdy1 — COMMENTED** [review]
swc-bump:
 - swc --breaking

**Pull request merged**
