### PR TITLE
feat(es/ast): Improve AST api for plugin authors

### LINKED ISSUE #3239: Lots of `impl From` for AST nodes
### Describe the feature

We should implement lots of `From`s for ast types. This is to help plugin authors.

e.g. `impl From<bool> for Expr` allows more convinient ast manipulation like `true.as_arg()`.

 - `impl From<{bool, f64, BIgIntValue, JsWord,  &str, String, Cow<'_, str>}> for {Lit, Expr}`
 - `impl From<{Number, Str} for {Expr}`.

### Babel plugin or link to the feature description

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by kdy1**
# ChangeLog

swc_ecma_ast:
 - Improve API for AST creation.

## Cleanup

This is required as plugin authors will look at core transforms to know what they can do.

 - [x] Pat::Ident
 - [x] Pat::from
 - [x] AssignOp
 - [x] BinaryOp
 - [x] UnaryIOp

**Description:**

**BREAKING CHANGE:**

**Related issue (if exists):**

 - Closes #3239

### CODE REVIEW

**Review by kdy1 — COMMENTED** [review]
Do you have any suggestion related to 'intuitive' implementations of `From`?

**Comment by kwonoj** [comment]
Mind share some usecase example?

Also, what does `bridge_` means? Does it mean wrap to `into` only?

**Comment by kdy1** [comment]
@kwonoj I add a commit to demonstrate what can be done. https://github.com/swc-project/swc/pull/3281/commits/8817855aa76c81b3f8ad997d73d9138c13568184

**Review by kwonoj — DISMISSED** [review]
In my opinion, this looks reasonable.

Reiterating discussions for the record

- We may want to collect some feedback from actual plugin author what kind of helper features we need to provide
- We may not able to provide 1:1 to other tools (i.e babel's helper)
- While experiment we'll limit adding new features until we get some feedback.

**Pull request merged**
