### PR TITLE
build(preset-env/base): Upgrade `browserslist-rs` to `v0.13.0`

### PR DESCRIPTION
**Pull request by mischnic**
**Description:**

Upgrade browserslist-rs, there was a major version change because wasm-pack functionality was split out into a feature:

https://github.com/browserslist/browserslist-rs/compare/v0.12.4...v0.13.0

### CODE REVIEW

**Review by kdy1 — CHANGES_REQUESTED** [review]
Thanks! Requesting change as the CI failed.

---

swc-bump:
 - preset_env_base

**Comment by mischnic** [comment]
As far as I can tell, the failing tests doesn't even build for wasm. So I have no idea why they fail

**Comment by kdy1** [comment]
Then I'll fix them. `swc_core` one is about Wasm plugins and the `swc_css_prefixer` is about updating test references. (Browser data changed)

**Review by kdy1 — APPROVED** [review]

**Comment by mischnic** [comment]
Thank you!

**Pull request merged**
