### PR TITLE
test(html/parser): add big integration tests from html5lib-test

### PR DESCRIPTION
**Pull request by alexander-akait**
**Description:**

Tests from html5-lib:
1. Recretate HTML/AST/DOM in our tests
2. Created DomVisualizer - it is like DOM in browser but in texttual simplified mode, it allow to ensure we create the same AST as firefox/servo/chrome (they used the same tests)

Currently from >=2000 tests, we passed 1600+, found couple bugs, so I will fix them step by step

Also we need to implement `parse_template` for parsing `template` content, because some tests for them, they are failed currenty. 

When we finish it - it will mean we fully covert HTML parsing

Late I want to add also errors message tests to ensure we have the same error and location, but currently it is less priority

For each implement I putted TODO

**BREAKING CHANGE:**

No

**Related issue (if exists):**

No

### CODE REVIEW

**Comment by alexander-akait** [comment]
@kdy1 I think we can merge it, other bugs/improvements I will do step by step

**Comment by alexander-akait** [comment]
@kdy1 Make sense to merge firstly, before other PRs to avoid extra rebasing

**Comment by kdy1** [comment]
I'm not sure how should I review this

**Comment by kdy1** [comment]
Do we really need this PR inlined?
I think this will make git operation much slower

**Review by kdy1 — DISMISSED** [review]

**Comment by alexander-akait** [comment]
I think we need rebase here, because we merge other commits before, WIP

**Review by kdy1 — APPROVED** [review]

**Review by kdy1 — APPROVED** [review]
swc-bump:
 - ''

**Pull request merged**
