### PR TITLE
fix(es/transforms/module/common_js):  fix duplicate named exports iss…

### LINKED ISSUE #1780: more than one `export * from`  cause `Cannot redefine property` when re-imports have same name export
Hi, I'm working in Ringcentral Inc. I plan to use swc for reducing build time.

**I'm willing to help fix it**
## Describe the bug
in this demo, I have these files
``` ts
// constant.ts
export enum Foo {};
```

``` ts
// File1.ts
export {Foo} from './constant';
```

``` ts
// file2.ts
export {Foo} from './constant';
```
### Input code

``` ts
// index.ts
export const BIZ = 'biz';
export * from './File1';
export * from './File2';
```

and I compile it with swc, then run the index.js

it through an error
image

the compile result of index.ts is
``` js
"use strict";
Object.defineProperty(exports, "__esModule", {
    value: true
});
var _exportNames = {
    BIZ: true
};
exports.BIZ = void 0;
var _file1 = require("./File1");
var _file2 = require("./File2");
function _interopRequireWildcard(obj) {
    if (obj && obj.__esModule) {
        return obj;
    } else {
        var newObj = {
        };
        if (obj != null) {
            for(var key in obj){
                if (Object.prototype.hasOwnProperty.call(obj, key)) {
                    var desc = Object.defineProperty && Object.getOwnPropertyDescriptor ? Object.getOwnPropertyDescriptor(obj, key) : {
                    };
                    if (desc.get || desc.set) {
                        Object.defineProperty(newObj, key, desc);
                    } else {
                        newObj[key] = obj[key];
                    }
                }
            }
        }
        newObj.default = obj;
        return newObj;
    }
}
var BIZ = 'biz';
exports.BIZ = BIZ;
Object.keys(_file1).forEach(function(key) {
    if (key === "default" || key === "__esModule") return;
    if (Object.prototype.hasOwnProperty.call(_exportNames, key)) return;
    Object.defineProperty(exports, key, {
        enumerable: true,
        get: function() {
            return _file1[key];
        }
    });
});
Object.keys(_file2).forEach(function(key) {
    if (key === "default" || key === "__esModule") return;
    if (Object.prototype.hasOwnProperty.call(_exportNames, key)) return;
    Object.defineProperty(exports, key, {
        enumerable: true,
        get: function() {
            return _file2[key];
        }
    });
});

```
### config

```json
{
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "tsx": true,
      "decorators": true
    },
    "transform": {
      "legacyDecorator": true
    }
  },
  "module": {
    "type": "commonjs",

    "strict": false,
    "strictMode": true,
    "lazy": false,
    "noInterop": false
  }
}

```

## Expected behavior
the index.js run and exit without error

## Version
The version of @swc/core: 1.2.59

## Additional context
compare with the result via babel, it has a extra check before `Object.defineProperty`

``` js
if (key in exports && exports[key] === _utils[key]) return;
```

### PR DESCRIPTION
**Pull request by IronLu233**
totally fix  (#1780)
This is from https://github.com/babel/babel/blob/b2d9156cc62d37f4c522c9505a00f50b99a1eb74/packages/babel-helper-module-transforms/src/index.ts#L206
and
https://github.com/babel/babel/blob/b2d9156cc62d37f4c522c9505a00f50b99a1eb74/packages/babel-helper-module-transforms/src/index.ts#L302

---

Closes #1780

### CODE REVIEW

**Comment by kdy1** [comment]
I'm sorry but it's already fixed by https://github.com/swc-project/swc/pull/1829

**Comment by IronLu233** [comment]
So should I need open a new issue for it?

**Comment by kdy1** [comment]
What do you are trying to fix?
If there are some unhandled edge cases left, I'll reopen the issue.

**Comment by IronLu233** [comment]
Please reopen the issue.
I want add `if (key in exports && exports[key] === _File2[key]) return;` in each named export.
If we don't have this judge, when two module have same named-export, the code will emit a error:
image
source:
``` typescript
export const BIZ = 'biz';
export * from './File1';
export * from './File2';
```
compile result of swc:
``` javascript
"use strict";
Object.defineProperty(exports, "__esModule", {
    value: true
});
var _exportNames = {
    BIZ: true
};
exports.BIZ = void 0;
var _file1 = require("./File1");
var _file2 = require("./File2");
function _interopRequireWildcard(obj) {
    if (obj && obj.__esModule) {
        return obj;
    } else {
        var newObj = {
        };
        if (obj != null) {
            for(var key in obj){
                if (Object.prototype.hasOwnProperty.call(obj, key)) {
                    var desc = Object.defineProperty && Object.getOwnPropertyDescriptor ? Object.getOwnPropertyDescriptor(obj, key) : {
                    };
                    if (desc.get || desc.set) {
                        Object.defineProperty(newObj, key, desc);
                    } else {
                        newObj[key] = obj[key];
                    }
                }
            }
        }
        newObj.default = obj;
        return newObj;
    }
}
var BIZ = 'biz';
exports.BIZ = BIZ;
Object.keys(_file1).forEach(function(key) {
    if (key === "default" || key === "__esModule") return;
    if (Object.prototype.hasOwnProperty.call(_exportNames, key)) return;
    Object.defineProperty(exports, key, {
        enumerable: true,
        get: function() {
            return _file1[key];
        }
    });
});
Object.keys(_file2).forEach(function(key) {
    if (key === "default" || key === "__esModule") return;
    if (Object.prototype.hasOwnProperty.call(_exportNames, key)) return;
    Object.defineProperty(exports, key, {
        enumerable: true,
        get: function() {
            return _file2[key];
        }
    });
});
```
compile result of babel:
``` javascript
"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
var _exportNames = {
  BIZ: true
};
exports.BIZ = void 0;

var _File = require("./File1");

Object.keys(_File).forEach(function (key) {
  if (key === "default" || key === "__esModule") return;
  if (Object.prototype.hasOwnProperty.call(_exportNames, key)) return;
  if (key in exports && exports[key] === _File[key]) return;
  Object.defineProperty(exports, key, {
    enumerable: true,
    get: function () {
      return _File[key];
    }
  });
});

var _File2 = require("./File2");

Object.keys(_File2).forEach(function (key) {
  if (key === "default" || key === "__esModule") return;
  if (Object.prototype.hasOwnProperty.call(_exportNames, key)) return;
  if (key in exports && exports[key] === _File2[key]) return;
  Object.defineProperty(exports, key, {
    enumerable: true,
    get: function () {
      return _File2[key];
    }
  });
});
const BIZ = 'biz';
exports.BIZ = BIZ;
```

**Comment by IronLu233** [comment]
Hi, @kdy1 , I updated the branch and confirmed all unit test passed. Please approve the workflow.

**Review by kdy1 — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
