### PR TITLE
test: rebase html5lib-test

### PR DESCRIPTION
**Pull request by alexander-akait**
**Description:**

Update html5lin-test before improve tests + more tests

**BREAKING CHANGE:**

No

**Related issue (if exists):**

Work before https://github.com/swc-project/swc/pull/6014

### CODE REVIEW

**Review by kdy1 — APPROVED** [review]
swc-bump:
 - dbg-swc

**Comment by kdy1** [comment]
Seems like there's a problem with submodules

**Comment by alexander-akait** [comment]
Yeah, will fix it soon

**Comment by alexander-akait** [comment]
@kdy1 Fixed :+1:

**Review by kdy1 — APPROVED** [review]

**Pull request merged**
