### PR TITLE
Upgrade dependencies, mainly lexical for better performance

### PR DESCRIPTION
**Pull request by Brooooooklyn**
### Lexer
test three         ... bench:  14,350,033 ns/iter (+/- 767,897) = 82 MB/s

### Parser:
test three         ... bench:  27,030,841 ns/iter (+/- 765,058) = 43 MB/s

### Lexer
test three         ... bench:  14,089,720 ns/iter (+/- 667,112) = 84 MB/s

### Parser
test three         ... bench:  26,409,095 ns/iter (+/- 1,086,535) = 44 MB/s

### CODE REVIEW

**Review by kdy1 — APPROVED** [review]
Thank you!

I profiled this multiple time and seems like it's a bit faster.

---


swc-bump:
 - ast_node
 - jsdoc
 - preset_env_base
 - swc
 - swc_bundler
 - swc_cli
 - swc_common
 - swc_css_parser
 - swc_ecma_ast
 - swc_ecma_codegen
 - swc_ecma_dep_graph
 - swc_ecma_ext_transforms
 - swc_ecma_lints
 - swc_ecma_loader
 - swc_ecma_minifier
 - swc_ecma_parser
 - swc_ecma_transforms
 - swc_ecma_transforms_base
 - swc_ecma_transforms_compat
 - swc_ecma_transforms_optimization
 - swc_ecma_transforms_proposal
 - swc_ecma_transforms_react
 - swc_ecma_transforms_testing
 - swc_ecma_utils
 - swc_ecma_visit
 - swc_eq_ignore_macros
 - swc_estree_compat
 - swc_fast_graph --breaking
 - swc_graph_analyzer --breaking
 - swc_macros_common
 - swc_plugin_runner
 - testing

**Review by kdy1 — CHANGES_REQUESTED** [review]
Oh... Can you rebase?

**Comment by Brooooooklyn** [comment]
@kdy1 rebased

**Review by kdy1 — APPROVED** [review]
Thank you!

**Pull request merged**
