### PR TITLE
fix(ecma_parser) Allow arrow func without parenthesisised param in conditional for TS

### PR DESCRIPTION
**Pull request by williamtetlow**
**Description:**
Fixes https://github.com/swc-project/swc/issues/2174, https://github.com/swc-project/swc/issues/4067

In https://github.com/swc-project/swc/pull/3685#issuecomment-1050701591 we removed TS support for arrow function without parenthesis on single param to match the behaviour of TSC.

As of https://github.com/microsoft/TypeScript/pull/47550 TSC supports this syntax.

This PR adds support for syntax.

**BREAKING CHANGE:**

**Related issue (if exists):**
 - Fixes https://github.com/swc-project/swc/issues/2174
 - Fixes https://github.com/swc-project/swc/issues/4067

### CODE REVIEW

**Review by kdy1 — APPROVED** [review]
LGTM. Thank you!

---

swc-bump:
 - swc_ecma_parser

**Comment by jakebailey** [comment]
FYI, we just reverted https://github.com/microsoft/TypeScript/pull/47550 for TS 4.7 (in https://github.com/microsoft/TypeScript/pull/48940), as it caused some unexpected breaks (with plans to solve it for real in 4.8). So, you my want to back this one out.

**Comment by williamtetlow** [comment]
Ah yep we had the same bug 😆  we've fixed that case and one other on our side and haven't seen any other issues come in

@kdy1 I'll let you decide whether we pull this or leave it in seeing as it will be released in 4.8?

**Comment by kdy1** [comment]
I think it's better to revert this and #4302 for now

**Comment by williamtetlow** [comment]
Cool I can submit PR later today

**Comment by kdy1** [comment]
Thank you!

I was busy due to the new minifier rule :)

**Pull request merged**
