### PR TITLE
Test Reflect.metadata existed before use it

### PR DESCRIPTION
**Pull request by Brooooooklyn**

### CODE REVIEW

**Review by kdy1 — APPROVED** [review]
Thanks!

**Comment by kdy1** [comment]
Wait a minute, doesn't this make output size very larger?

**Comment by Brooooooklyn** [comment]
> doesn't this make output size very larger

Yes, but `TypeScript` also do it in this way [Playground](https://www.typescriptlang.org/play?#code/GYVwdgxgLglg9mABASTAKwKbQIYCMA2GAFAJSIDeiAThlCFUkVGQLwB8iUiAvgFC8ABVJhwFiJXhHzYAzjMQARDAAcKkhDKhUQ0OFSLKQBGBEQRsEABYYAyjABeGAFyIwIALa4MVADSJDxqYAJioAKgDucC5KyhFwZOR8fILCWFB4hKSS0nKKYZEU3EA), maybe we could add `__decorate` helper to reduce the output size.

> Also, I'm curious if it's spec-compilant.

You mean `Reflect.decorate`? I followed the implement of `TypeScript`, so I think there is no `spec-compilant` problem.

**Comment by kdy1** [comment]
Got it. If tsc do it, it's okay.

**Review by kdy1 — APPROVED** [review]

**Pull request merged**
