### PR TITLE
Perf/source map mutibyte

### PR DESCRIPTION
**Pull request by IWANABETHATGUY**
**Description:**

**BREAKING CHANGE:**

**Related issue (if exists):**

### CODE REVIEW

**Comment by kdy1** [comment]
I think https://github.com/swc-project/swc/pull/6523 is a better fix, but not sure if it's correct fix

**Comment by IWANABETHATGUY** [comment]
I would like to help to testing the performance.

**Comment by kdy1** [comment]
You can add `large.js` to `swc_ecma_minifier/benches/full` and uncomment https://github.com/swc-project/swc/blob/1425475f4af7c50db4fc415feb4e3f49eea6b101/crates/swc/benches/minify.rs#L87

**Comment by IWANABETHATGUY** [comment]
using the issue https://github.com/swc-project/swc/issues/6411 `large.js` 
## before: 
image
## this pr: 
image

**Pull request closed without merging**
