### PR TITLE
chore: Publish `v1.3.46` with fixed `peerDependency`

### PR DESCRIPTION
**Pull request by kdy1**
**Description:**

**Related issue:**

 - Closes https://github.com/swc-project/swc/issues/7203.

### CODE REVIEW

**Comment by kdy1** [comment]
It deprecates a whole package 
image

**Comment by magic-akari** [comment]
> It deprecates a whole package
> image

1.3.46 has not been released yet, so it may be a display issue.

**Comment by kdy1** [comment]
I tested it, but it hides `@swc/core` from the search result

**Comment by magic-akari** [comment]
> I tested it, but it hides `@swc/core` from the search result

run this before 1.3.46 released.
```
npm dist-tag add @swc/core@1.3.44 latest
```

**Comment by kdy1** [comment]
Thank you!

**Pull request merged**
