### PR TITLE
fix(ecma/parser): Reorder read_digits parameters

### PR DESCRIPTION
**Pull request by LekoArts**
**Description:**

Hi!

This is my first PR to swc (and hopefully not the last 👍 ) so let me know if I did anything wrong for the contribution process :)

I'm currently trying to build Parcel (it uses swc_ecma_parser) and it currently fails on https://github.com/swc-project/swc/issues/4004 -- so I figured: Let's put up a PR!

**Related issue (if exists):**

Closes https://github.com/swc-project/swc/issues/4004

### CODE REVIEW

**Review by kdy1 — APPROVED** [review]
Thank you!
Looks like the correct fix.

---

swc-bump:
 - swc_ecma_parser

**Comment by kdy1** [comment]
Can you sign the CLA?

**Comment by LekoArts** [comment]
Done! 👍

**Comment by LekoArts** [comment]
I saw you've added it to the 1.2.156 milestone but also a bot publishes the crates on the main branch: https://github.com/swc-project/swc/commits/main

Can I read up the release process somewhere or can you give me a TL;DR? Thanks!

**Comment by kdy1** [comment]
Oh, all changes are published for rust-side users, once a PR is merged.
`swc-bump` in the *my* review comments denote which crate should be published.
But it's good to have documentation for it.

The milestone and tag are used to track the version of node.js binary.

**Comment by LekoArts** [comment]
> The milestone and tag are used to track the version of node.js binary.

Ahh, that was the missing piece for me. Thanks, appreciate it

**Review by kdy1 — APPROVED** [review]

**Pull request merged**
