### PR TITLE
feat(parser/ts): support optional variance annotations

### PR DESCRIPTION
**Pull request by magic-akari**
**Description:**
Implement: Optional variance annotations

**BREAKING CHANGE:**

**Related issue (if exists):**
- https://github.com/microsoft/TypeScript/pull/48240

### CODE REVIEW

**Comment by kdy1** [comment]
Is it included in rc? I didn't check the typescript blog recently...

**Comment by magic-akari** [comment]
No, I just made it "ready for review".
I was concerned that there might be some issues that needed to be revised.

do not merge until microsoft/TypeScript#48240 is merged.

**Comment by kdy1** [comment]
I see, thanks!

**Review by kdy1 — COMMENTED** [review]
LGTM. Thank you!
Not marking as approval as to prevent mistake

**Comment by magic-akari** [comment]
I'm testing the type variance annotations with JSX(tsx).

```tsx
const validJSX = <in T>() => {}</in>;

const validTypeVarianceFN = <in T,>() => {};

const expectedError = <in T>() => {};
```

The first two are parsed expected.
However, the last one did not report an error.

> Single type parameter T should have a trailing comma.

When I investigated, I found that this was a pre-existing issue.
What do you think about it?
Maybe we should open a new issue to track it.

```tsx
const expectedError = <T>() => {};
```

**Comment by kdy1** [comment]
I didn't know that `const expectedError = <T>() => {};` is an error. I think we need an issue, thank you!

**Comment by magic-akari** [comment]
Babel will revert this feature and defer it to Babel 8.
cc @kdy1 

- https://github.com/babel/babel/pull/14367

**Comment by nicolo-ribaudo** [comment]
Note that it should be an error only in TSX files, not in TS files. Due to how Babel needs to be configured, many people enabled TSX mode also for `.ts` files: swc might not have the same problem and you might be able to ship it without introducing breakages.

**Comment by kdy1** [comment]
@magic-akari I found that typescript PR is merged, and you added some tests.
Is this PR ready to review?

**Comment by magic-akari** [comment]
Yes. It's ready for review.

**Review by kdy1 — APPROVED** [review]
Thank you!

---

swc-bump:
 - swc_atoms
 - swc_ecma_ast --breaking

**Pull request merged**
