### PR TITLE
test(html/parser): tests

### PR DESCRIPTION
**Pull request by alexander-akait**
**Description:**

There are buggy tests, but I think it should be fixed by https://github.com/swc-project/swc/pull/4502, so I will rebase after merge https://github.com/swc-project/swc/pull/4502 and check snapshots

**BREAKING CHANGE:**

No

**Related issue (if exists):**

No

### CODE REVIEW

**Comment by kdy1** [comment]
Can you rebase?
CI failed

**Comment by alexander-akait** [comment]
Yep, WIP :+1:

**Comment by alexander-akait** [comment]
@kdy1 Done0

**Review by kdy1 — APPROVED** [review]
swc-bump:
 - ''

**Pull request merged**
