### PR TITLE
fix(css/codegen): preserved tokens output

### PR DESCRIPTION
**Pull request by alexander-akait**
**Description:**

fix codegen with preserved comments

**BREAKING CHANGE:**

No

**Related issue (if exists):**

No

### CODE REVIEW

**Review by kdy1 — APPROVED** [review]
LGTM.

---

swc-bump:
 - swc_css_codegen

**Review by kdy1 — CHANGES_REQUESTED** [review]
Can you fix clippy errors?
I removed it from husky hook because it was too annoying

**Comment by alexander-akait** [comment]
:+1: WIP

**Review by kdy1 — APPROVED** [review]

**Comment by kdy1** [comment]
CI failed, can you update?

**Review by kdy1 — APPROVED** [review]

**Pull request merged**
