### PR TITLE
fix import statements improperly being transformed when symlinks are utilized

### PR DESCRIPTION
**Pull request by clhuang**
**Description:**
Fixes https://github.com/swc-project/swc/issues/4057.

https://github.com/swc-project/swc/pull/3340/files changed the behavior to canonicalize symlinks when invoking the swc compiler, as far as I can tell this was an unintended change. This restores the original behavior.

**BREAKING CHANGE:**

**Related issue (if exists):**
https://github.com/swc-project/swc/issues/4057
https://github.com/swc-project/swc/issues/2945

### CODE REVIEW

**Review by kdy1 — APPROVED** [review]
Thank you!

---


swc-bump:
 - swc

**Review by kdy1 — CHANGES_REQUESTED** [review]
CI faied.
Please run `UPDATE=1 cargo test` from `./crates/swc`

**Comment by clhuang** [comment]
updated -- the broken tests seemed to be representative of the previous broken behavior

**Review by kdy1 — APPROVED** [review]
Thanks!
Finally I found the reason CI failes 🤣 

---

swc-bump:
 - swc

**Pull request merged**
