### PR TITLE
feat(es/codegen): emit comments in method emit_module and emit_script

### LINKED ISSUE #3354: Using `emit_leading_comments_of_span` for `emit_module` and `emit_script`
### Describe the feature

```diff
#[emitter]
    pub fn emit_module(&mut self, node: &Module) -> Result {
+      self.emit_leading_comments_of_span(node.span(), false)?;
        if let Some(ref shebang) = node.shebang {
            punct!("#!");
            self.wr.write_str_lit(DUMMY_SP, &*shebang)?;
            self.wr.write_line()?;
        }
        for stmt in &node.body {
            emit!(stmt);
        }
+      self.emit_trailing_comments_of_pos(node.span().hi, true, true)?;
    }
```

I'm doing something like. Because some AST nodes in `module#body` were deleted in manipulating, I couldn't get the correct comment output with the following codes.

```rs
let comments = SingleThreadedComments::default();

self.swc_modules.iter().for_each(|module| {
  comments.add_leading(
      module.span.lo,
      Comment {
          kind: CommentKind::Line,
          span: DUMMY_SP,
          text: format!(" {}", SOME_DEBUG_INFO),
      },
  );
});

let mut emitter = swc_ecma_codegen::Emitter {
  cfg: swc_ecma_codegen::Config { minify: false },
  cm: crate::graph::SOURCE_MAP.clone(),
  comments: Some(&comments),
  wr: Box::new(JsWriter::with_target(
      crate::graph::SOURCE_MAP.clone(),
      "\n",
      &mut output,
      None,
      EsVersion::latest(),
  )),
};
```

This is my hack version now.
```diff

self.swc_modules.iter().for_each(|module| {
+ module.ast.body.insert(
+   0,
+   ModuleItem::Stmt(Stmt::Empty(EmptyStmt {
+       span: swc_common::Span {
+           lo: module.ast.span.lo,
+           hi: module.ast.span.hi,
+           ..Default::default()
+       },
+   })),
+ );
  comments.add_leading(
      module.span.lo,
      Comment {
          kind: CommentKind::Line,
          span: DUMMY_SP,
          text: format!(" {}", SOME_DEBUG_INFO),
      },
  );
});


```

I would like to send a PR to do this if there's no downside to this.

### Babel plugin or link to the feature description

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by iheyunfei**
**Description:**

**BREAKING CHANGE:**

**Related issue (if exists):**

Close #3354.

### CODE REVIEW

**Comment by iheyunfei** [comment]
The [benchmark result](https://github.com/iheyunfei/swc/commit/949027c054eba5201cf798d92a8ba6be15a20c5e#commitcomment-64546222) seems not optimistic.

**Comment by kdy1** [comment]
Can you run `UPDATE=1 cargo test` on `/crates/swc`?
You may need to run it multiple times.

**Review by kdy1 — APPROVED** [review]

**Comment by iheyunfei** [comment]
> Can you run `UPDATE=1 cargo test` on `/crates/swc`? You may need to run it multiple times.

I ran 4 times. One test failed the first and second times. All tests pass after the second time. 
Running these tests changes some `.js` files, should I also commit these changes?

**Comment by kdy1** [comment]
> should I also commit these changes?

Yes

**Review by kdy1 — APPROVED** [review]
LGTM. Thanks!

**Pull request merged**
