### PR TITLE
fix(es/compat): Transform curried function call with optional chaining

### LINKED ISSUE #7312: Transform optional chaining maybe incorrectly, inconsistent with babel
### Describe the bug

If a is `undefined`, this code can run in browser directly, and Babel transformed like this:

image

SWC output:
(a === null || a === void 0 ? void 0 : a.b())();

Is this an expected behavior

### Input code

```typescript
a?.b()()
```

### Config

```json
{
  "jsc": {
    "transform": {
      "react": {
        "runtime": "automatic"
      }
    },
    "parser": {
      "syntax": "typescript",
      "tsx": true
    },
    "target": "es5",
    "loose": false,
    "minify": {
      "compress": false,
      "mangle": false
    }
  },
  "module": {
    "type": "es6"
  },
  "minify": false,
  "isModule": true
}
```

### Playground link

https://play.swc.rs/?version=1.3.52&code=H4sIAAAAAAAAA0u010vS0NTQ5AIA1MkElQkAAAA%3D&config=H4sIAAAAAAAAA1VQyw6DMAy77ytQzly3w%2F5hHxF1AXWiDyWpNIT497WFMji1tR3b6XLrOviIgWe35Gt%2BKKOXIbA7oAwyodETUKDk1TrKIGDS4FCtgZ1e67n2m2NEFuKzncxe8VtGdY4khm1U6BurUijlRBcbRR6plACS%2B66GKQQpHQachHbMWW%2BH%2BZxngotMIldhkaIfp2P%2B1rrXSHDhnSrZfiZ33eIf8Be1sMMYrLzaZF1i%2FQEQs2upZQEAAA%3D%3D

### Expected behavior

if a is undefined, code can run successfully

### Actual behavior

Output code is `(a === null || a === void 0 ? void 0 : a.b())();`, an Error has been thrownÏ

### Version

1.3.52

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by JSerFeng**
**Description:**

Fix transform of curried function call with option chain

close #7312 

**BREAKING CHANGE:**

**Related issue (if exists):**

### CODE REVIEW

**Comment by kdy1** [comment]
Can you run `UPDATE=1 cargo test --test tsc` from `./crates/swc`?

**Comment by JSerFeng** [comment]
Done, but is this expected ? The parentheses disappear but the test in `swc_ecma_transform_compat` is right

**Comment by JSerFeng** [comment]
Maybe due to the fixer, I will try to troubleshoot it.

**Comment by JSerFeng** [comment]
It's the `paren_remover` removes the parentheses that should have been there. I will try to fix it and let me know if you have any clues.

**Comment by kdy1** [comment]
`paren_remover` is applied before other passes and it should not be applied on final result...

**Comment by JSerFeng** [comment]
Yes, `paren_remover` transforms `(a?.b.c)();` into `a?.b.c();`, maybe we can return if expr contains opt_chain, but that might have performance issue
image

**Comment by JSerFeng** [comment]
`(a?.b.c).d` and `a?.b.c.d` is not the same, so it cannot remove the parentheses when `Expr` contains opt_chain in it, I added a way to detect if it contains opt_chain, do you think this is approprait

**Comment by kdy1** [comment]
Yeah I think it's fine.
IIRC, there's already a case where `paren_remover` and `fixer` simply don't unwrap parens because injecting parenthesis correctly is a way too hard task

**Comment by JSerFeng** [comment]
Done

**Review by kdy1 — APPROVED** [review]
Thank you!

---

swc-bump:
 - swc_ecma_transforms_bases

**Comment by kdy1** [comment]
Please do not rebase/force push

**Comment by JSerFeng** [comment]
Sry, what should I do

**Comment by kdy1** [comment]
It's all done, and @swc-bot will publish crates and rebase automatically.

**Pull request merged**
