### PR TITLE
fix(html/minifier): html minifier perf + benches

### PR DESCRIPTION
**Pull request by alexander-akait**
**Description:**

Improve perf + memory usage + benches + found more places for future improvements (will be in other PRs) + all HTML and SVG tags (will be useful for CSS parser too, because selectors can be `a, strong, div { color: red; }`)

**BREAKING CHANGE:**

No

**Related issue (if exists):**

No

### CODE REVIEW

**Review by kdy1 — APPROVED** [review]
Thanks!

---
swc-bump:
 - swc_atoms

**Review by kdy1 — CHANGES_REQUESTED** [review]
Oh CI failed.
Also, can you run `./scripts/sort.sh` from `swc_atoms`?

**Comment by alexander-akait** [comment]
Yeah, WIP on this

**Comment by alexander-akait** [comment]
@kdy1 Fixed and rebased

**Review by kdy1 — APPROVED** [review]
Thannks!

---
swc-bump:
 - swc_atoms

**Pull request merged**
