### PR TITLE
Fix missing musl config in package.json

### PR DESCRIPTION
**Pull request by Brooooooklyn**
I'm fixing https://github.com/napi-rs/napi-rs/issues/174, we can testing a alpha version after it's fixed

### CODE REVIEW

**Comment by kdy1** [comment]
@Brooooooklyn Is it done? I mean, is it ok to merge this?

**Comment by Brooooooklyn** [comment]
@kdy1 let's create a new alpha tag in this branch and see if the new `napi-rs` cli worked.

**Comment by kdy1** [comment]
I tried it, but seems like I can't tag on your fork.

**Comment by Brooooooklyn** [comment]
> I tried it, but seems like I can't tag on your fork.

So could you add me as collaborate in this project? So I can push branch to `swc-project/swc`

**Comment by kdy1** [comment]
Did it

**Comment by Brooooooklyn** [comment]
https://github.com/swc-project/swc/pull/1074

**Pull request closed without merging**
