### PR TITLE
fix(es/react): Fix location for `$RefreshSig$` injection

### PR DESCRIPTION
**Pull request by kdy1**
**Description:**

This PR fixes HMR.

**Related issue:**

### CODE REVIEW

**Comment by kdy1** [comment]
@Austaras @ForsakenHarmony Can you review this PR? I'm not 100% sure if this change is correct.

**Review by kdy1 — COMMENTED** [review]
swc-bump:
 - swc_ecma_transforms_react

**Comment by Austaras** [comment]
I don't know if this change is wrong or right but the original output is identical to official react-refresh babel plugin.

**Comment by ForsakenHarmony** [comment]
yes seems the babel plugin does it the same way, maybe defining/aliasing the function in the root, but calling inside the wrapped function would work, I think swc is handling this correctly

**Comment by kdy1** [comment]
Thank you!

**Pull request closed without merging**
