### PR TITLE
feat(html/minifier): minify conditional comments

### PR DESCRIPTION
**Pull request by alexander-akait**
**Description:**

Minify legacy conditional comments + option (true by default)

**BREAKING CHANGE:**

Yes

**Related issue (if exists):**

No

### CODE REVIEW

**Review by kdy1 — APPROVED** [review]
Thank you!

---

swc-bump:
 - swc_html_minifier

**Comment by alexander-akait** [comment]
@kdy1 Rebased

**Comment by alexander-akait** [comment]
@kdy1 fixed and done

**Review by kdy1 — APPROVED** [review]
Thank you!

---

swc-bump:
 - swc_html_minifier

**Pull request merged**
