### PR TITLE
fix(es/minifier): Abort sequential inliner on unresolved reference

### LINKED ISSUE #7749: Minify changes the order of statements
### Describe the bug

The input code below, visit function accesses variable depth, however after minified, the depth becomes 0 when visit gets invoked

### Input code

```typescript
let depth = 0;

function foo(n) {
  depth += 1;
  let k = visit(n);
  depth -= 1;
  return k;
}

blackbox(foo)
```

### Config

```json
{
  "jsc": {
    "externalHelpers": true,
    "parser": {
      "tsx": true,
      "syntax": "typescript",
    },
    "target": "es2020",
    "minify": {
      "compress": {}
    },
  },
}
```

### Playground link

https://play.swc.rs/?version=1.3.72&code=H4sIAAAAAAAAA8tJLVFISS0oyVCwVTCw5uJKK81LLsnMz1NIy8%2FXyNNUqOZSgMpr2yoYWgN5OUAd2UDVZZnFmSVAJdZwFbpQFUWpJaVFeQrZ1ly1XFxJOYnJ2Un5FRpAAzUBjCI5XG4AAAA%3D&config=H4sIAAAAAAAAA32US27jMAxA93OKwOsuii7nAEVvISgW5agji4JIJTGK3L2UbaSdhPYmcPj4Eb9ffw6H7pP67u%2FhSz7lD1wZSrLxA2KGQgK4VHhZYLaFoNyVRcJ0%2FU9FRDQltk3a8ZSB%2BhIydwu9rX7YlgG4qQC9vb69rrgbQwp%2B%2Bu2%2FxzEXIPolE6mY1xESN7G3ke7BZ1bwQg%2BPEvkRMYJNO8RYMiExDEvej457jNFmAnO2RfHSXmpLINRCNFgZnMkFs8qTCxxQCq9QB9aZHh0oKBToOZxBM5NYYpZI0lPymbGDYx2GuacP1nC2sVpWYsJ1bom8VvF6wkBsfE1aCRe4UYMFrsV9tAzeFOBa0rPdJ4a00ZN%2FAFKBaImSHUHzO2t4macta79rGZKXkeVJ4RHVLBMMUlQTglcq2yoDhYPWzQKu9tAq22vPWfFG%2BSg4MOC9zIrimi6B%2B5MWtG0wegVIf63XpmoB5r6FG7wtxA5%2BlyxZH7BVY7R82qY0jUeMOwFG4BO6HQVpBeM2LnIlrnmb1%2BRARgOcqlJpBs9HQBaA0cT5Nj7NhqyHeDRDxOPPmVgVbj%2F3VX5u3%2Bzl52fYBQAA

### Expected behavior

depth += 1;
let k = visit(n);
depth -= 1;
return k

### Actual behavior

return depth += 1, depth -= 1, visit(n);

### Version

1.3.72

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by kdy1**
**Description:**

**Related issue:**

 - Closes #7749

### CODE REVIEW

**Review by kdy1 — COMMENTED** [review]
swc-bump:
 - swc_ecma_minifier

**Review by kdy1 — COMMENTED** [review]
swc-bump:
 - swc_ecma_usage_analyzer

**Comment by kdy1** [comment]
@Austaras Can you take a look? Do you have any idea for improvement?

**Comment by Austaras** [comment]
The problem is very difficult to find a proper solution. Current solution is wrong consider following code
```js
let depth = 0;

export function visit() {
    console.log(depth)
}

function foo(n) {
  depth += 1;
  let k = visit(n);
  depth -= 1;
  return k;
}

blackbox(foo)
```

**Comment by JSerFeng** [comment]
```js
let depth = 0;

export function visit() {
    console.log(!depth) // not expected

    // console.log(depth) expected
}

function foo(n) {
  depth += 1;
  let k = visit(n);
  depth -= 1;
  return k;
}

blackbox(foo)
```

Unary expr access not expected, don't know if there are more edge cases

**Comment by Austaras** [comment]
> ```js
> let depth = 0;
> 
> export function visit() {
>     console.log(!depth) // not expected
> 
>     // console.log(depth) expected
> }
> 
> function foo(n) {
>   depth += 1;
>   let k = visit(n);
>   depth -= 1;
>   return k;
> }
> 
> blackbox(foo)
> ```
> 
> Unary expr access not expected, don't know if there are more edge cases

What unexpected?

**Comment by JSerFeng** [comment]
> What unexpected?

Acess depth directly (console.log), the output code is expected.

Acess bang depth, the output code is unexpected

**Comment by Austaras** [comment]
> > What unexpected?
> 
> Acess depth directly (console.log), the output code is expected.
> 
> Acess bang depth, the output code is unexpected

Can you provide detailed error log? It seems to work fine in playground, other than issue #7749

**Comment by JSerFeng** [comment]
image
image

[Playground](https://play.swc.rs/?version=1.3.72&code=H4sIAAAAAAAAAz2NwQoCMQxE7%2FmKHFtE0XPZj3FrVktDsnSzsiD%2Bu9HKzm3gzRsmwxvN9sABzwmAtlmb4bRKtqKCz7IUCxFfgJ6ssijTifUefqsIb4AdnlSDdLY7DwNekjf2l%2BoP3SYx7cTxTzSytQnW9BWOfM111C24MH4AbgLFMqIAAAA%3D&config=H4sIAAAAAAAAA32US27jMAxA93OKwOsuii7nAEVvISgW5agji4JIJTGK3L2UbaSdhPYmcPj4Eb9ffw6H7pP67u%2FhSz7lD1wZSrLxA2KGQgK4VHhZYLaFoNyVRcJ0%2FU9FRDQltk3a8ZSB%2BhIydwu9rX7YlgG4qQC9vb69rrgbQwp%2B%2Bu2%2FxzEXIPolE6mY1xESN7G3ke7BZ1bwQg%2BPEvkRMYJNO8RYMiExDEvej457jNFmAnO2RfHSXmpLINRCNFgZnMkFs8qTCxxQCq9QB9aZHh0oKBToOZxBM5NYYpZI0lPymbGDYx2GuacP1nC2sVrWLOE690Seq8ATBmLja9JquMCNIixwre6jZfCmANeSnu0%2BMaSNpvwDkBJES5TsCJrfWcPLQG1Z%2B13LkLzMLE8Kj6hmmWCQqpoQvNLOVhkoHLR2FnC1h1bZXnvOijfKR8GBAe9lWBTXdAncn7SgbYXRK0D6a702HAsw9zXc4G0jdvC7ZMn6gK0ao%2BXTNqVpPGLcCTACn9DtKEgrGLdxkTNxzdu8JgcyGuBUlUozeL4CsgCMJs7H8Wk2ZD3EoxkiHu1PbqvG7efCys%2FtG4NxyujaBQAA)

**Origin issue**: `visit` cannot be analyzed as it is from global, so dont know if it has effects.

**The "unexpected" I meant here**: 
`console.log(depth)`, the depth is used in `visit`, so the output remains the right order.

`console.log(!depth)`, the depth is used in `visit`, however the output is wrong.

**Comment by Austaras** [comment]
It's the same issue, but that case may also lead to more optimization as well.

**Pull request closed without merging**
