### PR TITLE
fix(swc-helpers): Add `src/*.mjs` entry back

### PR DESCRIPTION
**Pull request by magic-akari**
**Description:**

**Related issue:**

 - https://github.com/vercel/next.js/issues/48593

### CODE REVIEW

**Comment by magic-akari** [comment]
Another question: Should we add the old cjs entry `lib` as well?

**Comment by kdy1** [comment]
I don't think we need `lib`, and thank you so much!

**Comment by kdy1** [comment]
I'll close the issue with update PR (for `@swc/helpers`) towards next.js

**Review by kdy1 — APPROVED** [review]
swc-bump:
 - dbg-swc

**Pull request merged**
