### PR TITLE
Extension for jest

### LINKED ISSUE #1048: Extension packages with hidden option.
`@swc-node/jest` seems like a good idea and I think such support for some libraries worth it.

But supporting library means a maintenance hazard. What should happen if version of a library is bumped, or abandoned?
It will require bumping major version of swc, which is not a good idea.

So I think the hidden option, intended to be used only by packages in the `@swc` namespace, can be a solution.

### PR DESCRIPTION
**Pull request by kdy1**
cc @Brooooooklyn 
Because definitions of ast nodes change over time, I think this is the easiest way for end-users.
(TypeScript introduces new feature, ecmascript spec evolves)

---

Closes #1048.

### CODE REVIEW

**Comment by Brooooooklyn** [comment]
Just a note, `ts-jest` has added `path-mapping` transformer plugin for `jest` users: https://github.com/kulshekhar/ts-jest/blob/master/src/transformers/path-mapping.ts. 
We should also implement it if `{ hidden: { jest: true } }`.

**Comment by kdy1** [comment]
Hmm... I looked at it, but it seems like cjson parser is required.
I'll make `@swc/jest` faster alternative for babel-jest and improve it over time.

**Comment by bartlomieju** [comment]
FYI @dsherret wrote [`jsonc-parser`](https://crates.io/crates/jsonc-parser) which we use successfully in Deno

**Comment by kdy1** [comment]
@bartlomieju Thanks! I think I can add support for path soon.

**Comment by Brooooooklyn** [comment]
So is there any opportunity to have an independent `tsconfig.json` parse which be shared for `deno` and `swc`?

**Comment by bartlomieju** [comment]
> So is there any opportunity to have an independent `tsconfig.json` parse which be shared for `deno` and `swc`?
> 
> Seems like deno already have one? @bartlomieju

@Brooooooklyn the actual parsing of `tsconfig.json` is just a few lines - in Deno in process that config to exclude a lot of settings that we ignore.

**Pull request merged**
