### PR TITLE
feat(es/lint): no-restricted-syntax rule implementation

### PR DESCRIPTION
**Pull request by ArturAralin**
**Description:**
no-restricted-syntax rule implementation.

This implementation has basic support for airbnb styles compatibility https://github.com/airbnb/javascript/blob/master/packages/eslint-config-airbnb-base/rules/style.js#L333

**BREAKING CHANGE:**
No

### CODE REVIEW

**Review by kdy1 — DISMISSED** [review]
Thanks!

swc-bump:
 - swc_ecma_lints

**Comment by kdy1** [comment]
Can you run `UPDATE=1 cargo test` on the swc crate?

**Comment by kdy1** [comment]
Hmm... I checkout this PR locally using `gh` and it fails.

**Comment by ArturAralin** [comment]
Ok. I'll receck it more attentive

**Review by kdy1 — APPROVED** [review]
LGTM. Thanks!

---

swc-bump:
 - swc_ecma_lints

**Comment by kdy1** [comment]
Oh, build is failing.
Can you fix it?

**Comment by ArturAralin** [comment]
Yes. Checking now

**Review by kdy1 — APPROVED** [review]

**Pull request merged**
