### PR TITLE
docs(readme): Update `README.md`

### PR DESCRIPTION
**Pull request by cjeonguk**
**Description:**

- Remove an unused badge
- Add links for release badge and node version badge
- Update the license description
- Add a link for LICENSE
- Format indentation size (2 spaces same as html)
- Remove unnecessary links
- Change `alt` of swc logo from babel to swc

of `README.md`.

**BREAKING CHANGE:**

**Related issue (if exists):**

 - Closes https://github.com/swc-project/swc/issues/5957

### CODE REVIEW

**Comment by kdy1** [comment]
Can you sign the CLA?

**Review by kdy1 — APPROVED** [review]
Thanks!

---

swc-bump:
 - dbg-swc

**Comment by kdy1** [comment]
Please don't rebase by yourself

**Comment by cjeonguk** [comment]
Oops sorry my mistake.

**Pull request merged**
