### PR TITLE
feat(es/preset-env): Upgrade `browserslist-rs`

### PR DESCRIPTION
**Pull request by g-plane**

### CODE REVIEW

**Review by kdy1 — APPROVED** [review]
LGTM, thanks!

**Comment by g-plane** [comment]
Licenses check failed. I'm try to address this.

**Comment by g-plane** [comment]
"BSD-2-Clause-Patent" should be OK: https://writing.kemitchell.com/2019/11/07/BSD-Patents.html .

**Comment by kdy1** [comment]
Can you add it to allowlist?

**Comment by g-plane** [comment]
Yes, I added it. See the latest commit.

**Review by kdy1 — APPROVED** [review]
Thanks!

**Pull request merged**
