### PR TITLE
feat(es/compat): transform numeric separator

### PR DESCRIPTION
**Pull request by magic-akari**
**Description:**

**BREAKING CHANGE:**

**Related issue (if exists):**
- #4724

### CODE REVIEW

**Comment by kdy1** [comment]
I already fixed it and published a new version.

**Comment by magic-akari** [comment]
> I already fixed it and published a new version.

I prefer to fix it in `es/compat` for a few reasons.

- leave it without change when target >= es2021
- minimal change. Just remove `_` and keep the original scientific notation, hexadecimal, etc.

**Comment by kdy1** [comment]
Visitors are too costly for this case.
We can handle it in codegen, but not with visitor

**Comment by kdy1** [comment]
Everything you mentioned it possible with codegen.
Visitor is really a waste

**Pull request closed without merging**
