### PR TITLE
feat(es/minifier): Drop pure `new` calls

### PR DESCRIPTION
**Pull request by kdy1**
**Description:**

**Related issue (if exists):**

### CODE REVIEW

**Comment by Austaras** [comment]
This should be under `unsafe` flag -- as we cannot know if global constructor is modified

**Comment by kdy1** [comment]
I'm not sure about it.

I think opt-out is fine in cases like this

**Comment by Austaras** [comment]
Well `terser` put them under `unsafe` and disable it by default -- but IMO that's a bad design. `unsafe` sounds too scary, but today few people actually modify global object.

**Comment by kdy1** [comment]
It sounds scary, but it's fine for more than 99.99% of users

**Comment by kdy1** [comment]
Or `untouched_globals`
I don't have a good solid idea about the name

**Comment by Austaras** [comment]
Yeah enable it by default is good, but unsafe by default sounds a bit awkward... what about `origin_globals` or `pristine_globals`

**Comment by kdy1** [comment]
Oh, I love `pristine_globals`

**Pull request merged**
