### PR TITLE
fix(es/ast): revert removal of `definite` in `PrivateProp`

### LINKED ISSUE #4050: Add back `definite` on `PrivateProp`
### Describe the bug

The `definite` property was removed, but it's not useless. It's useful for analysis to know if this exists or not.

https://github.com/swc-project/swc/pull/3868/files#diff-7691f705debe5b1726316e17ca0361f9fb546ef8df4a7845474514a22de8f5f4L181

cc @Austaras

### Input code

```typescript
class Test {
  #test!:string;
}
```

### Config

_No response_

### Playground link

https://www.typescriptlang.org/play?ssl=3&ssc=2&pln=1&pc=1#code/MYGwhgzhAEAqCmEAu0DeBYAUNaBiJiSAhAFzIBOAlgHYDmA3FgL5A

### Expected behavior

Should have `definite`.

### Actual behavior

_No response_

### Version

swc_ecmascript 0.134.0

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Austaras**
**Description:**

**BREAKING CHANGE:**

**Related issue (if exists):**
closes #4050

### CODE REVIEW

**Review by dsherret — APPROVED** [review]
Thanks @Austaras! FWIW, it looks good to me 🙂

**Review by kdy1 — APPROVED** [review]
Thank you!

---

swc-bump:
 - swc_ecma_ast --breaking

**Comment by Austaras** [comment]
Why isn't CI running

**Comment by kdy1** [comment]
Seems like api for starting CI had some issue, and now ci is running

**Pull request merged**
