### PR TITLE
ci: sync to latest napi workflow

### PR DESCRIPTION
**Pull request by Brooooooklyn**
https://github.com/Brooooooklyn/swc/runs/4056044169?check_suite_focus=true

### CODE REVIEW

**Review by kdy1 — APPROVED** [review]
Thanks!

**Comment by Songkeys** [comment]
This PR makes `@swc/core@1.2.106` totally break. (`1.2.105` is fine.)

After installing `@swc/core`, there's no platform-specific core binding installed. Checked on my macOS and linux x64. Please take a look.

**Comment by Brooooooklyn** [comment]
image

**Comment by Brooooooklyn** [comment]
@Songkeys I've confirmed this is because our internal npm registry is out of synced for all `optioanlDependencies` in `@swc/core`.

**Comment by Songkeys** [comment]
@Brooooooklyn  You were right. Sorry about this. This is really confusing... Could we make this error behaviour clearer?

**Pull request merged**
