### PR TITLE
fix(es/hygiene): Fix renaming bugs

### LINKED ISSUE #3213: Variable being renamed unnecessarily is breaking code
### Describe the bug

Running the function `f()` from the input code, causes the console to log `"original string"`, whereas running the one outputted by the compiler results in `"new string"` being logged.

### Input code

```typescript
function f() {
  var value$2 = 'original string';
  if (true) {
    var value$21 = 'new string'
    console.log(value$2)
  }
  [].map(function x(_) {
    var value$2; // this causes the previous value$2 to become value$21
    return value$2
  })
}
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "ecmascript",
      "jsx": false
    },
    "target": "es5",
    "loose": true,
    "minify": {
      "compress": false,
      "mangle": false
    },
    "keepClassNames": true
  },
  "module": {
    "type": "es6"
  },
  "minify": false,
  "isModule": true
}
```

### Playground link

https://play.swc.rs/?version=1.2.124&code=H4sIAAAAAAAAA21OzQqCQBC%2B%2BxRzCFwvSl2lJ4mIbZm1gXVG9keD8N1bLYWgwwfDfL82sYkkDFZV8CoARu0zXMLDCc5QiqeOWDsI0RN3ZZslZEFFn%2FBj%2BLEcFw%2FjtMlX3ggHcVg76dRXV2Vizrhc614Pym4rnur2J7WFpoH4oABGp4Ah3wiDx5EkhX1tFLijkR73MWuOx5g8b7%2Bltyrm4g21Prmx%2BAAAAA%3D%3D&config=H4sIAAAAAAAAA0WNOw7DIBBE77I1bVLQpk7usCJrC4efGCwFId894CC5W828edtogyHdKHGG5HGhhsJf0iTGM0y2qZDqWI8WdpBDUeG8ShkIbr1zMUJIl7yLIm%2BDXeoQmehTFmDuesVhdXJpPiLp4Rh4sRf8BT328b0PrFGpSc4vdzou87RZPCd47n5%2FjK7bygAAAA%3D%3D

### Expected behavior

I think that there are two problems:

1. The compiler shouldn't have renamed the first `value$2` to `value$21` in the first place. It does that because of the second declaration inside `function x(_)`, but it's not necessary since variables are scoped to its closures, so the shadowing is valid.
2. The compiler should notice that the `var value$21` declaration inside the `if` block clashes with the compiler's renaming of `value$2` to `value$21`, so it should probably rename it to something else (or not at all, as mentioned in the previous point.). Notice that the bug is gone if the code is taken out off the `if` block.

### Actual behavior

_No response_

### Version

1.2.124

### Additional context

This might seem like an unrealistic example, but it actually broke our application written in [Rescript](https://rescript-lang.org/), whose compiler outputs a lot of variables suffixed with numbers.

Update: Looks like this only started happening on `v1.2.102`

### LINKED ISSUE #3823: Incorrect output when 2+ vars are named with a shared prefix and one var name is re-used across scopes
### Describe the bug

When there are variables whose names share the same prefix and where one variable name is shared between an inner and outer scope.

Reproduced here - https://github.com/bnoguchi/swc-bug-repro-1

To reproduce:

```bash
git clone https://github.com/bnoguchi/swc-bug-repro-1.git
npm i
npx swc index.js -o out.js
```

Then execute index.js and out.js, and notice that you have 

```bash
$ node index.js
{ aaa: 2, bbb: 3 }
```

```
$ node out.js
{ aaa: 'bbb', bbb: 3 }
```

If swc were working correctly, then we would expect to get the same result.
However, we get different results because `out.js` ends up conflating 2
variables.

### Input code

The contents of index.js:

```typescript
'use strict';

function print() {
  var value$4 = 2;
  var value$41 = value$4 + 100;
  var c = 1;
  if (true) {
    var value$42 = "bbb";
    if (value$42 === "bbb") c = 3;
  }

  [0, 1].map(function (value) {
    var value$4 = 2;
    var x = value ? value$4 : "";
    return x;
  });
  return {aaa: value$4, bbb: c};
}

console.log(print());
```

### Config

```json
/* empty */
```

### Playground link

https://play.swc.rs/?version=1.2.146&code=H4sIAAAAAAAAA21Q3QqDIBS%2B9ykOMUhZRG67SmIPMnZhYkNoGqYjiN599mMj2IUH%2FH7O93FS30vonVXCpQyhxmvhlNHQWaUdJjAigA%2B34bVenm5QwYUdIRqwyJ6BFkXkRSDo%2FFENYGe9XLcdzJegSeq6TtjCzMofU20cWVZdZ8mEwngUGdBn%2FuYd3vuutj8JsfEKDrEs3HdBCckWb6XzVsOwJJF5bsjIOS%2BjIYNQqgQxMRTqCKN708q8NS%2B8HY2wL%2BJYBH1WAQAA&config=H4sIAAAAAAAAA0WMSwrDMAxE76K1t93kDj2EcJXg4B8aBWqM714bUrKSmPdmOp3wtHWqrBBdH1o2%2FtJG4hPDa6hGbmoz2jlChiNjPcSWgtdksRTITR2lkMPe1pIvqaoAD%2BJ8xL855lAqn2sFnazVeVcllXyCxjN0lwPet216yfgBCKaI9boAAAA%3D

### Expected behavior

```javascript
'use strict';
function print() {
    var value$4 = 2;
    var value$41 = value$4 + 100;
    var c = 1;
    if (true) {
        var value$42 = "bbb";
        if (value$42 === "bbb") c = 3;
    }
    [
        0,
        1
    ].map(function(value) {
        var value$4 = 2;
        var x = value ? value$4 : "";
        return x;
    });
    return {
        aaa: value$4,
        bbb: c
    };
}
console.log(print());


//# sourceMappingURL=out.js.map
```

### Actual behavior

Notice how `value$4` and `value$42` from index.js are combined into one var in
out.js named `value$42`, instead of being kept as separate variables.

```javascript
'use strict';
function print() {
    var value$42 = 2;
    var value$41 = value$42 + 100;
    var c = 1;
    if (true) {
        var value$42 = "bbb";
        if (value$42 === "bbb") c = 3;
    }
    [
        0,
        1
    ].map(function(value) {
        var value$4 = 2;
        var x = value ? value$4 : "";
        return x;
    });
    return {
        aaa: value$42,
        bbb: c
    };
}
console.log(print());


//# sourceMappingURL=out.js.map
```

### Version

@swc/cli: 0.1.55 ; @swc/core: 1.2.147

### Clue 1

The issue seems to be related to the re-use of the var name `value$4` inside the Array.map callback. If we remove that callback or if we rename the var in the callback from `value$4` to `value$9`, then the issue disappears.

For example, the issue disappears if we change from:

```javascript
  [0, 1].map(function (value) {
    var value$4 = 2;
    var x = value ? value$4 : "";
    return x;
  });
```

to

```javascript
  [0, 1].map(function (value) {
    var value$9 = 2;
    var x = value ? value$9 : "";
    return x;
  });
```

### Clue 2

The issue seems to be related to the shared prefixes of the var names `value$4`, `value$41`, `value$42`. If we change `var value$41 = value$4 + 100;` to `var value$1 = value$4 + 100;`, then the issue disappears.

For example, the issue disappears if we change index.js to:

```javascript
'use strict';

function print() {
  var value$1 = 2;
  var value$2 = value$1 + 100;
  var c = 1;
  if (true) {
    var value$3 = "bbb";
    if (value$3 === "bbb") c = 3;
  }

  [0, 1].map(function (value) {
    var value$1 = 2;
    var x = value ? value$1 : "";
    return x;
  });
  return {aaa: value$1, bbb: c};
}

console.log(print());
```

### Clue 3

The issue seems to only occur when one of the variables that share a name prefix is declared and used inside of a block.

For example, the issue disappears if we change from:

```javascript
  var c = 1;
  if (true) {
    var value$42 = "bbb";
    if (value$42 === "bbb") c = 3;
  }
```

to 

```javascript
  var c = 1;
  var value$42 = "bbb";
  if (value$42 === "bbb") c = 3;
```

### PR DESCRIPTION
**Pull request by kdy1**
**Description:**

We 'reserve' all used symbols, so it cannnot result in an error

**Related issue (if exists):**

 - Closes #3213
 - Closes #3823

### CODE REVIEW

**Review by kdy1 — COMMENTED** [review]
swc-bump:
 - swc_ecma_transforms_base

**Comment by jdalton** [comment]
This is still happening in 1.2.164.

It's happening with consts defined outside a try-catch and used inside a try-catch

**Comment by kdy1** [comment]
@jdalton Please file a new issue

**Comment by jdalton** [comment]
Input:
```js
const a = b;
try {
  foo(a);
} catch {}
```
Output:
```js
const a = b;
try {
  var a;
  a = a;
  foo(a);
} catch {}
```

**Comment by jdalton** [comment]
@kdy1 Done! https://github.com/swc-project/swc/issues/4294 Thank you!

**Pull request merged**
