### PR TITLE
feat(es/minifier): Minify `"undefined" == typeof x` to `"u" < typeof x`

### PR DESCRIPTION
**Pull request by magic-akari**
**Description:**

The only thing I'm worried about is IE returning "unknown" for some objects.
https://stackoverflow.com/questions/10982739/typeof-returning-unknown-in-ie

**BREAKING CHANGE:**

**Related issue (if exists):**

### CODE REVIEW

**Comment by kdy1** [comment]
🤣 I never heard about `unknown`

**Review by kdy1 — APPROVED** [review]

**Review by jridgewell — APPROVED** [review]
I think this technically works, but I'd be worried about the runtime performance costs. Every engine has a static optimization for `typeof == "undefined"` (or reversed order), but I don't know if any implement this for `<`.

**Review by kdy1 — CHANGES_REQUESTED** [review]
This may make runtime performance worse.

https://source.chromium.org/chromium/chromium/src/+/main:v8/test/mjsunit/optimized-typeof.js?q=typeof%20undefined

Let's see if it's possible to get this optimized

**Comment by magic-akari** [comment]
I supposed it woulld be faster, since it's a common tricks in c/c++.

In `'undefined' > 'u'`, only comparing the first letter is sufficient to obtain the result.
In `'undefined' == 'undefined'`, typically the KMP algorithm needs to be executed, but even with the optimal algorithm, it still requires comparing 9 times to obtain the result.

If `typeof x` can be converted to compare directly with `x` and `void 0`, it should be faster, just like what we did in crates/swc_ecma_minifier/src/compress/optimize/bools.rs.

However, in actual speed tests, the results may fluctuate. So I speculate that its impact on speed is not significant.

image

[perf.link](https://perf.link/#eyJpZCI6Indsd2tqbnBzdjVqIiwidGl0bGUiOiJDb21wYXJlIHR5cGVvZiIsImJlZm9yZSI6ImNvbnN0IHggPSAxIiwidGVzdHMiOlt7Im5hbWUiOiJjb21wYXJlIGRpcmVjdGx5IiwiY29kZSI6InggPT09IHZvaWQgMCIsInJ1bnMiOls0NzY0MDAwLDM0MDIwMDAsMTA3NDcwMDAsMTQ0MjAwMDAsNjUxNjAwMCwxMTI0MTAwMCwzMjY1MDAwLDMzMzUwMDAsMTY5NTAwMCw0MzgxMDAwLDUzNTcwMDAsMTczNzEwMDAsMjUzNDAwMCwxODQzODAwMCw1NDI5MDAwLDIwNDcyMDAwLDEyMDY4MDAwLDg0NzkwMDAsMTkzNTAwMCwxNjk1MDAwLDUzODAwMDAsMTUwOTgwMDAsMjMwMDAsMTg2MDkwMDAsMjIwMDkwMDAsMTQ1NzgwMDAsMTYyOTgwMDAsMTI2MzAwMDAsMjM2MTAwMCwxNDQ2MDAwLDIxODIwMDAsMTI2MjkwMDAsMTY5NTAwMCwyMDYyMzAwMCwxMDkxMDAwLDE5ODA5MDAwLDE0MzcwMDAsMjEyMjIwMDAsMjY0NzAwMCwxNzM1MTAwMCwyNTM0MDAwLDE2OTA3MDAwLDc1NjEwMDAsODg3MTAwMCwxMjk2NzAwMCwxNjUzMDAwMCwxODIyMjAwMCwxODQxMzAwMCwxNzAzODAwMCwyMjQyMTAwMCwxMjM2NDAwMCw0MjI0MDAwLDE3NjgxMDAwLDg5MzMwMDAsMzg3OTAwMCw0NDc0MDAwLDE2OTUwMDAsMTY5NTAwMCwxNDI3OTAwMCwxNjcwMDAsMTAzMDIwMDAsMTkyNjgwMDAsMTIzNjMwMDAsNjU4MDAwMCwxMzE0MTAwMCwyMzAwMCw0OTQ5MDAwLDYxNjAwMDAsNDIwOTAwMCwxNjk1MDAwLDUzMTAwMCwyMDQ4NDAwMCw2MDcxMDAwLDE0NjEwMDAsMTIyNTgwMDAsMjA5MTkwMDAsMTg2MTAwMDAsMTc5MTMwMDAsNzczODAwMCwxMzg5NTAwMCw0NTA3MDAwLDEwMDEwMDAwLDkxMzIwMDAsMjA3OTkwMDAsMTc5NzAwMCwxOTEwNDAwMCwxNzI5NjAwMCwxMjYzNTAwMCwzOTQ3MDAwLDQ1MTQwMDAsNDczNjAwMCwxMDkzNzAwMCwxOTgzMDAwLDExNjc0MDAwLDE5NDYwMDAsMTE3OTcwMDAsOTY2MTAwMCw0NjYwMDAsMTY0NDAwMCwxNjAyMDAwXSwib3BzIjo5MzYyNzQwfSx7Im5hbWUiOiJ0eXBlb2YgMSIsImNvZGUiOiJ0eXBlb2YgeCA%2BICd1JyIsInJ1bnMiOlsyMDU2MDAwLDE1NDQwMDAsMzMzMDAwMCwxMDc0MTAwMCw0ODU1MDAwLDkxNTAwMDAsMjcxMzAwMCwxOTc1MDAwMCwxNjA3MjAwMCwxNTQ0MDAwLDUwMDEwMDAsMTUyMTMwMDAsMjIzMzAwMCwxMjU5ODAwMCw1MDEzMDAwLDE4MDAwMDAwLDEwNjcxMDAwLDgxNjQwMDAsNDA4OTAwMCwxNjk5MTAwMCw0MzQwMDAwLDEyMzk2MDAwLDE4NTM2MDAwLDEzMzk4MDAwLDE4MDk3MDAwLDI0NzkwMDAsMTAzNjAwMCwxMTU5MTAwMCwxODkzODAwMCwxNjc2NjAwMCw5MTMwMDAsOTQ2ODAwMCwxOTQ5OTAwMCwxNzYwNjAwMCwxODkyOTAwMCw1NzcwMDAwLDE2MjEzMDAwLDE4MjUzMDAwLDE5MzAwMDAwLDE2NDMwMDAwLDE3OTAxMDAwLDE0ODU2MDAwLDY1NjAwMDAsODE4NzAwMCwxMjA5MTAwMCwxNDM3MjAwMCwxNDU5OTAwMCwxNjk4MTAwMCwxMzM0NzAwMCwxOTE4OTAwMCw5MzY0MDAwLDE5NTEwMDAsMTQ4MjkwMDAsNzM4NjAwMCw2MzcwMDAsMTU0NDAwMCwxNzcxNDAwMCwxODIxMTAwMCwxMjE0NzAwMCwxNjAzNTAwMCw0MDYzMDAwLDE2MzIwMDAwLDEwOTQxMDAwLDE1MDMwMDAsOTUwODAwMCwxNjQwOTAwMCw0NDM5MDAwLDI4NjIwMDAsMTAyNjAwMCwxMTk2MTAwMCw0MTYwMDAsMTM4NjAwMDAsNDg1MTAwMCwxOTE0OTAwMCwxMjA0MTAwMCwxNzc4OTAwMCwxNzUxODAwMCwxMzI1OTAwMCw2MTI5MDAwLDEwNzY4MDAwLDE5MDM0MDAwLDg1OTMwMDAsODIyMzAwMCwxNzg0MjAwMCwxODY0NTAwMCw1MjAwMDAwLDE1NjUyMDAwLDgxOTQwMDAsNjQ4MTAwMCwxMjcwMDAwLDE4NzIwMDAsOTU0MTAwMCwxOTA1ODAwMCw3NTUzMDAwLDE4NTA2MDAwLDYyOTYwMDAsODQ3MzAwMCw1NDEwMDAwLDI3NzEwMDAsMTIwODcwMDBdLCJvcHMiOjEwNjMxMDAwfSx7Im5hbWUiOiJ0eXBlb2YgMiIsImNvZGUiOiJ0eXBlb2YgeCA9PSBcInVuZGVmaW5lZFwiIiwicnVucyI6WzI1MjEwMDAsNzc0ODAwMCwxOTQyMDAwLDY2NzgwMDAsMTY2NjAwMCw0MDkxMDAwLDI5MzcwMDAsMTY5ODAwMDAsMTAyNDYwMDAsMTQ1MDAwLDYzMjcwMDAsOTE2OTAwMCwyNTQyMDAwLDk0OTAwMDAsNTE5MjAwMCwxMzE4MzAwMCwxMDQ4ODAwMCw1NzE2MDAwLDQxNDUwMDAsMTA0ODEwMDAsNTA4NDAwMCw3NjYwMDAwLDE0NTQ0MDAwLDEzMzQ1MDAwLDEwMjIyMDAwLDE1MDQ0MDAwLDE2NjYwMDAsMTAxMDQwMDAsMTIxNTIwMDAsMTA5ODkwMDAsMTk3NzIwMDAsNTc3OTAwMCwxNTM0OTAwMCw4MzgwMDAsMTU3NDIwMDAsNDQzODAwMCwxMTU0MDAwMCwxNjUxNTAwMCwxMTcwMjAwMCwxNTE0OTAwMCwxMTE5NTAwMCwxMzgzOTAwMCw0OTA4MDAwLDg3NDAwMDAsMTIzNjQwMDAsMTQzODMwMDAsMTE2NjEwMDAsMTI1MzkwMDAsMTE2NDMwMDAsMTMxMjEwMDAsMjE5ODAwMCwxMjY4ODAwMCwxMzA4NDAwMCw4Njk1MDAwLDEzOTg0MDAwLDE0MTMzMDAwLDE1NTY5MDAwLDE0MTE3MDAwLDExNzQxMDAwLDExMDMwMDAwLDI3NjYwMDAsMTMwNjgwMDAsMTU5ODEwMDAsMTcxNDIwMDAsMzMxNDAwMCwxMTE4NDAwMCwyMzg4MDAwLDE3NTM4MDAwLDE4Nzg1MDAwLDEwMzg2MDAwLDE4MzM1MDAwLDEwMDE5MDAwLDM1ODIwMDAsNzY3MjAwMCwxMDI4MTAwMCw3NjU0MDAwLDEyOTMyMDAwLDEwNjY5MDAwLDU0MTQwMDAsNzI0NDAwMCwxMzU5NTAwMCw1MDg4MDAwLDkxMTAwMDAsMTQwMTQwMDAsMTk1NTAwMCwyMDYwNDAwMCwxNjIxNjAwMCw2MzAwMDAwLDUyMzQwMDAsNDY2NTAwMCwxNjc1MzAwMCw1NjE1MDAwLDEzMDAyMDAwLDQxODAwMDAsMTQ4NDUwMDAsNDc4OTAwMCwxOTcyMjAwMCw1NjMyMDAwLDE2NjYwMDAsMTE0MTQwMDBdLCJvcHMiOjk4MTcwNjB9XSwidXBkYXRlZCI6IjIwMjMtMTAtMjFUMDM6MDY6MzEuMTU4WiJ9)

**Comment by kdy1** [comment]
I'll profile runtime performance later today

**Comment by zloirock** [comment]
@magic-akari it makes no sense to test the performance of something that can be removed as a dead code since it hasn't observable side effects.

image

---

image

**Pull request closed without merging**
