### PR TITLE
swc(html/parser): fix adoption agency algorithm

### PR DESCRIPTION
**Pull request by alexander-akait**
**Description:**

Bugfix 

**BREAKING CHANGE:**

No

**Related issue (if exists):**

No

### CODE REVIEW

**Review by kdy1 — APPROVED** [review]
Thank you!

---

swc-bump:
 - swc_html_parser

**Review by kdy1 — CHANGES_REQUESTED** [review]
CI failed

**Comment by alexander-akait** [comment]
WIP on rebase

**Comment by alexander-akait** [comment]
@kdy1 Rebased, most of cross tests passed:

> test result: FAILED. 1843 passed; 217 failed; 0 ignored; 0 measured; 0 filtered out; finished in 1.57s

There that stability is already very close

**Review by kdy1 — APPROVED** [review]

**Pull request merged**
