### PR TITLE
feat: compress display

### PR DESCRIPTION
**Pull request by alexander-akait**
**Description:**

Feat - port of https://github.com/cssnano/cssnano/tree/master/packages/postcss-normalize-display-values

**BREAKING CHANGE:**

No

**Related issue (if exists):**

No

### CODE REVIEW

**Comment by kdy1** [comment]
I'll review this after rebasing :)

**Comment by alexander-akait** [comment]
@kdy1 Done :+1:

**Review by kdy1 — APPROVED** [review]
LGTM.
---

swc-bump:
 - swc_css_minifier

**Comment by kdy1** [comment]
I'll merge once the new version is published

**Pull request merged**
