### PR TITLE
fix(es/codegen): detailed control of whitespace in BinExpr

### PR DESCRIPTION
**Pull request by Austaras**
**Description:**

**BREAKING CHANGE:**

**Related issue (if exists):**

### CODE REVIEW

**Review by kdy1 — COMMENTED** [review]
image


Is this intentional?
I think `<-90` will work

**Comment by Austaras** [comment]
> will



> image
> 
> Is this intentional? I think `<-90` will work
> 
> swc-bump:
> 
>     * swc_ecma_codegen

Seems like left side is generated by this pr and right is the origin. `<-90` did work.

**Comment by kdy1** [comment]
Oh, sorry I think I made a mistake while copy pasting

**Review by kdy1 — APPROVED** [review]
Thank you!

---

swc-bump:
 - swc_ecma_codegen

**Pull request merged**
