### PR TITLE
feat(css/parser): add method to return error message

### PR DESCRIPTION
**Pull request by g-plane**
**Description:**

This can allow downstream developers to retrieve error message.

### CODE REVIEW

**Comment by alexander-akait** [comment]
I think we will need the same for HTML, because now it is copy/paste from CSS parser :+1:

**Comment by g-plane** [comment]
@alexander-akait I think it can be done in another PR.

**Comment by g-plane** [comment]
ping @kdy1 .

**Review by kdy1 — APPROVED** [review]
swc-bump:
 - swc_css_parser

**Pull request merged**
