### PR TITLE
chore(ci): Add linux arm build back

### PR DESCRIPTION
**Pull request by Brooooooklyn**
Also fixes some build infra

### CODE REVIEW

**Comment by kdy1** [comment]
I'm not sure about the reason, but Wasm CI failed

**Review by kdy1 — COMMENTED** [review]
It seems like CI is still failing

**Comment by Brooooooklyn** [comment]
@kdy1 fixed

**Review by kdy1 — APPROVED** [review]
Thank you so much!


---


swc-bump: 
 - dbg-swc

**Comment by kdy1** [comment]
It seems like the publish action is broken. https://github.com/swc-project/swc/actions/runs/7174972904/job/19538863524

`napi artifacts --dist scripts/npm` seems obsolete now?

**Pull request merged**
