### PR TITLE
fix(es/transform/compat) fix early return caused by comment above async func in object

### PR DESCRIPTION
**Pull request by UMASHIBA1**
Fix https://github.com/swc-project/swc/issues/2701
I fixed early return caused by comment above async method in object.
if something wrong, please point it out🙇‍♂️

### CODE REVIEW

**Comment by UMASHIBA1** [comment]
If I'm wrong I'm sorry. Does this PR resolved same problem...?
https://github.com/swc-project/swc/pull/2762

**Comment by kwonoj** [comment]
:oh-no: yes, it looks like aiming same issues while I tried to reuse exising span. Sorry I didn't aware if there was overlapping work.

**Review by kdy1 — APPROVED** [review]
The new code can panic if someone trolls, but rust code is required to such trolling, so it's fine IMO.

**Comment by kwonoj** [comment]
@kdy1 do you think this is still required after #2762? My impression was preserving original span would be ok.

**Comment by kwonoj** [comment]
Looks like #2758 was dupe of #2701 and I didn't realize it.

**Comment by kdy1** [comment]
@kwonoj Oh, you are right. I'll test if it works with this PR reverted.

**Comment by kdy1** [comment]
@kwonoj I'll revert this PR as it's not required.

**Comment by UMASHIBA1** [comment]
> :oh-no: yes, it looks like aiming same issues while I tried to reuse exising span. Sorry I didn't aware if there was overlapping work.

OK👍 Thank you for your great work. I'm glad the issue was solved early.

**Pull request merged**
