### PR TITLE
test(html/parser): Flatten tests to make git faster

### PR DESCRIPTION
**Pull request by kdy1**
**Description:**

This PR flattens html tests to make git faster

### CODE REVIEW

**Comment by kdy1** [comment]
Seems like html tests are quite complex.

cc @alexander-akait How can I flatten this?

Performance difference of `git status -z -u` is about 0.45 sec vs 0.4 sec

**Comment by kdy1** [comment]
File count is fine. Only directory count matters

**Comment by alexander-akait** [comment]
WIP on improvements

**Comment by kdy1** [comment]
Closing in favor of https://github.com/swc-project/swc/pull/6158

**Pull request closed without merging**
