### PR TITLE
fix(es/minifier): Don't replace parameters of IIFE if it's recursive

### PR DESCRIPTION
**Pull request by kdy1**
**Description:**

While investigating, I found that problem is not analysis of recursive functions. Instead, it was a problem of IIFE evaluator, which replaces parameters even if it's recursive.

**Related issue:**

 - Closes https://github.com/swc-project/swc/issues/5846

### CODE REVIEW

**Review by kdy1 — COMMENTED** [review]
reset ci

---

swc-bump:
 - swc_ecma_minifier

**Comment by Austaras** [comment]
I'm wondering if it's worth it to add a field in analyzer like `used_recursively`, as #5682 can also benefit from it.

**Comment by kdy1** [comment]
@Austaras What's the purpose of the field? I think adding a field is fine in general

**Comment by Austaras** [comment]
If an ident is `used_recursively`, it

1. cannot be replaced parameters with
2. cannot be drop when inline function

**Comment by kdy1** [comment]
I think it will worth

**Pull request merged**
