### PR TITLE
Fix(es/compat): escape keyword of class method's key in transpiling class metod into under ES5

### LINKED ISSUE #4482: Cannot use eval as class method name
### Describe the bug

The error Module parse failed: Binding eval in strict mode (105:28) is thrown when declaring a public function named eval

```
public eval(scope?: object): number {
        if (!this.e) {
            // ...
        }

        return this.e.evaluate(scope);
    }

```

The error thrown is then 
```
Module parse failed: Binding eval in strict mode (105:28)
File was processed with these loaders:
 * ./node_modules/swc-loader/src/index.js
You may need an additional loader to handle the result of these loaders.
|         this.c();
|     };
>     _proto1.eval = function eval(scope) {
```

### Input code

_No response_

### Config

```json
{
                    test: /\.ts(x?)$/,
                    use: 
                        {
                            loader: "swc-loader",
                            options: {
                                sync: true,
                                jsc: {
                                    parser: {
                                        syntax: "typescript",
                                        tsx: true,
                                        dynamicImport: true
                                    },
                                    loose: false,
                                    externalHelpers: true,
                                    // Requires v1.2.50 or upper and requires target to be es2016 or upper.
                                    keepClassNames: false,

                                },
                                module: {
                                    type: "commonjs",
                                    strictMode: false,
                                    lazy: true
                                }
                            }
                        }
                }
```

### Playground link

_No response_

### Expected behavior

The code should compile

### Actual behavior

The code throws an error

### Version

1.2.173

### Additional context

_No response_

### LINKED ISSUE #4774: downtranspiling of class method into ES5 can generate function declaration with invalid function name
### Describe the bug

in latest swc(v1.2.189), downtranspiling of class method into ES5 can generate function declaration with invalid function name, such as function declaration with reserved keyword function name. This causes runtime or parsing error.

### Input code

```typescript
export class Foo {
	let() {}
}
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "tsx": false
    },
    "loose": false,
    "minify": {
      "compress": false,
      "mangle": false
    }
  },
  "module": {
    "type": "es6"
  },
  "minify": false,
  "isModule": true
}
```

### Playground link

https://play.swc.rs/?version=1.2.189&code=H4sIAAAAAAAAA0utKMgvKlFIzkksLlZwy89XqObizEkt0dBUqK7lqgUAk3%2FrGh4AAAA%3D&config=H4sIAAAAAAAAA0WNSw7DIAxE7%2BI16y5yhxwCUSei4iePIxUh7l6oiLIbj%2BfNNPrA0daoWAHLVKhJ7Zc20loYTnxRMqQY1mEDuBsKOYPXaSj65I86UZdjEQael01nuJN9kDG%2Fr2m0f%2FsYYbyoPx2L89hXUOXi%2FgMhdKqapgAAAA%3D%3D

### Expected behavior

```javascript
function _classCallCheck(instance, Constructor) {
    if (!(instance instanceof Constructor)) {
        throw new TypeError("Cannot call a class as a function");
    }
}
export var Foo = function() {
    "use strict";
    function Foo() {
        _classCallCheck(this, Foo);
    }
    var _proto = Foo.prototype;
    _proto.let = function _let() {};
    return Foo;
}();
```

### Actual behavior

```javascript
function _classCallCheck(instance, Constructor) {
    if (!(instance instanceof Constructor)) {
        throw new TypeError("Cannot call a class as a function");
    }
}
export var Foo = function() {
    "use strict";
    function Foo() {
        _classCallCheck(this, Foo);
    }
    var _proto = Foo.prototype;
    _proto.let = function let() {};
    return Foo;
}();
```

### Version

1.2.189

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Shinyaigeek**
**Description:**

Fixes: #4774 

in latest swc(v1.2.189), downtranspiling of class method into ES5 can generate function declaration with invalid function name, such as function declaration with reserved keyword function name. This causes runtime or parsing error. This bug happens when swc's `set_class_methods` config is true.

I fixed this issue to escape keyword of class method's key with `escape_keywords` utility function same as `set_class_methods` is false.

**Related issue (if exists):**

 - Closes #4774 
- Closes #4482

### CODE REVIEW

**Review by kdy1 — APPROVED** [review]
Thanks!

---

swc-bump:
 - swc_ecma_transforms_compat

**Review by kdy1 — CHANGES_REQUESTED** [review]
Please run `UPDATE=1 cargo test` from `./crates/swc`
You may need to run it multiple times

**Comment by Austaras** [comment]
This closes #4482 too

**Comment by kdy1** [comment]
Thanks! I updated the PR

**Comment by Shinyaigeek** [comment]
@kdy1 I'm sorry for late response, done 👍  [811b5bf](https://github.com/swc-project/swc/pull/4775/commits/811b5bf0f124c36586ab27cf7b5934522ee1e64c)

**Review by kdy1 — APPROVED** [review]

**Pull request merged**
