### PR TITLE
fix(css/prefixer): generate prefixes for selectors using env

### PR DESCRIPTION
**Pull request by alexander-akait**
**Description:**

Generate prefixes for selectors using env

**BREAKING CHANGE:**

No

**Related issue (if exists):**

No

### CODE REVIEW

**Comment by alexander-akait** [comment]
@kdy1 rebased

**Comment by alexander-akait** [comment]
@kdy1 rebased

**Review by kdy1 — DISMISSED** [review]
Thanks!

---

swc-bump:
 - swc_css_prefixer

**Comment by alexander-akait** [comment]
@kdy1 Rebased

**Review by kdy1 — APPROVED** [review]

**Pull request merged**
