### PR TITLE
fix(es/module): Fix `jsc.paths` on Windows

### PR DESCRIPTION
**Pull request by kdy1**
**Description:**

**Related issue:**

 - Reverts https://github.com/swc-project/swc/pull/6716.
 - Closes https://github.com/swc-project/swc/issues/6782.

### CODE REVIEW

**Comment by kdy1** [comment]
Investigation:

```
   INFO  jsc.paths, base_url: \\?\C:\Users\MSI\projects\swc-win\crates\swc\tests\fixture\issues-6xxx\6782\1\input
    at crates\swc_ecma_loader\src\resolvers\tsc.rs:54
    in Compiler.parse
    in parse_js_as_input
    in process_js_with_custom_pass
    in process_js_file with fm: SourceFile(\\?\C:\Users\MSI\projects\swc-win\crates\swc\tests\fixture\issues-6xxx\6782\1\input\config\index.ts)

   INFO  Done in 2.7276ms, kind: "perf"
    at crates\swc_timer\src\lib.rs:32
    in Compiler.parse
    in parse_js_as_input
    in process_js_with_custom_pass
    in process_js_file with fm: SourceFile(\\?\C:\Users\MSI\projects\swc-win\crates\swc\tests\fixture\issues-6xxx\6782\1\input\config\index.ts)

  DEBUG  Renaming `config#1` to `config`
    at crates\swc_ecma_transforms_base\src\rename\analyzer\scope.rs:183
    in process_js_inner
    in process_js_with_custom_pass
    in process_js_file with fm: SourceFile(\\?\C:\Users\MSI\projects\swc-win\crates\swc\tests\fixture\issues-6xxx\6782\1\input\config\index.ts)

   INFO  Done in 652µs, kind: "perf"
    at crates\swc_timer\src\lib.rs:32
    in Compiler.print
    in process_js_inner
    in process_js_with_custom_pass
    in process_js_file with fm: SourceFile(\\?\C:\Users\MSI\projects\swc-win\crates\swc\tests\fixture\issues-6xxx\6782\1\input\config\index.ts)

  DEBUG  compare_to_file: failed to canonicalize outfile path `\\?\C:\Users\MSI\projects\swc-win\crates\swc\tests\fixture\issues-6xxx\6782\1\output\index.map`: Os { code: 2, kind: NotFound, message: "지정된 파일을 찾을 수 없습니다." }
    at crates\testing\src\output.rs:115

File: \\?\C:\Users\MSI\projects\swc-win\crates\swc\tests\fixture\issues-6xxx\6782\1\input\src\index.ts
   INFO  Done in 1.0332ms, kind: "perf"
    at crates\swc_timer\src\lib.rs:32
    in Compiler.parse
    in parse_js_as_input
    in process_js_with_custom_pass
    in process_js_file with fm: SourceFile(\\?\C:\Users\MSI\projects\swc-win\crates\swc\tests\fixture\issues-6xxx\6782\1\input\src\index.ts)

  DEBUG  invoking resolver
    at crates\swc_ecma_transforms_module\src\path.rs:158
    in resolve_import with base: \\?\C:\Users\MSI\projects\swc-win\crates\swc\tests\fixture\issues-6xxx\6782\1\input\src\index.ts, module_specifier: @/config
    in process_js_inner
    in process_js_with_custom_pass
    in process_js_file with fm: SourceFile(\\?\C:\Users\MSI\projects\swc-win\crates\swc\tests\fixture\issues-6xxx\6782\1\input\src\index.ts)

  DEBUG  non-relative import
    at crates\swc_ecma_loader\src\resolvers\tsc.rs:131
    in tsc.resolve with base_url: \\?\C:\Users\MSI\projects\swc-win\crates\swc\tests\fixture\issues-6xxx\6782\1\input, base: \\?\C:\Users\MSI\projects\swc-win\crates\swc\tests\fixture\issues-6xxx\6782\1\input\src\index.ts, src: @/config
    in resolve_import with base: \\?\C:\Users\MSI\projects\swc-win\crates\swc\tests\fixture\issues-6xxx\6782\1\input\src\index.ts, module_specifier: @/config
    in process_js_inner
    in process_js_with_custom_pass
    in process_js_file with fm: SourceFile(\\?\C:\Users\MSI\projects\swc-win\crates\swc\tests\fixture\issues-6xxx\6782\1\input\src\index.ts)

  TRACE  to_specifier: orig_ext=None
    at crates\swc_ecma_transforms_module\src\path.rs:119
    in resolve_import with base: \\?\C:\Users\MSI\projects\swc-win\crates\swc\tests\fixture\issues-6xxx\6782\1\input\src\index.ts, module_specifier: @/config
    in process_js_inner
    in process_js_with_custom_pass
    in process_js_file with fm: SourceFile(\\?\C:\Users\MSI\projects\swc-win\crates\swc\tests\fixture\issues-6xxx\6782\1\input\src\index.ts)

  DEBUG  Renaming `config#3` to `config`
    at crates\swc_ecma_transforms_base\src\rename\analyzer\scope.rs:183
    in process_js_inner
    in process_js_with_custom_pass
    in process_js_file with fm: SourceFile(\\?\C:\Users\MSI\projects\swc-win\crates\swc\tests\fixture\issues-6xxx\6782\1\input\src\index.ts)

  DEBUG  Renaming `main#3` to `main`
    at crates\swc_ecma_transforms_base\src\rename\analyzer\scope.rs:183
    in process_js_inner
    in process_js_with_custom_pass
    in process_js_file with fm: SourceFile(\\?\C:\Users\MSI\projects\swc-win\crates\swc\tests\fixture\issues-6xxx\6782\1\input\src\index.ts)

   INFO  Done in 600.6µs, kind: "perf"
    at crates\swc_timer\src\lib.rs:32
    in Compiler.print
    in process_js_inner
    in process_js_with_custom_pass
    in process_js_file with fm: SourceFile(\\?\C:\Users\MSI\projects\swc-win\crates\swc\tests\fixture\issues-6xxx\6782\1\input\src\index.ts)
```

`base` is UNC

**Review by kdy1 — COMMENTED** [review]
swc-bump:
 - swc

**Comment by realtimetodie** [comment]
This removes support for symbolic links and breaks rules_swc @alexeagle

**Comment by kdy1** [comment]
@realtimetodie Can you send PR for adding tests for https://github.com/swc-project/swc/pull/6716? So I can ensure those are working while fixing https://github.com/swc-project/swc/pull/6930

**Comment by realtimetodie** [comment]
@kdy Yes I can. These new tests will not be directory based fixture tests and a will be a.little different. In this case, I will need to verify the support for symbolic links on different platforms programmatically, preferably in a temporary directory.

**Comment by realtimetodie** [comment]
I'm currently at work and will be back home in a couple of hours.

**Comment by realtimetodie** [comment]
I can confirm that the suggested changes break the Bazel support due to unnecessary path canonicalization of symbolic links.

```
exec ${PAGER:-/usr/bin/less} "$0" || exit 1
Executing tests from //examples/paths:test_test
-----------------------------------------------------------------------------
5c5
< const _moduleA = require("../../../src/modules/moduleA");
---
> const _moduleA = require("./modules/moduleA");
FAIL: files "examples/paths/src/index.js" and "examples/paths/expected.js" differ. 

@//examples/paths:expected.js is out of date. To update this file, run:

    bazel run //examples/paths:test

```

I'm working on the test cases.

**Comment by realtimetodie** [comment]
I can confirm that between b451fa9e88aee33368759a67913e7c6eb9c3898f and e332dffb588269dbfd494209b26da721f62b6868 (now) the module resolution has changed and the previous behavior can no longer be reproduced.

I also confirmed that the Bazel test fails prior to b451fa9e88aee33368759a67913e7c6eb9c3898f due to path canonicalization

```
exec ${PAGER:-/usr/bin/less} "$0" || exit 1
Executing tests from //examples/paths:test_test
-----------------------------------------------------------------------------
5c5
< const _moduleA = require("../../../../../../../../.cache/bazel/_bazel_kyoko/d981ac4e564436252b4ad023c1ebd769/sandbox/linux-sandbox/35/execroot/aspect_rules_swc/examples/paths/src/modules/moduleA");
---
> const _moduleA = require("./modules/moduleA");
FAIL: files "examples/paths/src/index.js" and "examples/paths/expected.js" differ. 

@//examples/paths:expected.js is out of date. To update this file, run:

    bazel run //examples/paths:test

```

To confirm this behavior, I created an integration test for Bazel using symbolic links in. The tree is checked out at that fails due to path canonicalization

**Comment by realtimetodie** [comment]
@kdy1 https://github.com/realtimetodie/swc/commit/1dc54c8576236c01bce71e9358a2f67dd1728bd6

**Comment by realtimetodie** [comment]
I tested the binary manually with Bazel and the tests pass.

**Comment by realtimetodie** [comment]
@kdy1 I added a Bazel test in https://github.com/realtimetodie/swc/commit/1dc54c8576236c01bce71e9358a2f67dd1728bd6 that verifies symbolic link support.

**Comment by kdy1** [comment]
@realtimetodie Can you create a PR towards swc main?

**Comment by realtimetodie** [comment]
@kdy1 https://github.com/swc-project/swc/pull/6933

**Comment by kdy1** [comment]
Thank you!

**Review by kdy1 — COMMENTED** [review]
swc-bump:
 - swc

**Pull request merged**
