### PR TITLE
feat(es/transform): support for importing namespaces from `const_modules`

### PR DESCRIPTION
**Pull request by magic-akari**
**Description:**

**BREAKING CHANGE:**

**Related issue (if exists):**

### CODE REVIEW

**Comment by magic-akari** [comment]
The current approach to defining const_modules involves using the Record<ident, expression> format, as exemplified below:

```JSON
{
  "globals": {
    "module_foo": {
      "DEBUG": "true"
    }
  }
}
```

I feel that this method to defining const_modules is a bit cumbersome. Instead, I prefer to use the Record<ident, value> format, as shown below:

```JSON
{
  "globals": {
    "module_foo": {
      "DEBUG": true
    }
  }
}
```

What is your opinion?

Perhaps I am looking for something like const_json_modules.

**Comment by kdy1** [comment]
I agree with your opinion.

**Comment by kdy1** [comment]
Storing an expression in a json file is quite cumbersome

**Review by kdy1 — APPROVED** [review]
Thanks!

---

swc-bump:
 - swc_ecma_transforms_optimization

**Pull request merged**
