### PR TITLE
fix(es/compat): Handle `useDefineForClassFields: false`

### LINKED ISSUE #6985: Inconsistent `useDefineForClassFields` behavior
### Describe the bug

result from TypeScript:

| useDefineForClassFields | true                     | false                    | None    |
| ----------------------: | :----------------------- | :----------------------- | :------ |
|                  ES2022 | [Native][ts_2022_true]   | [[[Set]]][ts_2022_false] | Native  |
|               <= ES2021 | [[[Define]]][ts_2020_true] | [[[Set]]][ts_2020_false]   | [[Set]] |

> Default: true if target is ES2022 or higher, including ESNext,,false otherwise.
> ref: https://www.typescriptlang.org/tsconfig#useDefineForClassFields

`useDefineForClassFields: false` always works in tsc, no matter what the target is.
However, if this option is missing, the tsc result will be different when the target changes.
The behavior of the `Native` class field is `[[Define]]`.

The behavior of swc and tsc is not identical, and the JS and TS outputs of swc are not identical.

[ts_2022_true]: https://www.typescriptlang.org/play?#code/PTAEAEBcEMCcHMCmkBcpEGcBMAGLWAoECAVw0QBFEAzASwDtEAxAe1gGEAbaDDJ2xJwAmGNJFglEBAMbdeoVi1ABvAqFAAPUAF5QARgDcBAL5A
[ts_2022_false]: https://www.typescriptlang.org/play?#code/PTAEAEBcEMCcHMCmkBcpEGcBMAGLWAoECAVw0QBFEAzASwDtEAxAe1gGEAbaDDJ2xJwAmGNNWidyBAMbdeoVi1ABvAqFAAPUAF5QARgDcBAL5A
[ts_2020_true]: https://www.typescriptlang.org/play?#code/PTAEAEBcEMCcHMCmkBcpEGcBMAGXAoECAVw0QBFEAzASwDtEAxAe1gGEAbaDDRmxDgBMMaSLGKJ8AYy49QLZqADe+UKAAeoALygAjAG58AXyA
[ts_2020_false]: https://www.typescriptlang.org/play?#code/PTAEAEBcEMCcHMCmkBcpEGcBMAGXAoECAVw0QBFEAzASwDtEAxAe1gGEAbaDDRmxDgBMMaKtA5l8AYy49QLZqADe+UKAAeoALygAjAG58AXyA

Ref: https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html#the-usedefineforclassfields-flag-and-the-declare-property-modifier

### Input code

```typescript
class Foo {
  x = 1;
}
```

### Config

_No response_

### Playground link

_No response_

### Expected behavior

| useDefineForClassFields | true       | false   | None   |
| ----------------------: | :--------- | :------ | :----- |
|                  ES2022 | Native     | [[Set]] | Native |
|           <= ES2021(TS) | [[Define]] | [[Set]] | x      |
|           <= ES2021(JS) | [[Define]] | [[Set]] | x      |

1. We expect `useDefineForClassFields: false` to always work.
2. We expect the same results from JS and TS.

x can be either `[[Define]]` or `[[Set]]`.
If we choose `[[Set]]`, then we keep the same behavior as TypeScript.
If we choose `[[Define]]`, then we get consistency with our `None` option, since `Native` means `[[Define]]`.

### Actual behavior

| useDefineForClassFields | true                           | false                           | None                           |
| ----------------------: | :----------------------------- | :------------------------------ | :----------------------------- |
|                  ES2022 | [Native][swc_2022_true_ts]     | [Native][swc_2022_false_ts]     | [Native][swc_2022_none_ts]     |
|           <= ES2021(TS) | [[[Define]]][swc_2020_true_ts] | [[[Set]]][swc_2020_false_ts]    | [[[Set]]][swc_2020_none_ts]    |
|           <= ES2021(JS) | [[[Define]]][swc_2020_true_js] | [[[Define]]][swc_2020_false_js] | [[[Define]]][swc_2020_none_js] |

1. `useDefineForClassFields: false` does not work for ES2022.
2. The results for `useDefineForClassFields: false` are different for TS and JS.
3. The results for `useDefineForClassFields: None` are different for TS and JS.

[swc_2022_true_ts]: https://play.swc.rs/?version=1.3.36&code=H4sIAAAAAAAAA0vOSSwuVnDLz1eo5lJQqFCwVTC05qoFAGMyfh4WAAAA&config=H4sIAAAAAAAAAxXLQQqDQBBE0bvU2kWY5WwTvEejZZhgxqGrhYjM3aO7z4N%2F4qMJ%2BUQzF%2F0uHTXsh4w4GjV5aYE%2BIMzfjIup9EgJl7hVLZt%2F72sXX1xK5bj5czVpLFxnIYfv7L3%2FAZrF9hZpAAAA
[swc_2022_false_ts]: https://play.swc.rs/?version=1.3.36&code=H4sIAAAAAAAAA0vOSSwuVnDLz1eo5lJQqFCwVTC05qoFAGMyfh4WAAAA&config=H4sIAAAAAAAAAxXLQQqEMBBE0bvU2oVkme2I92icjkQyMXS1MCK5u7r7PPgXNi6IF5oY1d7iWV3%2BiPCzKRfLzdEHuNiq%2FrAyjCHgEZPKtNvvvQ7qpClXnXf7FCHnrOVLxCSF2nu%2FAZeQBtpqAAAA
[swc_2022_none_ts]: https://play.swc.rs/?version=1.3.36&code=H4sIAAAAAAAAA0vOSSwuVnDLz1eo5lJQqFCwVTC05qoFAGMyfh4WAAAA&config=H4sIAAAAAAAAAxXLMQqAMAxG4bv8s4Nk7G1CSUXBGpIMlpK7W7fHB2%2Fi8ooyoWwu9pePHvyiIIaKVzs1kBuC7ZBYLE47EZYYd2%2BP3evKzA%2BRwzaSSwAAAA%3D%3D
[swc_2020_true_ts]: https://play.swc.rs/?version=1.3.36&code=H4sIAAAAAAAAA0vOSSwuVnDLz1eo5lJQqFCwVTC05qoFAGMyfh4WAAAA&config=H4sIAAAAAAAAAxXLQQqDQBBE0bvU2oW4nG2C92hMGUbMOHS1oMjcPbr7PPgXFk1IF6q56E%2FpLGEHEuKs1OS5BlqHMP8ybqaGfuhxi1vRvPnvuXbxzTkXjpu%2FVpPGzPUjpPCdrbU%2F%2FZ0302kAAAA%3D
[swc_2020_false_ts]: https://play.swc.rs/?version=1.3.36&code=H4sIAAAAAAAAA0vOSSwuVnDLz1eo5lJQqFCwVTC05qoFAGMyfh4WAAAA&config=H4sIAAAAAAAAAxXLMQrDMBBE0btMncK4VJvgeyzOKCgostjZQIzR3WN3nwf%2FwFsr0oFuLvpV2lvYDwmxd2r10gPjhjB%2FMU6m5mmecIpbU978c11f8cFcGpfN79WkpbA%2BhZStimOMPzSlFQlqAAAA
[swc_2020_none_ts]: https://play.swc.rs/?version=1.3.36&code=H4sIAAAAAAAAA0vOSSwuVnDLz1eo5lJQqFCwVTC05qoFAGMyfh4WAAAA&config=H4sIAAAAAAAAAxXLMQqAMAxG4bv8s0Pp2NuEEkXBGpIMlpK7G7fHB2%2Fhso62IKTG%2BpfN4fSiwaewdT3FERuc9GBPZqulFqQoDdsfvfOKiA9gxYLmSwAAAA%3D%3D
[swc_2020_true_js]: https://play.swc.rs/?version=1.3.36&code=H4sIAAAAAAAAA0vOSSwuVnDLz1eo5lJQqFCwVTC05qoFAGMyfh4WAAAA&config=H4sIAAAAAAAAAxXLMQqAMBBE0btMbSGWaRXvscRVIhplZwVFcndN93nwX6yMCC9OMarV4pNdbgRo3IXR0ukoDVxsUa%2FMru1a%2FGKSOR%2B21%2BuiDjqnrONh%2FSbkmHSbiOB2aSnlA5r52odpAAAA
[swc_2020_false_js]: https://play.swc.rs/?version=1.3.36&code=H4sIAAAAAAAAA0vOSSwuVnDLz1eo5lJQqFCwVTC05qoFAGMyfh4WAAAA&config=H4sIAAAAAAAAAxXLMQqAMBBE0btMbSGWaRXvscSNRGKUnQiK5O6a7vPgv9jo4V6cYlRrxScXueGgfhd6i2dB7VDEVi2NOfRDj19MMsNhe7su6qQhZp0PG5OQc9S0EC5IotZaP6u8l9pqAAAA
[swc_2020_none_js]: https://play.swc.rs/?version=1.3.36&code=H4sIAAAAAAAAA0vOSSwuVnDLz1eo5lJQqFCwVTC05qoFAGMyfh4WAAAA&config=H4sIAAAAAAAAA6tWyipOVrKqVipILCpOLQKxiivzShIrlKyUUpNzE4uTizILSpRqdZRKEovSU0tAwsVGBkYGSkCRosS84rT8olygrtraWgDGsGlFSwAAAA%3D%3D

### Version

1.3.36

### Additional context

Output 1: `Native` class field

```JavaScript
class Foo {
    x = 1;
}
```

Output 2: `[[Set]]`

```JavaScript
class Foo {
    constructor() {
        this.x = 1;
    }
}
```

Output 3: `[[Define]]` from TypeScript

```JavaScript
class Foo {
    constructor() {
        Object.defineProperty(this, "x", {
            enumerable: true,
            configurable: true,
            writable: true,
            value: 1
        });
    }
}
```

Output 4: `[[Define]]` from swc

```JavaScript
function _defineProperty(obj, key, value) {
    if (key in obj) {
        Object.defineProperty(obj, key, {
            value: value,
            enumerable: true,
            configurable: true,
            writable: true
        });
    } else {
        obj[key] = value;
    }
    return obj;
}
class Foo {
    constructor(){
        _defineProperty(this, "x", 1);
    }
}
```

### PR DESCRIPTION
**Pull request by magic-akari**
**Description:**

**BREAKING CHANGE:**

# IMPORTANT NOTE: Users of decorators are recommended to configure `"useDefineForClassFields": false` to ensure that your code is properly transpiled.

**Related issue (if exists):**
- fix #6985

### CODE REVIEW

**Comment by kdy1** [comment]
I think so. Thank you!

**Comment by magic-akari** [comment]
> I think so. Thank you!

| useDefineForClassFields | true       | false   | None   |
| ----------------------: | :--------- | :------ | :----- |
|                  ES2022 | Native     | [[Set]] | Native |
|           <= ES2021(TS) | [[Define]] | [[Set]] | [[Define]]      |
|           <= ES2021(JS) | [[Define]] | [[Set]] | [[Define]]      |

So, we choose the Define semantics when there is no input value from the user, right? \
This may deviate from TS behavior, however, it ensures consistency in the final column of our table.

**Comment by kdy1** [comment]
Yes, I think it's more important to be consistent than to align with `tsc`

**Comment by magic-akari** [comment]
It appears that https://github.com/microsoft/TypeScript/issues/45995 is a bug in TypeScript that occurs when `useDefineForClassFields` is absent.

When its value is present, the order of the TS constructor parameter properties always precedes the ECMAScript class field for the four cases of ES Version and useDefineForClassFields: true/false.

Please refer to the following table for more detailed information.

| useDefineForClassFields | true                         | false                         |
| ----------------------: | :--------------------------- | :---------------------------- |
|                  ES2022 | [TS Playground][es2022_true] | [TS Playground][es2022_false] |
|               <= ES2021 | [TS Playground][es2021_true] | [TS Playground][es2021_false] |

[es2022_true]: https://www.typescriptlang.org/play?useDefineForClassFields=true&target=9#code/PTAEAEFcGcFMBFYDMCWA7WAxA9gJwMIA2AhtNJirIQCbQBcoALrpLAFAgSPG4DmsjBrGgAmAAwiRbDAHdQAYxJlQ8UgAsARth7VQAbzagjoNMQC2sUAF4F2NNGyFYAOkLZeACkZqU0Z+exINEYASgBuQ2N5O2hmSHlGPA8AB0gNQhR5UACgwRNIMw1YXBD9SKMAXzYKjwBGcKA
[es2022_false]: https://www.typescriptlang.org/play?target=9&useDefineForClassFields=true#code/PTAEAEFcGcFMBFYDMCWA7WAxA9gJwMIA2AhtNJirIQCbQBcoSxhcAUCBAC7G4DmsnBrGgAmAAwiRrDAHdQAYxJlQ8UgAsARth7VQAb1agjoNMQC2sUAF4F2NNGyFYAOkLZeACk5qU0Z+exINE4ASgBuQ2N5O2hOXEh5TjwPAAdIDUIUeVAAoMETSDMNWFwQ-UijAF9WSo8ARnCgA
[es2021_true]: https://www.typescriptlang.org/play?useDefineForClassFields=true&target=8#code/PTAEAEFcGcFMBFYDMCWA7WAxA9gJwMIA2AhtNJirIQCbQBcoALrpLAFAgSPG4DmsjBrGgAmAAwiAjGwwB3UAGMSZUPFIALAEbYe1UAG82oY6DTEAtrFABeRdjTRshWADpC2XgApG6lNBcW2JBojACUANxGJgr20MyQCox4ngAOkJqEKAqggcGCppDmmrC4oQZRxgC+bJWekhFAA
[es2021_false]: https://www.typescriptlang.org/play?target=8&useDefineForClassFields=true#code/PTAEAEFcGcFMBFYDMCWA7WAxA9gJwMIA2AhtNJirIQCbQBcoSxhcAUCBAC7G4DmsnBrGgAmAAwiAjKwwB3UAGMSZUPFIALAEbYe1UAG9WoY6DTEAtrFABeRdjTRshWADpC2XgApO6lNBcW2JBonACUANxGJgr20Jy4kAqceJ4ADpCahCgKoIHBgqaQ5pqwuKEGUcYAvqxVnpIRQA

**Comment by kdy1** [comment]
🤣 It was a bug of `tsc`. What should we do, in your opinion?

**Comment by magic-akari** [comment]
The https://github.com/microsoft/TypeScript/issues/45995 issue  arises only when useDefineForClassFields is missing. However, if it is explicitly set to either true or false, then TS's constructor parameter properties consistently appear first. Hence, we must adhere to TS's behavior.

Moreover, there is another issue in TS where the initialization of constructor parameter properties does not always take effect.

Check the following code.

[TS Playground](https://www.typescriptlang.org/play?useDefineForClassFields=true&target=9#code/PTAEAEBcEMCcHMCmkBcpEGcBMAGLWAoECAVw0QBFEAzASwDtEAxAe1gGEAbaDDJ2xJwAmGNJFglEBAMbdeoVi1ABvAqFAAjUAF5QkABa0MAOmgBuNaGkt6GcSWmQ2ACgAOJDZ1rTQ0HaABGAEpVSwBfAjCgA)

```TypeScript
// @target: es2022
// @useDefineForClassFields: true
class Foo {
  b = this.a;
  constructor(public a = 1){

  }
}
```

output:

```TypeScript
class Foo {
    a;
    b = this.a;
    constructor(a = 1) {
        this.a = a;
    }
}
```

The value obtained by b is undefined. However, if we reduce the ES version to below ES2022,

[TS Playground](https://www.typescriptlang.org/play?useDefineForClassFields=true&target=8#code/PTAEAEBcEMCcHMCmkBcpEGcBMAGLBGAKBAgFcNEARRAMwEsA7RAMQHtYBhAG2gw2bqIuAEwxpIsUokIBjHn1BtWoAN6FQoAEagAvKEgALOhgB00ANzrQM1gwwTSMyOwAUAB1KaudGaGi7QfABKNSsAX0IwoA)

```JavaScript
class Foo {
    constructor(a = 1) {
        Object.defineProperty(this, "a", {
            enumerable: true,
            configurable: true,
            writable: true,
            value: a
        });
        Object.defineProperty(this, "b", {
            enumerable: true,
            configurable: true,
            writable: true,
            value: this.a
        });
    }
}
```

B will get the correct value. I believe that such a situation is more reasonable. Therefore, for the scenarios above ES2022, I have made an improvement. SWC will output the following code to ensure correctness.

```JavaScript
class Foo {
    a;
    b;
    constructor(a = 1) {
        this.a = a;
        this.b = this.a;
    }
}
```

**Comment by kdy1** [comment]
Sounds good, thank you so much for your hard work.

**Review by kdy1 — APPROVED** [review]
Thank you!

---

swc-bump:
 - swc_ecma_ast
 - swc --breaking

**Pull request merged**
