### PR TITLE
Upgrade to napi@1

### LINKED ISSUE #1238: Provide binary for android
**Describe the feature**
Basically to run swc on android (e.g. by using termux) one would need a binary for android / arm64.

Currently getting this error on yarn install:
```
error @swc/core@1.2.36: The platform "android" is incompatible with this module.
error @swc/core@1.2.36: The CPU architecture "arm64" is incompatible with this module.
```

### LINKED ISSUE #1257: Support for armv7l
It would be extremely useful if this project supported ARMv7. That would, for instance, make it possible to use Raspberry Pi for development.

### LINKED ISSUE #1265: Fails to load in yarn 2 PnP
**Describe the bug**

@swc/core does not load under yarn 2 PnP.

The root cause is in `@node-rs/helpers`, but once it's fixed, it will require a tiny code change in `@swc/core`

Here is a description of the root cause of the failure.
https://github.com/napi-rs/node-rs/issues/263

Once the root cause is fixed, `@swc/core` will need to adjust it's `loadBinding` call like this:
https://github.com/swc-project/swc/blob/master/node-swc/src/index.ts#L14

```
const bindings = loadBinding(__dirname, "swc", "@swc/core", require)
```

**Input code**

N/A

**Config**

N/A

**Expected behavior**

`require('@swc/core')` succeeds when installed via yarn PnP.

**Version**
The version of @swc/core: 1.2.40

**Additional context**

### PR DESCRIPTION
**Pull request by Brooooooklyn**
New platforms support:
- ~~windows x32~~ (Wait for https://github.com/rust-lang/rust/issues/67497)
- apple silicon
- linux aarch64
- linux armv7
- android aarch64

- [x] Be compatible with yarn pnp

---

Closes #1238.
Closes #1257.
Closes #1265.

### CODE REVIEW

**Comment by Brooooooklyn** [comment]
@kdy1 testing failed, doesn't seem to be caused by my changes.

**Comment by kdy1** [comment]
The failing test is a test about invalid config file.
It seems like `napi::CallContext.get_deserialized` does not support `deny_unknown_fields` of serde. Is this intentional?

**Comment by Brooooooklyn** [comment]
hmmmm, seems like error was eaten by napi...I will fix it

**Comment by kdy1** [comment]
Is this done?

**Comment by Brooooooklyn** [comment]
Everything is done in swc side, I need sometime to prepare the napi@1 final release, like documentation and migration guide.

**Comment by kdy1** [comment]
Then I'll wait for it. Thanks a lot!!

**Comment by Brooooooklyn** [comment]
Ready to review

**Review by kdy1 — APPROVED** [review]
Cool. Thanks a lot!

**Pull request merged**
