### PR TITLE
refactor(css/parser): refactor code

### PR DESCRIPTION
**Pull request by alexander-akait**
**Description:**

use more box + refactor code according spec + tests for new nesting parsing

**BREAKING CHANGE:**

Yes

**Related issue (if exists):**

No

### CODE REVIEW

**Review by kdy1 — APPROVED** [review]
swc-bump:
 - swc_css_ast --breaking

**Review by kdy1 — CHANGES_REQUESTED** [review]
there's a merge conflict

**Comment by alexander-akait** [comment]
@kdy1 Rebased :+1:

**Comment by kdy1** [comment]
Can you rebase again?

**Comment by alexander-akait** [comment]
Yes, WIP

**Comment by alexander-akait** [comment]
@kdy1 Fixed :+1:

**Review by kdy1 — APPROVED** [review]

**Pull request merged**
