### PR TITLE
Fix NodeModulesResolver::resolve for handling module specifiers with `node:` prefix correctly.

### LINKED ISSUE #6058: Support imports that use the node prefix
### Describe the feature

Node 18 added the ability to import builitins using the node: prefix and projects targeting node 18 are encouraged to use this. A number of projects are using node: but swc doesn't appear to support this currently and attempting to use a package that has switched to the node 18 method of importing builtins will trigger an error.

The feature would:

1. Add the ability to resolve modules that use the node: prefix.
2. Remove the prefix if the target node environment doesn't support it ( version < 18 ).

### Babel plugin or link to the feature description

https://nodejs.org/api/esm.html#node-imports

### Additional context

esbuild implementation: https://github.com/evanw/esbuild/blob/master/internal/resolver/resolver.go
Discussion leading to this report: https://github.com/swc-project/swc/discussions/6055

### LINKED ISSUE #6848: support for resolving `node` protocole
### Describe the bug

node protocol for resolving module is broken (ie `node:path`) with spack

### Input code

```typescript
import { join } from 'node:path';

console.log(join('a', 'b'));
```

### Config

```js
const { join } = require('node:path');

const { config } = require('@swc/core/spack');

const CWD = process.cwd();

module.exports = config({
  mode: 'production',
  target: 'node',
  entry: {
    build: join(CWD, 'src', 'index.ts'),
  },
  output: {
    name: 'index.js',
    path: join(CWD, 'dist'),
  },
});
```

### Playground link

_No response_

### Expected behavior

module `node:path` should be resolved

### Actual behavior

Error with the command `npx spack`

```shell
❯ npx spack
node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[Error: load_transformed failed

Caused by:
    0: failed to analyze module
    1: failed to resolve node:path from /Users/******/projects/****/mono-repo/packages/*****/src/index.ts
    2: Impossible to get the node_modules path] {
  code: 'GenericFailure'
}

Node.js v18.13.0
```

### Version

1.3.28

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by nissy-dev**
**Description:** 

Fix #6848

I fixed `NodeModulesResolver::resolve` for handling module specifiers with `node:` prefix correctly.

**BREAKING CHANGE:** No

**Related issue (if exists):** #6848, This PR may fix #6058 too

### CODE REVIEW

**Comment by kdy1** [comment]
I'm not sure about this. `spack` is going to be deprecated in favor of turbopack

**Comment by nissy-dev** [comment]
> I'm not sure about this. spack is going to be deprecated in favor of turbopack

OK. Should I close my PR?

**Comment by kdy1** [comment]
I think this PR deserves a review/merge. I'll do it tommorow. Thank you!

**Review by kdy1 — APPROVED** [review]
Thanks!

---

swc-bump:
 - swc_ecma_loader

**Comment by blephy** [comment]
@nissy-dev thx !

**Pull request merged**
