### PR TITLE
refactor(swc_common): bytecheck arcstring

### PR DESCRIPTION
**Pull request by kwonoj**
**Description:**

Simple update to missing flags.

### CODE REVIEW

**Comment by kdy1** [comment]
Is this the correct place?
Any idea to verify this PR?

**Comment by kwonoj** [comment]
We have same thing for `EncodeJsWord` as well.

I don't have way to verify yet (after all we don't use versionedstruct yet). However, this should be noop even in worst case?

**Comment by kdy1** [comment]
Make sense. Thank you!

**Review by kdy1 — APPROVED** [review]
swc-bump:
 - swc_common

**Pull request merged**
