### PR TITLE
feat(es/minifier): Invoke sequential inliner for inlined IIFEs

### PR DESCRIPTION
**Pull request by kdy1**
**Description:**

Inlined IIFEs have the exact pattern sequential inliner wants, so it's good to invoke it.

### CODE REVIEW

**Comment by kdy1** [comment]
cc @Austaras Do you think this is a correct change?

**Comment by Austaras** [comment]
At least this would do no harm.

**Comment by kdy1** [comment]
Thank you!

**Review by kdy1 — COMMENTED** [review]
swc-bump:
 - swc_ecma_minifier

**Pull request merged**
