### PR TITLE
feat(es/testing): Use `__swc_snapshots__` for `test!` macro

### LINKED ISSUE #4509: Migrate inlined fixture tests to file-based fixture tests
Updating test references takes too much time.
I'll do this gradually

## PRs

 - https://github.com/swc-project/swc/pull/4510

### PR DESCRIPTION
**Pull request by kdy1**
**Description:**

This implements something similar to `__snapshots__` of `jest`. Instead of storing the expected result as a string literal, we now store it in `$crate/tests/__snapshots__/$path_to_test__$test_name.js`.

**Related issue:**

 - Closes #4509

### CODE REVIEW

**Review by kdy1 — COMMENTED** [review]
swc-bump:
 - testing

**Review by kdy1 — COMMENTED** [review]
swc-bump:
- swc_ecma_transforms_testing

**Comment by SevereCloud** [comment]
@kdy1 

> swc-bump:
> 
> * swc_ecma_transforms_testing

Hi, it was breaking change. `cargo update` break [fixture testing](https://swc.rs/docs/plugin/ecmascript/getting-started#testing-your-transform )

**Comment by kdy1** [comment]
My bad

**Pull request merged**
