### PR TITLE
fix(es/compat): Handle single expression case in static block

### LINKED ISSUE #7922: Avoid IIFEs for static class member definition with `useDefineForClassFields: false`
### Describe the bug

I'm trying to understand SWC's output for static class members with `useDefineForClassFields: false`.

```ts
// input
class Foo {
  static x = 1;
}

// output
class Foo {
}
(()=>{
    Foo.x = 1;
})();
```
```ts
// input
class Foo {
  static x = 1;
  static y = 1;
}

// output
class Foo {
}
(()=>{
    Foo.x = 1;
})();
(()=>{
    Foo.y = 1;
})();

```
[playground](https://play.swc.rs/?version=1.3.36&code=H4sIAAAAAAAAA0vOSSwuVnDLz1eo5lJQqFCwVTC05qoFAGMyfh4WAAAA&config=H4sIAAAAAAAAAxXLMQrDMBBE0btMncK4VJvgeyzOKCgostjZQIzR3WN3nwf%2FwFsr0oFuLvpV2lvYDwmxd2r10gPjhjB%2FMU6m5mmecIpbU978c11f8cFcGpfN79WkpbA%2BhZStimOMPzSlFQlqAAAA)

Why does SWC use an IIFE to define the static class member?

The reason I ask is because:
a) [this doesn't match TS's output](https://www.typescriptlang.org/play?#code/MYGwhgzhAEBiD29oG8BQ1oQC5iwS2GgA9oBeaARgG5UBfIA)
b) this causes down-stream problems with other tools (https://github.com/google/closure-compiler/issues/4116)

I tried to investigate via the PR that introduced this output (https://github.com/swc-project/swc/pull/7055) however the PR doesn't include any information about why an IIFE was introduced.

I'm not sure why the extra bytes are generated specifically for class properties. I understand  using them for static blocks - but I don't understand why they're used for class properties.

### Input code

_No response_

### Config

_No response_

### Playground link

_No response_

### SWC Info output

_No response_

### Expected behavior

.

### Actual behavior

_No response_

### Version

1.3.83

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by magic-akari**
**Related issue:**

 - Closes #7922

### CODE REVIEW

**Review by kdy1 — APPROVED** [review]
swc-bump:
 - swc_ecma_transforms_compat

**Comment by kdy1** [comment]
CI failed

**Comment by magic-akari** [comment]
> CI failed

Test cases updated.

**Review by kdy1 — APPROVED** [review]
swc-bump:
 - swc_ecma_transforms_compat

**Pull request merged**
