### PR TITLE
Legacy decorator for class and class members

### LINKED ISSUE #421: [Typescript] Decorator Issue
Hi, I'm brand new to SWC and trying it on and existing project.

I'm running into an issue with decorators. I'm using a `bind-decorator`. Code is here https://github.com/NoHomey/bind-decorator/blob/master/src/index.ts

I can see it is expecting 3 arguments, but being passed only 1.
image

My `.swcrc` looks like
```
{
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "tsx": true,
      "decorators": true,
      "dynamicImport": true
    }
  }
}
```
using versions:
@swc/core@1.0.45
swc-loader@0.1.6

Am I doing something wrong?

### PR DESCRIPTION
**Pull request by kdy1**
Fixes #421.

### CODE REVIEW

**Comment by wendellhu95** [comment]
If I don't use `legacyDecorator` with `emitDecoratorMetadata` then the decorator is gone in the output file. It this a designed behavior?

**Comment by kdy1** [comment]
Please post the url. Screenshot is too bad for reproducing bugs.

**Comment by kdy1** [comment]
Also, it should not disappear if I remember correctly.

**Comment by wendellhu95** [comment]
@kdy1 Thanks for reply. The reproduction is here. https://play.swc.rs/?version=1.2.106&code=H4sIAAAAAAAAA0XMUQrCMBAE0P%2BcYj4b6AkURcWLxO1WgiVbNhuhhNy9EYTO5zDz5pLIoiQ8mUSDiQ4e1aFH2YomDBb0zTbiw9uIiTNpXPvO43JFbWfXnKMl5Iz7%2F0iSsmmhH3Y73IfHqvEbjDsdJknLhtcJva6tIzvQ7WZvigAAAA%3D%3D&config=H4sIAAAAAAAAA02OMQ6DMAxF7%2BKZoWXowNy1h7CCQamSOLKN1Ahx9yZARTdbfv99r%2FBWB8MKGUVJ2qQlGX5gACuZ1InPBh2M5FjQWBQGk4U6MK3QhEFpqwvKTFZDpP2tv9dAYFY6gQ6iT34qTe84ZiHV64RpDvSnEkw6scRGB5rRleev%2FOjeKhV5XFpq3d%2Fcix%2BwXUWn3OvrBA%2F9F9Zf7R7wAAAA

Am I missing something?

**Comment by kdy1** [comment]
Ah, I found the cause.
Parameter properties in a constructor use a different type and seems like it's the cause.
It works if I remove `private readonly`.

https://play.swc.rs/?version=1.2.106&code=H4sIAAAAAAAAA0WMQQqDMBBF9znFXxrwBEqLLV4kjmMRSyKTyUJC7t5YBP%2Firf57S%2FKka%2FAYmYI4DdJYZIM6YU3i0aiTD2uLjY8WM0eSda8%2Fi8cTufSmGENfFyNel%2FgHBR9VEp3F4Y6%2FLaYOlblU8QdGkifxfgAAAA%3D%3D&config=H4sIAAAAAAAAA02OMQ6DMAxF7%2BKZoWXowNy1h7CCQamSOLKN1Ahx9yYURDdbfu9%2Fr%2FBWB8MKGUVJ2qQlGX5gACuZ1InPBh2M5FjQWBQGk4U6MK3QhEFpqwvKTFYl0v7W36sQmJUOoIPok59Ki3ccs5DqdcI0B%2FqLEkw6scRGB5rRledZflIVizwuTVv3P%2FfmB2xX05Hu9XWAP%2FMLGts1pPEAAAA%3D

**Comment by kdy1** [comment]
I filed #2658 for this;

**Pull request merged**
