### PR TITLE
feat(html/minifier): merge the same metadata elements

### PR DESCRIPTION
**Pull request by alexander-akait**
**Description:**

Merge the same `style` elements into one:

```css
<style>a { color: red; }</style><style>b { color: red; }</style>
```

->

```css
<style>a { color: red; }b { color: red; }</style>
```

The same possible with `script` tags, but need more complex logic and will be implemented in future

+ extra tests

Ref: https://github.com/kangax/html-minifier/issues/1126

**BREAKING CHANGE:**

Yes

**Related issue (if exists):**

No

### CODE REVIEW

**Comment by ghostd** [comment]
We should not merge tags ("style" or other) having some attributes like "id"; but maybe this is a very rare use case.

**Comment by alexander-akait** [comment]
We don't merge them when attributes are different

**Review by kdy1 — APPROVED** [review]
swc-bump:
 - swc_html_minifier

**Review by kdy1 — CHANGES_REQUESTED** [review]
There's a merge conflict

**Comment by alexander-akait** [comment]
@kdy1 Fixed

**Pull request merged**
