### PR TITLE
Fix metadata resolution for getter and setters

### PR DESCRIPTION
**Pull request by hbina**
Signed-off-by: Hanif Bin Ariffin <hanif.ariffin.4326@gmail.com>

**Description:**

Fix metadata resolution on getter/setter.

**BREAKING CHANGE:**

None that I am aware of.

**Related issue (if exists):**

https://github.com/swc-project/swc/issues/5252

### CODE REVIEW

**Comment by kdy1** [comment]
You can do `UPDATE=1 cargo test` to update test reference files

**Comment by hbina** [comment]
getting this error

```
   Compiling swc_css v0.127.10 (/home/hbina/git/swc/crates/swc_css)
error: custom attribute panicked
   --> crates/swc_html_parser/tests/fixture.rs:489:1
    |
489 | #[testing::fixture("tests/html5lib-tests/tokenizer/**/*.test")]
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = help: message: No test found

error: custom attribute panicked
   --> crates/swc_html_parser/tests/fixture.rs:968:1
    |
968 | #[testing::fixture("tests/html5lib-tests/tree-construction/**/*.dat")]
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = help: message: No test found

error: unused imports: `fs`, `mem::take`
 --> crates/swc_html_parser/tests/fixture.rs:7:11
  |
7 | use std::{fs, mem::take, path::PathBuf};
  |           ^^  ^^^^^^^^^
  |
note: the lint level is defined here
 --> crates/swc_html_parser/tests/fixture.rs:1:9
  |
1 | #![deny(warnings)]
  |         ^^^^^^^^
  = note: `#[deny(unused_imports)]` implied by `#[deny(warnings)]`

error: unused import: `serde_json::Value`
 --> crates/swc_html_parser/tests/fixture.rs:9:5
  |
9 | use serde_json::Value;
  |     ^^^^^^^^^^^^^^^^^

error: unused imports: `JsWord`, `js_word`
  --> crates/swc_html_parser/tests/fixture.rs:10:17
   |
10 | use swc_atoms::{js_word, JsWord};
   |                 ^^^^^^^  ^^^^^^

error: unused imports: `BytePos`, `StringInput`, `collections::AHashSet`
  --> crates/swc_html_parser/tests/fixture.rs:12:5
   |
12 |     collections::AHashSet,
   |     ^^^^^^^^^^^^^^^^^^^^^
13 |     errors::Handler,
14 |     input::{SourceFileInput, StringInput},
   |                              ^^^^^^^^^^^
15 |     BytePos, Spanned,
   |     ^^^^^^^

error: unused imports: `State`, `error::ErrorKind`
  --> crates/swc_html_parser/tests/fixture.rs:19:5
   |
19 |     error::ErrorKind,
   |     ^^^^^^^^^^^^^^^^
20 |     lexer::{Lexer, State},
   |                    ^^^^^

warning: unused variable: `handler`
  --> crates/swc_css_modules/tests/fixture.rs:37:35
   |
37 |     testing::run_test(false, |cm, handler| {
   |                                   ^^^^^^^ help: if this is intentional, prefix it with an underscore: `_handler`
   |
   = note: `#[warn(unused_variables)]` on by default

error: unused import: `input::ParserInput`
  --> crates/swc_html_parser/tests/fixture.rs:21:14
   |
21 |     parser::{input::ParserInput, PResult, Parser, ParserConfig},
   |              ^^^^^^^^^^^^^^^^^^

error: could not compile `swc_html_parser` due to 8 previous errors
warning: build failed, waiting for other jobs to finish...
warning: `swc_css_modules` (test "fixture") generated 1 warning
```

**Comment by kdy1** [comment]
Checkout submodules. And you can run cargo test in each directories

**Comment by kdy1** [comment]
Closing as the target issue is fixed

**Pull request closed without merging**
