### PR TITLE
Env option

### PR DESCRIPTION
**Pull request by tmpfs**
Initial preparation to support mapping environment variables to bundle globals.

See: https://github.com/swc-project/swc/issues/2087

### CODE REVIEW

**Comment by tmpfs** [comment]
Hi @kdy1, I think this is ready to be merged if you approve :+1: 

We can now configure an `env` map in `spack.config.js` and extend/override them with the `--env` option (see https://github.com/swc-project/cli/pull/54).

These variables are converted into a tree structure in `EnvironmentGlobals` and then folded into the module in `finalize()`. When building multiple bundles they would be injected into each bundle.

**Comment by kdy1** [comment]
I think this is already possible using `swc` option.
See: https://swc.rs/docs/configuring-swc/#jsctransformoptimizer

```json
{
  "jsc": {
    "transform": {
      "optimizer": {
        "globals": {
          "vars": {
            "__DEBUG__": "true"
          }
        }
      }
    }
  }
}
```

Although it's not documented, it acutally supports inlining environment variables.


```json
{
  "jsc": {
    "transform": {
      "optimizer": {
        "globals": {
          "vars": {
            "__DEBUG__": "true"
          },
          "env": ["NODE_ENV"]
        }
      }
    }
  }
}
```

should inline `process.env.NODE_ENV` if I remember it correctly.

**Comment by tmpfs** [comment]
Thanks @kdy1, setting `envs` doesn't seem to be work in my test. Maybe I am doing something wrong?

Here is the entire config: 

```javascript
const path = require('path');
const { config } = require('@swc/core/spack')

module.exports = config({
  entry: {
    background: __dirname + '/app/scripts/background.js',
  },
  output: {
    path: path.join(__dirname, "dist", "chrome"),
  },
  module: {},
  alias: {
    browser: {
      fs: "localstorage-fs",
      constants: "constants-browserify",
      stream: "stream-browserify",
      path: "path-browserify",
      os: "os-browserify",
      crypto: "crypto-browserify",
      vm: "vm-browserify",
      http: "stream-http",
      https: "https-browserify",
      zlib: "browserify-zlib",
      tty: "tty-browserify",
    }
  },
  options: {
    jsc: {
      parser: {
        syntax: "ecmascript",
        jsx: true,
        dynamicImport: false,
        privateMethod: false,
        functionBind: false,
        exportDefaultFrom: false,
        exportNamespaceFrom: false,
        decorators: false,
        decoratorsBeforeExport: false,
        topLevelAwait: false,
        importMeta: false
      },
      transform: {
        optimizer: {
          globals: {
            envs: ['INFURA_PROJECT_ID']
          }
        }
      },
      target: "es2016",
      loose: false,
      externalHelpers: false,
      keepClassNames: false
    }
  }
});
```

Then I invoke `spack` with the environment variable:

```
INFURA_PROJECT_ID=1234 npx spack
```

And I am back to the `ReferenceError` I had before:

```
Uncaught ReferenceError: process is not defined
```

**Comment by tmpfs** [comment]
Ok, I took a look at the code and it seems like when `env_map()` is called in `SwcLoader` to setup `InlineGlobals` it only processes `NODE_ENV`. Should I modify that to accept any name declared in `transform.optimizer.globals.envs` instead? I think that will fix it.

**Comment by kdy1** [comment]
Yes, I think it's the right way to go.

**Comment by tmpfs** [comment]
Closing in favor of #2121.

**Pull request closed without merging**
