### PR TITLE
feat(node): update features check

### PR DESCRIPTION
**Pull request by laqda**
**Description:**

This PR contains two proposals.

First, move feature checks to build script. The `compile_error` error message won't be mixed with other errors that are consequences. What do you think of that ?

Second, add a check that insures that features `swc_v1` and `swc_v2` are not being used at the same time.

**Related issue (if exists):**

https://github.com/swc-project/swc/issues/3079

### CODE REVIEW

**Comment by kdy1** [comment]
I don't think we need a build script here

**Comment by laqda** [comment]
The build script was already there. I wasn't sure if it was a good place to have such tests. 
Should I just move the new check next to the existing one ?

**Comment by kdy1** [comment]
Yeah I think so

**Review by kdy1 — APPROVED** [review]
LGTM, thank you!

**Pull request merged**
