### PR TITLE
fix(es/parser): Fix bin expr parsed as instantiation expr

### LINKED ISSUE #4990: Less than and right shift operators are parsed as generics
### Describe the bug

In `expr1 < expr2 >> expr3`, the `< expr2 >` is wrongly treated as a generic.

### Input code

```typescript
console.log(0 < 2 >> 1);
```

### Config

_No response_

### Playground link

_No response_

### Expected behavior

Transpiles to `console.log(0 < 2 >> 1);`.

### Actual behavior

Transpiles to `console.log(0 > 1);`.

### Version

swc_ecma_parser 0.104.0

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by g-plane**
**Description:**

This PR fixes binary expression parsed as instantiation expression.

Input:

```ts
a<b>>c<d>
```

Before:

```ts
a > c
```

After:

```ts
a < b >> c
```

Note that expressions like `f<x> & g<y>` aren't valid any more, as [TypeScript does](https://www.typescriptlang.org/play?#code/GYHgHgfABAZFDmICeEg).

**BREAKING CHANGE:**

No.

**Related issue (if exists):**

Fixes #4990

### CODE REVIEW

**Comment by kdy1** [comment]
Did you try https://www.typescriptlang.org/play?#code/GYHgHgfABAZFDmICeEBQ7gFcB2BjALgJYD22UoAKhABQCUA3qlM1AE4Cm+mrZArANyoAvhhwESZRFTqMWbTtz6ChQA

```ts
f<x> & g<y>


function f<T>(){
    return 5;
}

function g<T>(){
    return 5;
}
```


It fails with 


```
The '&' operator is not allowed for boolean types. Consider using '&&' instead.
Cannot find name 'x'.
Operator '>' cannot be applied to types 'boolean' and '<T>() => number'.
```

which implies it's parsed as 

`((f<x)>)&(g<y>)`

I'm not sure if this PR is identical

**Comment by g-plane** [comment]
image

See the second error message "Expression expected".

**Review by kdy1 — APPROVED** [review]
I see, thank you!

---


swc-bump:
 - swc_ecma_parser

**Comment by nicolo-ribaudo** [comment]
Heads up: https://github.com/microsoft/TypeScript/pull/49353 changes the parsing of `f<x> & g<y>`.

**Comment by kdy1** [comment]
Oops
cc @g-plane

**Pull request merged**
