### PR TITLE
feat(es/codegen): emit comments in method `emit_module`

### PR DESCRIPTION
**Pull request by iheyunfei**
**Description:**

It looks like some changes in https://github.com/swc-project/swc/pull/3358 disappeared.

I also watch the [history changes](https://github.com/swc-project/swc/commits/main/crates/swc_ecma_codegen/src/lib.rs). It seems disappeared in e8b64a9871ccfda5f5fb1f03662650f3500e6634 right after fcb7288eb66e027fa7278b8f028e4486059241cd.

**BREAKING CHANGE:**

**Related issue (if exists):**

### CODE REVIEW

**Review by kdy1 — APPROVED** [review]
Thanks, but I expect some test changes.
You can run `UPDATE=1 cargo test` to update test references, and you may need to run in multiple time

**Comment by iheyunfei** [comment]
I try to run `UPDATE=1 cargo test` same as before and got some errors. Do I do something wrong?
```
➜  swc git:(main) UPDATE=1 cargo test
   Compiling wasmer-compiler-cranelift v2.3.0
   Compiling swc_ecma_transforms_base v0.95.0 (/Users/bytedance/Documents/gitcodes/swc/crates/swc_ecma_transforms_base)
   Compiling wasmer-vm v2.3.0
   Compiling wasmer-engine-universal-artifact v2.3.0
   Compiling swc_ecmascript v0.176.0 (/Users/bytedance/Documents/gitcodes/swc/crates/swc_ecmascript)
   Compiling swc_ecma_lints v0.50.0 (/Users/bytedance/Documents/gitcodes/swc/crates/swc_ecma_lints)
   Compiling swc_ecma_ext_transforms v0.77.0 (/Users/bytedance/Documents/gitcodes/swc/crates/swc_ecma_ext_transforms)
   Compiling swc_estree_compat v0.121.0 (/Users/bytedance/Documents/gitcodes/swc/crates/swc_estree_compat)
   Compiling swc_css_codegen v0.106.0 (/Users/bytedance/Documents/gitcodes/swc/crates/swc_css_codegen)
   Compiling swc_ecma_codegen v0.113.0 (/Users/bytedance/Documents/gitcodes/swc/crates/swc_ecma_codegen)
   Compiling swc_ecma_parser v0.109.1 (/Users/bytedance/Documents/gitcodes/swc/crates/swc_ecma_parser)
   Compiling jsdoc v0.78.0 (/Users/bytedance/Documents/gitcodes/swc/crates/jsdoc)
error: custom attribute panicked
  --> crates/swc_ecma_codegen/tests/test262.rs:71:1
   |
71 | #[testing::fixture("../swc_ecma_parser/tests/test262-parser/pass/*.js")]
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = help: message: No test found

warning: unused import: `PathBuf`
 --> crates/swc_ecma_codegen/tests/test262.rs:7:18
  |
7 |     path::{Path, PathBuf},
  |                  ^^^^^^^
  |
  = note: `#[warn(unused_imports)]` on by default

warning: `swc_ecma_codegen` (test "test262") generated 1 warning
error: could not compile `swc_ecma_codegen` due to previous error; 1 warning emitted
```

**Comment by kdy1** [comment]
You need to checkout submodules.

`git submodule update --init --recursive` will fix it

**Review by kdy1 — APPROVED** [review]
Thank you!

---
swc-bump:
 - swc_ecma_codegen

**Comment by iheyunfei** [comment]
I only saw one test fail due to changes to this PR and it is fixed now.

**Comment by kdy1** [comment]
@iheyunfei 
image

**Comment by kdy1** [comment]
Also, failure of `swc` crate is caused by this PR

**Comment by kdy1** [comment]
If you want I can update test refs instead.
I tried but I failed to push it due to permission issue.

**Comment by iheyunfei** [comment]
@kdy1 The tests passed:).

**Review by kdy1 — APPROVED** [review]
Thank you!

**Pull request merged**
