### PR TITLE
feat(es/minifier): Evaluate more `toFixed` expressions

### PR DESCRIPTION
**Pull request by magic-akari**
**Description:**

**BREAKING CHANGE:**

**Related issue (if exists):**

### CODE REVIEW

**Review by kdy1 — APPROVED** [review]
swc-bump:
 - swc_ecma_minifier

**Review by kdy1 — CHANGES_REQUESTED** [review]
CI failed

**Comment by magic-akari** [comment]
This test seems to be fragile. All tests pass on my machine.

**Comment by kdy1** [comment]
I'll investigate

**Pull request merged**
