### PR TITLE
fix(es/transforms/compat): Move the optional catch binding pass to ES2019

### PR DESCRIPTION
**Pull request by g-plane**
"Optional `catch` binding" should be at ES2019:

图片

https://github.com/tc39/proposals/blob/master/finished-proposals.md

### CODE REVIEW

**Review by kdy1 — CHANGES_REQUESTED** [review]
Can you also add es2019 to https://github.com/swc-project/swc/blob/48d61039d24aaef688bf0d573d6f6037366c5eec/src/builder.rs#L181-L184?

**Review by kdy1 — APPROVED** [review]
LGTM. Thanks!

**Comment by kdy1** [comment]
I'll bump versions and merge it once tests are fixed.

**Comment by g-plane** [comment]
Are there anything blocking this?

**Comment by kdy1** [comment]
No, but tests are failing.

**Pull request merged**
