### PR TITLE
fix(es/minifier): Don't inline functions if `keep_fnames` is enabled

### PR DESCRIPTION
**Pull request by kdy1**
**Description:**

**Related issue:**

 - https://github.com/vercel/next.js/issues/56550

### CODE REVIEW

**Comment by kdy1** [comment]
image


`this` and `U` is `undefined`

**Comment by kdy1** [comment]
It seems like it's constructed twice, and those values are `undefined` only on the second construction.
Second call looks like a reflection

**Comment by kdy1** [comment]
image

`u(u)` in the output (broken) vs `u(t)` in the input (below)

image

**Comment by kdy1** [comment]
image

I think the mangling variable renamer is skipping renaming `u1`.

**Comment by kdy1** [comment]
Ah, https://github.com/vercel/next.js/pull/56281 was the cause. I'll update `mangle.json`

**Comment by kdy1** [comment]
The name mangler was correct; The problem was that inliner happily inlined `t`  as `u` in `a(u)`

**Review by kdy1 — COMMENTED** [review]
swc-bump:
 - swc_ecma_minifier

**Review by jridgewell — DISMISSED** [review]

**Pull request merged**
