### PR TITLE
fix(node): tls allocation issue by updating linux gnu build image

### PR DESCRIPTION
**Pull request by Brooooooklyn**
Fix https://github.com/swc-project/swc/issues/4107

https://github.com/Brooooooklyn/swc/runs/6286599487?check_suite_focus=true passed

### CODE REVIEW

**Comment by Brooooooklyn** [comment]
@kdy1 ready

**Comment by kdy1** [comment]
Seems like the integration test is failing? https://github.com/swc-project/swc/runs/6285669053?check_suite_focus=true

**Comment by kdy1** [comment]
I'm not sure why it's faiiling, though

**Comment by Brooooooklyn** [comment]
Hmmm, maybe because I upgrade the `node@14` to `node@16` in the integration test. Should we revert the upgrade?

**Comment by kdy1** [comment]
I think it's better to update integration test (if it uses node 16 in recent version)
I'll modify this PR

**Review by kdy1 — APPROVED** [review]
swc-bump:
 - ''

**Pull request merged**
