### PR TITLE
fix(es/minifier): Don't inline properties if the var is not `fn-local`

### PR DESCRIPTION
**Pull request by kdy1**
**Description:**

**Related issue:**

 - https://github.com/vercel/next.js/issues/54192.

### CODE REVIEW

**Comment by kdy1** [comment]
@Austaras @jridgewell 

I think we need to improve logic for `is_fn_local`, but I think I should focus on fixing https://github.com/vercel/next.js/issues/54192 for now

**Review by kdy1 — COMMENTED** [review]
swc-bump:
 - swc_ecma_minifier

**Comment by Austaras** [comment]
Should we abort in the else block of [this](https://github.com/swc-project/swc/blob/main/crates/swc_ecma_minifier/src/compress/optimize/props.rs#L54)? It's causing many item being wrongfully inlined. For example
```js
export function createCaseFirst(g, methodName) {
  var chr = g.get(0)
  console.log(123)
  return chr[methodName]() + trailing;
}
```
In this case chr cannot be inlined because of side effects.

**Comment by kdy1** [comment]
I reflected it 👍

**Review by jridgewell — APPROVED** [review]

**Review by hexiaokang — APPROVED** [review]

**Pull request merged**
