### PR TITLE
fix(es/react): error report of react pragma

### LINKED ISSUE #5099: Panic on missing @jsxFrag value
### Describe the bug

SWC panics if `@jsxFrag` is missing a value:

### Input code

```typescript
/** @jsx h */
/** @jsxFrag */
import { h } from "preact";
import { Handlers, PageProps } from "$fresh/server.ts";
import { Marked, Parsed } from "markdown";

type Data = { markup: Parsed };

export const handler: Handlers<Data> = {
  async GET(req, ctx) {
    const markdown = await Deno.readTextFile(`posts/${ctx.params.id}.md`)
    const markup = Marked.parse(markdown);
    const resp = await ctx.render({ markup });
    return resp;
  },
};

export default function Greet(props: PageProps<Data>) {
  return (
    <>
      <div
        dangerouslySetInnerHTML={{
          __html: props.data.markup.content,
        }}
      />
    </>
  );
}
```
```


### Config

```json
n/a
```

### Playground link

https://play.swc.rs/?version=1.2.208&code=H4sIAAAAAAAAA11RS2%2FCMAy%2B91dYiENBqL2Xh3ZgwKQhIY07RI2Bbm2SOS4Pof73JW0paKc49vfwl8TDIbx92yucYBgHcXtbkDj6e1YYTQx3N63gQLqAniEUKffGz9lKKJkj2RFsxBE3pI3t0P0DoT3FFumMFLF95a0F%2FaD0LLIoO0rh2lJflIMGfDMIc8ECpo7gJ6VJOoID4LUWS7WyDKdmkaTbaOKpM88NAIS9qRSW79uQ8HcEKV8HdR9a9sPXwcVFZAxzVDpyaeUWr7zIcgz3Rlu2cf%2FuyJERJAobZbKKCrkf%2FFMqjdNpEnqkxfChPxi%2FQN3rmM7QqxIqiRQ%2BwkLVwgm5JFXjfaMaBS%2FxJR5EmTMcSpVyphUsCZFD478ief5K8xxN6lYvrMUns%2FpwhczObQkghToi6dLmty%2FkD6WQVtv15%2FR%2B7yAAu92JizyB2iuSziBqNo9cQEbFow5cVW0ZN3aT%2BnT5qj%2FIWu19hQIAAA%3D%3D&config=H4sIAAAAAAAAA0WPQQ6DMAwE%2F%2BIzh4pDD%2Fyhj4iCQ1MlcWSbqhTxd5JAy23lXXvHK7zEwrBCNizIVcmS1HxgAF0yimWfFTpQKSPlGbeiDU%2BoJYHS3%2Fq%2BuIFIEAZngmAH0SfvlnrLUsyMIpdl0hR%2ByXqKTRJHHGua0Vg9hCtbz6OwgxHfGChHTPpnoKw%2B%2Bu%2BJ7GMOrbK5W%2FEjjXMtWtsbjfUO28V28nh5nMG2uQOa%2FUZ1DwEAAA%3D%3D

### Expected behavior

No panic, there's an error returned that we can report

### Actual behavior

```
thread 'main' panicked at 'not yet implemented: proper error reporting for wrong `@jsxFrag`', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/swc_ecma_transforms_react-0.120.0/src/jsx/mod.rs:338:34
stack backtrace:
   0:     0x55d31e1aa18d - std::backtrace_rs::backtrace::libunwind::trace::h22893a5306c091b4
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x55d31e1aa18d - std::backtrace_rs::backtrace::trace_unsynchronized::h29c3bc6f9e91819d
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55d31e1aa18d - std::sys_common::backtrace::_print_fmt::he497d8a0ec903793
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x55d31e1aa18d - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h9c2a9d2774d81873
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x55d31e1d3e0c - core::fmt::write::hba4337c43d992f49
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/fmt/mod.rs:1194:17
   5:     0x55d31e1a1931 - std::io::Write::write_fmt::heb73de6e02cfabed
                               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/io/mod.rs:1655:15
   6:
...
```

### Version

swc_ecma_transforms_react@0.120.0

### Additional context

n/a

### PR DESCRIPTION
**Pull request by magic-akari**
**Description:**

**BREAKING CHANGE:**

**Related issue (if exists):**
- fix #5099

### CODE REVIEW

**Review by bcheidemann — COMMENTED** [review]
Is there a use case for omitting a value? Maybe missing values should be reported as an error? Wouldn't cause any issues with existing codebases as current behaviour is to panic.

**Comment by magic-akari** [comment]
> Is there a use case for omitting a value? Maybe missing values should be reported as an error? Wouldn't cause any issues with existing codebases as current behaviour is to panic.

We are following [Babel's behaviour](https://babeljs.io/repl#?browsers=chrome%20100&build=&builtIns=false&corejs=false&spec=false&loose=true&code_lz=PQKhAIAECsGcA8BKBXAdgFwJYFsCm4RgAoUCGBASWwAcB7AJ3QGVbl6BjfQksKOeAGL0AhgHMCxUnwQSiRADwA-ecEUBuIA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=false&presets=env%2Creact%2Ctypescript&prettier=false&targets=Node-10.13&version=7.18.7&externalPlugins=&assumptions=%7B%7D).

swc refuse to compile if it reported as an error. I don't think this is a fatal error.
swc currently cannot output warning-level reports, which is something that can be improved in the future.

**Review by bcheidemann — APPROVED** [review]
LGTM

**Review by kdy1 — APPROVED** [review]
Thank you!

---

swc-bump:
 - swc_ecma_transforms_react

**Pull request merged**
