### PR TITLE
feat(common): emit source map columns

### LINKED ISSUE #4637: Optional column mapping for codegenerator
### Describe the feature

Currently, swc will map column to column on sourcemap generation, which results large sourcemaps. Personally, providing an option for column mapping would be better for performance-wise.

### Babel plugin or link to the feature description

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by h-a-n-a**
**Description:**

Optionally emit source map columns, use `true` as default value

**BREAKING CHANGE:**
No breaking changes

**Related issue (if exists):**
closes #4637

### CODE REVIEW

**Review by kdy1 — APPROVED** [review]
Thank you!

---

swc-bump:
 - swc_common
 - swc --breaking

**Review by kdy1 — CHANGES_REQUESTED** [review]
Oh CI failed

You can run `UPDATE=1 cargo test` to update test references

**Comment by kdy1** [comment]
I'll fix it with another PR.
The benchmark is not marked as `required` so I can still merge it

**Review by kdy1 — APPROVED** [review]

**Review by kdy1 — APPROVED** [review]

**Comment by h-a-n-a** [comment]
@kdy1 would you like to publish `swc_common` as well?

**Comment by kdy1** [comment]
Published with https://github.com/swc-project/swc/commit/f63be2fb9e7ea1bcbb7c06726ccc055847ad6be5

Btw, if it's fine to ask, is this patch useful for rolldown?

**Comment by h-a-n-a** [comment]
> Published with [f63be2f](https://github.com/swc-project/swc/commit/f63be2fb9e7ea1bcbb7c06726ccc055847ad6be5)
> 
> Btw, if it's fine to ask, is this patch useful for rolldown?

Thank you for quick response!

It will be used as a patch for a bundler developing in my company

**Comment by kdy1** [comment]
I see!
I asked because I started working on the new bundler for swc today 😄

**Comment by h-a-n-a** [comment]
> I see! I asked because I started working on the new bundler for swc today 😄

Wow! It's really nice to hear that a newly designed swc bundler is under developmenet from Vercel team! When would it be released? I'm looking forward to it!.

**Comment by kdy1** [comment]
Not sure at the moment.
I think I found a working design, but there are so many tasks as it has lots of features

**Comment by kdy1** [comment]
@h-a-n-a If you are okay with sharing some information, can you tell me about some requirements? (Email/Discord is also fine)
The more requirements I know, the better will be the bundler

**Comment by h-a-n-a** [comment]
> @h-a-n-a If you are okay with sharing some information, can you tell me about some requirements? (Email/Discord is also fine) The more requirements I know, the better will be the bundler

@kdy1 Sure, you can find me and my team on discord. Mine is `__H#7510`

**Pull request merged**
