### PR TITLE
Build FreeBSD binary

### PR DESCRIPTION
**Pull request by Brooooooklyn**

### CODE REVIEW

**Comment by kdy1** [comment]
Thanks a lot!

**Comment by kdy1** [comment]
cc @Brooooooklyn 
The build is failing with a rsync error.

https://github.com/swc-project/swc/runs/2703996836?check_suite_focus=true

**Comment by Brooooooklyn** [comment]
Oh it's never happened before, please retry the pipeline and see if this was a random error

**Comment by kdy1** [comment]
Oh, it was a random error.
I actually tried again before cc, but it failed. Anyway, thank you!

**Pull request merged**
