### PR TITLE
Support for parsing parameter decorators

### PR DESCRIPTION
**Pull request by dsherret**
I took a quick stab at an initial implementation in hopes that we could start working from here. Would really like to get this in swc.

Note: This is a parsing only commit. I have not looked at transformations at all.

Do you have any suggestion for the AST?

**TypeScript**

image

**ESTree**

image

For #750

### CODE REVIEW

**Comment by yharaskrik** [comment]
Any status on this? I discovered SWC and played around building our Nest app but we obviously have parameters in a lot of function calls (in Controllers).

**Comment by kdy1** [comment]
@yharaskrik
Hmm... I'll do this at the weekend. It's not a hard issue, but I postponed it mainly because I didn't know any use case of annotations on parameters.

**Comment by yharaskrik** [comment]
I'm not aware of anywhere else that uses it other that Nest and Angular. Both use decorators inside function params and constructors.

**Comment by kdy1** [comment]
Hmm... It's hard to determine where to store decorators.
I think creating a new type `Param` would be better than adding decorators to ident / array pat / etc...

**Comment by kdy1** [comment]
Closing in favor of #775

**Comment by dsherret** [comment]
@kdy1 thanks for doing the transformation work on this! Would you be able to add me on that commit as a co-author for doing the parsing and investigation work? It seems github didn’t keep track of it https://help.github.com/en/github/committing-changes-to-your-project/creating-a-commit-with-multiple-authors

**Comment by kdy1** [comment]
@dsherret I did it and [seems like it's applied](https://github.com/swc-project/swc/commits/master)

(I don't think force pushing is a good idea, but I think it is a correct thing to do)

**Comment by dsherret** [comment]
@kdy1 awesome. Thanks so much!

**Comment by yharaskrik** [comment]
Amazing! Thank you! Once a release is cut with it I'll give it another try!

**Pull request closed without merging**
