### PR TITLE
build(swc/core): fix dependency version

### PR DESCRIPTION
**Pull request by kwonoj**
**Description:**

latest `ecma_utils` build fails with 

```
 no method named `without_loc` found for struct `swc_ecma_ast::Ident` in the current scope
   --> /Users/ojkwon/.cargo/registry/src/github.com-1ecc6299db9ec823/swc_ecma_utils-0.100.1/src/function/fn_env_hoister.rs:743:22
    |
743 |             name: id.without_loc().into(),
    |                      ^^^^^^^^^^^ method not found in `swc_ecma_ast::Ident`
```

Due to version mismatch after https://github.com/swc-project/swc/pull/5569. PR bumps up version to fix issues.

**BREAKING CHANGE:**

**Related issue (if exists):**

### CODE REVIEW

**Comment by kwonoj** [comment]
This requires releasing new `@swc/core`.

**Review by kdy1 — APPROVED** [review]
Thanks!

---
swc-bump:
 - swc_core

**Review by kdy1 — CHANGES_REQUESTED** [review]
There's conflict

**Comment by kwonoj** [comment]
OK, rebased PR.

**Review by kdy1 — APPROVED** [review]

**Pull request merged**
