### PR TITLE
ci(actions): include swc_cli into optional deps package

### PR DESCRIPTION
**Pull request by kwonoj**
**Description:**
This PR continues CLI implementation, update publish script to each platform specific optional dep to include cli binary as well. Main entrypoint (@swc/cli) and optional dep doesn't point to those binary yet, so this is safe from any breaking changes. 

To conform with existing artifact packaging I did small bend over to copy release binary into specific platform path side by side to node bindings.

**Related issue (if exists):**

- https://github.com/swc-project/swc/issues/1589

### CODE REVIEW

**Review by kdy1 — APPROVED** [review]
LGTM, thanks!

**Review by alexeagle — COMMENTED** [review]
Hey OJ - should this PR have caused the new CLI binary to appear on https://github.com/swc-project/swc/releases ?  I still only see node bindings there. We'd like to benchmark the pure-rust CLI under Bazel :)

**Comment by kwonoj** [comment]
@alexeagle We'll need it but afaik it's not yet included via this PR. For now, you can directly access included binary in `@swc/core`'s native pkg or download it via cdns like unpkg.com. 

I'll try to peek this.

**Comment by kwonoj** [comment]
I wouldn't say it is wrong - please refer announcements that it is currently an experiemental approach to test cli & its deployment mechanism. It is indeed a possible burden who won't need cli binary, reason we'd like to try to couple of different possible approaches to find a suitable way.

**Pull request merged**
