### PR TITLE
refactor(css/parser): refactor

### PR DESCRIPTION
**Pull request by alexander-akait**
**Description:**

Simplify code + prepare for new improvements and fixes inside parser to be align with spec + tests to verify 

**BREAKING CHANGE:**

Yes

**Related issue (if exists):**

No

### CODE REVIEW

**Comment by alexander-akait** [comment]
@kdy1 Fixed

**Comment by kdy1** [comment]
There's a merge conflict

**Comment by alexander-akait** [comment]
@kdy1 Done :+1:

**Review by kdy1 — APPROVED** [review]
Thank you!

---

swc-bump:
 - swc_css_ast --breaking

**Pull request merged**
