### PR TITLE
chore: upgrade arbitrary crate to v1

### PR DESCRIPTION
**Pull request by punkeel**
Upgrade the arbitrary (fuzzing) crate to v1. This is a major bump, but the API hasn't changed much. We only need to add lifetimes in some impl blocks.

### CODE REVIEW

**Comment by kdy1** [comment]
Do you actually need this?

**Comment by punkeel** [comment]
I tried using `swc` + `cargo-fuzz` for an experiment, and was blocked by the different `arbitrary` versions used. The experiment didn't go the way I wanted it to, so I may not "need" it ... but I figured I could still contribute this to swc :-)

Up to you, I won't mind too much if you reject this PR.

**Review by kdy1 — APPROVED** [review]
Thanks!
I asked it just because this is a technically breaking change :)

**Comment by punkeel** [comment]
Thanks for merging it :-)
And, indeed, it technically is a breaking change. Good catch, I totally missed it!

**Pull request merged**
