### PR TITLE
Feat compress transform function

### PR DESCRIPTION
**Pull request by alexander-akait**
**Description:**

feat port https://github.com/cssnano/cssnano/tree/master/packages/postcss-reduce-transforms

**BREAKING CHANGE:**

No

**Related issue (if exists):**

No

### CODE REVIEW

**Review by kdy1 — APPROVED** [review]
Thank you!

---

swc-bump:
 - swc_css_minifier

**Review by kdy1 — CHANGES_REQUESTED** [review]
Can you rebase?

**Comment by alexander-akait** [comment]
@kdy1 Can you review?

**Review by kdy1 — APPROVED** [review]
Of course, I actually reviewed some files previously.

---

swc-bump:
 - swc_css_minifier

**Pull request merged**
