### PR TITLE
Use rkyv in strict mode

### PR DESCRIPTION
**Pull request by djkoloski**
*Note:* This PR turns on an rkyv feature that requires support from `wasmer`. I haven't done the work to push `strict` through `wasmer-types` yet.

**Description:**

By default, rkyv data may change format across Rust compiler versions. Enabling the `strict` feature guarantees that the data format will not change over time.

**Motivation:**

The end-to-end `plugins.compat.test.js` is failing on nightly.

**BREAKING CHANGE:**

Any rkyv-serialized data may change format. I'm not sure if SWC has an ABI or not, so this may not actually be considered a breaking change.

**Related issue (if exists):**

https://github.com/rkyv/rkyv/issues/338

### CODE REVIEW

**Comment by kwonoj** [comment]
Oh this looks nice. Any elaborations may able to share what strict mode supposed to do & why it is not default behavior?

**Comment by kwonoj** [comment]
Tracking: https://github.com/wasmerio/wasmer/issues/3695

**Comment by kdy1** [comment]
Closing as https://github.com/swc-project/swc/pull/7197 merged this

**Comment by kdy1** [comment]
Thank you!

**Pull request closed without merging**
