### PR TITLE
feat: Introduce is_module unknown

### LINKED ISSUE #2541: Is swc support options like Babel-loader "sourceType":  "unambiguous" ?
**Describe the feature**
Is there an option like babel-loader `sourceType: "script" | "module" | "unambiguous"`

**Babel plugin or link to the feature description**
https://babeljs.io/docs/en/options#sourcetype

**Additional context**

### PR DESCRIPTION
**Pull request by sventschui**
This PR introduces the `isModule: 'unknown'` flag to auto-detect whether a program is a module or script.

Open points:

- [x] Add tests
- [x] Figure out why test for issue 706 is failing (currently commented out)
- [x] Figure out why a bunch of other tests are failing too

Resolves #2541

### CODE REVIEW

**Review by Edge00 — APPROVED** [review]

**Review by Edge00 — APPROVED** [review]

**Comment by kdy1** [comment]
I'll review this today. Sorry for the delay.

**Review by kdy1 — CHANGES_REQUESTED** [review]
code changes look fine to me, thanks!

I have a very small issue.
Can you add some tests to `node-swc/__tests__`?

Due to config merging, verifying it using only rust code is impossible.

**Review by kdy1 — APPROVED** [review]
LGTM, thanks!

**Comment by Edge00** [comment]
@sventschui Thank you for your awesome work! I have a little question. What the interface will be in swc-loader ?

**Comment by sventschui** [comment]
@Edge00 `isModule: 'unknown'` should do the job the swc-loader. Let me know if it doesn't.

But beware that you'll probably run into these issues with scripts:
- #1814 
- preset-env is not yet supported for scripts (https://github.com/swc-project/swc/blob/main/crates/swc_ecma_preset_env/src/lib.rs#L413)

**Pull request merged**
