### PR TITLE
fix(ecma/transform/compat): constructor

### PR DESCRIPTION
**Pull request by Austaras**
This is needed for #3474

### CODE REVIEW

**Comment by Austaras** [comment]
This pr does:
- use `SuperFieldAccessFolder` for super field in constructor
- fix bug when constructor has same name variable as class name
- fix bug when function in constructor call super or have this

**Review by kdy1 — COMMENTED** [review]
I checked test file changes, and it looks fine.
But I'm not sure about the purpose of this PR. Can you describe a bit?

**Comment by Austaras** [comment]
> This pr does:
> 
>     * use `SuperFieldAccessFolder` for super field in constructor
> 
>     * fix bug when constructor has same name variable as class name
> 
>     * fix bug when function in constructor call super or have this
* use `SuperFieldAccessFolder` for super field in constructor, so I doesn't have to write loose mode twice in #3474
* [fix this](https://play.swc.rs/?version=1.2.133&code=H4sIAAAAAAAAA0vOSSwuVnBUqOblUgCC5Py84pKi0uSS%2FCINTZggCJQlFik4Irggdfk5qXo5%2BekajpoQ8VperloAMiolQ08AAAA%3D&config=H4sIAAAAAAAAA0WMTQrEIAxG75K1286id5hDBCctFv9IUhgR714tlu7C915ehUMsrBUyshCPS0pU%2FMMKZAOKZZcVTNf6tKEXagYUeScdiiyd%2BZSEJjUQXHRbGSWbQmYSeRHG3T9m66GQfucYKmjJdAc%2F0N7G%2FHPynaLySe0Cj9ke9LUAAAA%3D)
* [fix this](https://play.swc.rs/?version=1.2.133&code=H4sIAAAAAAAAA0vOSSwuVnBUSK0oSc1LKVZwqublUlBIzs8rLikqTS7JL9LQVAALKSgUlxakFuml5ecraGtbIwslJRYpaNsqGBoZg4VreblqAb69JnxXAAAA&config=H4sIAAAAAAAAA0WMTQrEIAxG75K1286id5hDBCctFv9IUhgR714tlu7C915ehUMsrBUyshCPS0pU%2FMMKZAOKZZcVTNf6tKEXagYUeScdiiyd%2BZSEJjUQXHRbGSWbQmYSeRHG3T9m66GQfucYKmjJdAc%2F0N7G%2FHPynaLySe0Cj9ke9LUAAAA%3D)

**Comment by Austaras** [comment]
The whole thing around class is quite a mess, no need to hurry

**Comment by kdy1** [comment]
Sorry, I missed it. Thanks!

**Review by kdy1 — APPROVED** [review]
Thank you!

**Pull request merged**
