### PR TITLE
refactor(es/minifier): Pre-calculate `reassigned`

### PR DESCRIPTION
**Pull request by Austaras**
**Description:**

**BREAKING CHANGE:**

**Related issue (if exists):**

### CODE REVIEW

**Comment by Austaras** [comment]
The changed minified test can be reduced to
old
```js
export function ez(n, t, e) {
  var r;
  try {
      iP(this, tU(n, t, e));
  } catch (n) {
      if (nG(n = tg(n), 14)) throw r = n, new nw(r.f);
      throw n;
  }
}
```
new
```js
export function ez(n, t, e) {
  try {
      iP(this, tU(n, t, e));
  } catch (n) {
      if (nG(n = tg(n), 14)) throw new nw(r.f);
      throw n;
  }
}
```

**Review by jridgewell — APPROVED** [review]

**Review by jridgewell — CHANGES_REQUESTED** [review]
Wait a minute:

```diff
--- A/app.kaleidoscope.kaleidoscope_dynamicfile_9DF500FA-7A80-4CDC-A435-EEE7EF3B114D-81211-00001730D248EF88.txt
+++ B/app.kaleidoscope.kaleidoscope_dynamicfile_B3D1C7AE-EA28-4184-BE77-406DEECA9390-81211-00001730D8548196.txt
@@ -1,10 +1,9 @@
 export function ez(n, t, e) {
-  var r;
   try {
       iP(this, tU(n, t, e));
   } catch (n) {
+      if (nG(n = tg(n), 14)) throw new nw(r.f);
-      if (nG(n = tg(n), 14)) throw r = n, new nw(r.f);
       throw n;
   }
 }
\ No newline at end of file
```

That `throw new nw(r.f)` is now an error, because `r` isn't assigned anymore?

**Comment by Austaras** [comment]
Sorry, I write it wrong.

**Review by jridgewell — APPROVED** [review]

**Review by kdy1 — APPROVED** [review]
Thank you!

---

swc-bump:
  - swc_ecma_usage_analyzer

**Pull request merged**
