### PR TITLE
Feat improve minify

### PR DESCRIPTION
**Pull request by alexander-akait**
**Description:**

Bugfix:
1. Parse custom property according to latest spec changes, i.e. `--foo:;` and `--foo: ;` are same
2. Namespace output

Improvements:
1. Minify `@media` and `@supports`
2. Avoid spaces in values when it is unnecessary
3. Fix printing in normal mode
4. Many tests to avoid regressions in future

**BREAKING CHANGE:**

No

**Related issue (if exists):**

No

### CODE REVIEW

**Review by kdy1 — APPROVED** [review]
Seems like we can improve a bit more, but I think it's not urgent. (It's a guess based on the test reference files)
Thanks!

**Comment by kdy1** [comment]
Can you rebase?

**Comment by alexander-akait** [comment]
WIP

**Comment by alexander-akait** [comment]
@kdy1 Done

**Review by kdy1 — APPROVED** [review]
Thank you!

**Pull request merged**
