### PR TITLE
feat: compress deg to zero

### PR DESCRIPTION
**Pull request by alexander-akait**
**Description:**

feat - compress `<Angle>` with `0` value to `0`

**BREAKING CHANGE:**

No

**Related issue (if exists):**

No

### CODE REVIEW

**Review by kdy1 — APPROVED** [review]
swc-bump:
 - swc_css_minifier

**Comment by yisibl** [comment]
This may not be very safe:

https://twitter.com/tabatkins/status/676297504237879296
> And Chrome/Edge's behavior is a bug. "0" (without a unit) can only be used for lengths, not angles or anything else.

**Comment by yisibl** [comment]
Sorry, I misremembered, the specification was updated later, the angle value can omit the unit: https://github.com/cssdream/css-creating/issues/14

**Comment by alexander-akait** [comment]
@yisibl Yes, but there is exception, it is legacy transfrom functions and they are supported `0` https://www.w3.org/TR/css-transforms-2/#three-d-transform-functions, we don't replace `0` in declarations

**Comment by alexander-akait** [comment]
So we replace them on `0` only for these cases

**Comment by yisibl** [comment]
In the current spec, CSS Gradients can be omitted as well. But I don't know when Firefox implemented it, so I think swc can be safer to leave it out for this case.

It's really a rabbit hole.

**Comment by alexander-akait** [comment]
@yisibl https://tomhodgins.com/demo/cssom/, open firefox and write:
```
.class6{transform:rotateX(0)}
```

Works fine

**Comment by yisibl** [comment]
Firefox 55 fixed “Zero (0) angle value without degree unit is not correctly interpreted in linear-gradient” https://bugzilla.mozilla.org/show_bug.cgi?id=1363292

image
https://developer.mozilla.org/en-US/docs/Web/CSS/gradient/linear-gradient()

**Comment by alexander-akait** [comment]
Yep, but we don't convert to `0` in `linear-gradient`, only in transform functions

**Comment by yisibl** [comment]
That's great, thanks for the discussion.

**Pull request merged**
