### PR TITLE
feat(html/minifier): sort attributes

### PR DESCRIPTION
**Pull request by alexander-akait**
**Description:**

Sort attributes for better gzip

**BREAKING CHANGE:**

No

**Related issue (if exists):**

No

### CODE REVIEW

**Review by kdy1 — APPROVED** [review]
Thank you!

---

swc-bump:
 - swc_html_minifier

**Review by kdy1 — CHANGES_REQUESTED** [review]
Can you rebase, please?

**Review by kdy1 — DISMISSED** [review]

**Comment by alexander-akait** [comment]
@kdy1 I will rebase after omit tag commit, because we will have fail here on CI

**Comment by alexander-akait** [comment]
@kdy1 Found how we can do it better and better gzip, I am investigating it to check

**Comment by alexander-akait** [comment]
@kdy1 ready for review

**Comment by alexander-akait** [comment]
@kdy1 Rebase too :star:

**Review by kdy1 — APPROVED** [review]
Thanks!

---

swc-bump:
 - swc_html_minifier --breaking

**Pull request merged**
