### PR TITLE
Fix TS types for AST nodes

### PR DESCRIPTION
**Pull request by overlookmotel**
**Description:**

This PR fixes various inaccuracies in the TS type definitions for AST nodes. They seem to have got out of sync over time.

These discrepancies were identified programmatically based on the model of the Rust types I've made for #2175. So this PR should be definitive and bring the TS types completely up to date.

NB Some of the changes just re-order fields and enum options. This doesn't make a difference to correctness of the types. But now they're all consistent with field order in the Rust types, which will maybe make it easier to spot when further changes are required in future.

**Related issue (if exists):**

n/a

### CODE REVIEW

**Review by kdy1 — CHANGES_REQUESTED** [review]
CI failed

**Comment by overlookmotel** [comment]
Yes, the types are now correct, but their usage in `node-swc/src/Visitor.ts` is now wrong!

**Comment by overlookmotel** [comment]
I've made changes to `Visitor.ts` to use the updated types, so TS check now passes.

There are likely a lot of inaccuracies remaining in `Visitor.ts`, but I'll try to fix them another time. At least the types are correct now.

**Review by kdy1 — APPROVED** [review]
Thank you!

**Pull request merged**
