### PR TITLE
feat(css/parser): normalize at-rules

### PR DESCRIPTION
**Pull request by alexander-akait**
**Description:**

Here:
- normalize ident to lowercase where it is allowed by spec
- improve AST for custom media by spec (comment in code)
- more tests

**BREAKING CHANGE:**

Yes

**Related issue (if exists):**

No

### CODE REVIEW

**Review by kdy1 — APPROVED** [review]
swc-bump:
 - dbg-swc

**Review by kdy1 — COMMENTED** [review]
Please merge PRs that breaks AST in future

**Review by kdy1 — CHANGES_REQUESTED** [review]
CI failed

**Comment by alexander-akait** [comment]
@kdy1 Rebased and fixed

**Review by kdy1 — DISMISSED** [review]

**Comment by alexander-akait** [comment]
@kdy1 Rebased and fixed

**Review by kdy1 — APPROVED** [review]

**Pull request merged**
