### PR TITLE
fix(swc): Fix  bugs

### LINKED ISSUE #1383: declare global is not stripped correctly anymore
**Describe the bug**

SWC does not strip `declare global { }` from output code anymore.

**Input code**

```ts
declare global {
  // @ts-ignore
  const process: Process;
}

export {}
```

**Config**

Deno

**Expected behavior**

This is TSC output:

```js
export {};
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiIiwic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsiZmlsZTovLy9ob21lL2x1Y2FjYXNvbmF0by9mb28udHMiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IiJ9
```

This is swc_ecmascript 0.17.1
```js
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IiJ9
```

This is swc_ecmascript 0.18.8
```js
var global;
(function(global1) {
    // @ts-ignore
    const process;
})(global || (global = {
}));
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbIjxmaWxlOi8vL2hvbWUvbHVjYWNhc29uYXRvL2Zvby50cz4iXSwic291cmNlc0NvbnRlbnQiOlsiZGVjbGFyZSBnbG9iYWwge1xuICAvLyBAdHMtaWdub3JlXG4gIGNvbnN0IHByb2Nlc3M6IFByb2Nlc3M7XG59XG5cbmV4cG9ydCB7fSJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiSUFBQSxNQUFBOztBQUNBLE1BQUEsV0FBQTtVQUNBLE9BQUE7R0FGQSxNQUFBLEtBQUEsTUFBQSJ9
```

**Version**

swc_ecmascript 0.18.8

### PR DESCRIPTION
**Pull request by kdy1**
# Tasks

swc_ecma_ast:
 - Support import assertions for exports.

swc_ecma_parser:
 - Support import assertions for exports.

swc_ecma_transform_typescript:
 - Strip `declare globals` correctly. (Closes #1383)

spack:
 - Re-enable multi-entry tests.

### CODE REVIEW

**Comment by wycats** [comment]
@kdy1 is multi-entry currently broken? I was trying to use it and I get a hang followed by a:

```
FATAL ERROR: MarkCompactCollector: young object promotion failed Allocation failed - JavaScript heap out of memory
```

**Comment by kdy1** [comment]
@wycats Yes, but `JavaScript heap out of memory ` seems unrelated to the bug.

**Comment by wycats** [comment]
@kdy1 is there anything I can do to help you reproduce it?

**Comment by kdy1** [comment]
@wycats Is your project open source?
If not, can you share your `spack.config.js`?

**Pull request merged**
