### PR TITLE
chore: refine error report text

### PR DESCRIPTION
**Pull request by magic-akari**
**Description:**

**BREAKING CHANGE:**

**Related issue (if exists):**

### CODE REVIEW

**Comment by kdy1** [comment]
How do you think about https://github.com/swc-project/swc/pull/3946?
Or alternatively, updating emitter writer to match recent version of rustc

**Review by kdy1 — APPROVED** [review]
LGTM, regardless of the new error reporter.

Thank you!

---

swc-bump:
 - swc_common
 - swc_ecma_lints

**Comment by magic-akari** [comment]
I didn't know you moved to the miette.
In the last two days I tried to follow the latest rustc but did not manage to migrate.
Rust has its own complexity and using a library like miette is a better choice.

**Comment by kdy1** [comment]
Migration to miette will be gradual, as it requires lots of snapshot updates to rust-side users of swc

**Pull request merged**
