### PR TITLE
chore: Publish `v1.3.33`

### PR DESCRIPTION
**Pull request by realtimetodie**

### CODE REVIEW

**Comment by realtimetodie** [comment]
Related

- https://github.com/aspect-build/rules_swc/pull/149

**Comment by realtimetodie** [comment]
@kdy1

**Comment by kdy1** [comment]
I'll publish a new version after merging https://github.com/swc-project/swc/pull/6906 and https://github.com/swc-project/swc/pull/6899

**Review by kdy1 — APPROVED** [review]
swc-bump:
 - dbg-swc

**Pull request merged**
