### PR TITLE
refactor(css/prefixer): more js_word

### PR DESCRIPTION
**Pull request by alexander-akait**
**Description:**

Use `js_word`

**BREAKING CHANGE:**

No

**Related issue (if exists):**

No

### CODE REVIEW

**Comment by alexander-akait** [comment]
@kdy1 Test fixed

**Review by kdy1 — APPROVED** [review]
swc-bump:
 - swc_atoms
 - swc_css_prefixer

**Review by kdy1 — CHANGES_REQUESTED** [review]
There's a merge conflict

**Comment by alexander-akait** [comment]
@kdy1 Rebased too

**Comment by alexander-akait** [comment]
Rebased

**Review by kdy1 — APPROVED** [review]
swc-bump:
 - swc_atoms
 - swc_css_prefixer

**Pull request merged**
