### PR TITLE
buiild(bindings/wasm): Fix Wasm build

### LINKED ISSUE #7663: `@swc/wasm` releases are missing since `1.3.66`
_Originally posted by @SimulatedGREG in https://github.com/swc-project/swc/discussions/7632#discussioncomment-6440672_

---

I'm running into this as well. I'm running on FreeBSD, and am aware that the `@swc/wasm` build will be used. But I noticed that the last few releases are missing a wasm build 😱. It appears they failed building.

Latest `@swc/wasm` is `1.3.66`, but latest `@swc/core` is `1.3.69`.

https://github.com/swc-project/swc/actions/runs/5538355336/jobs/10108207111

### PR DESCRIPTION
**Pull request by kdy1**
**Description:**

**Related issue:**

 - Closes #7663.

### CODE REVIEW

**Review by kdy1 — COMMENTED** [review]
swc-bump:
 - dbg-swc

**Comment by magic-akari** [comment]
I still get something wrong with getrandom.
https://github.com/magic-akari/jest_workaround/actions/runs/5587657701/jobs/10213312237?pr=52

**Comment by magic-akari** [comment]
I changed the compilation target from `wasm32-unknown-unknown` to `wasm32-wasi` to avoid the compilation error.

**Comment by Jack-Works** [comment]
still have error for my plugin:

```
Error: failed to handle: failed to invoke plugin: failed to invoke plugin on 'Some("virtual-module.js")'

Caused by:
    0: failed to invoke `swc_transformer_static_module_record.wasm` as js transform plugin at swc_transformer_static_module_record.wasm
    1: Error while importing "__wbindgen_placeholder__"."__wbg_crypto_c48a774b022d20ac": unknown import. Expected Function(FunctionType { params: [I32], results: [I32] })
```

**Comment by kdy1** [comment]
@Jack-Works It's completely unrelated

**Comment by Jack-Works** [comment]
> @Jack-Works It's completely unrelated

I found I need `getrandom = { version = "0.2", features = ["js"] }` to build the wasm, and it cause the `Error while importing "__wbindgen_placeholder__"."__wbg_crypto_c48a774b022d20ac": unknown import. Expected Function(FunctionType { params: [I32], results: [I32] })` error.

If I remove this feature, it directly fails to compile:

```
> cargo build --release --target wasm32-unknown-unknown

   Compiling getrandom v0.2.10
error: the wasm*-unknown-unknown targets are not supported by default, you may need to enable the "js" feature. For more information see: https://docs.rs/getrandom/#webassembly-support
   --> getrandom-0.2.10/src/lib.rs:285:9
    |
285 | /         compile_error!("the wasm*-unknown-unknown targets are not supported by \
286 | |                         default, you may need to enable the \"js\" feature. \
287 | |                         For more information see: \
288 | |                         https://docs.rs/getrandom/#webassembly-support");
    | |________________________________________________________________________^

error[E0433]: failed to resolve: use of undeclared crate or module `imp`
   --> getrandom-0.2.10/src/lib.rs:341:9
    |
341 |         imp::getrandom_inner(dest)?;
    |         ^^^ use of undeclared crate or module `imp`

For more information about this error, try `rustc --explain E0433`.
```

But I did not use `getrandom`. Here is my dependency list:

```toml
[dependencies]
serde = "1"
serde_json = "1"
swc_core = { version = "0.79.16", features = [
    "ecma_ast",
    "ecma_utils",
    "ecma_visit",
    "ecma_plugin_transform",
    "swc_atoms",
    "swc_plugin",
    "testing_transform",
] }
testing = "0.33.5"
tracing = { version = "0.1.37", features = ["release_max_level_off"] }
```

is there anything unneeded for a wasm plugin?

**Comment by Jack-Works** [comment]
I opened a new issue https://github.com/swc-project/swc/issues/7729

**Pull request merged**
