### PR TITLE
feat(bindings/swc_cli): Append the sourceMappingURL= soruce map file …

### PR DESCRIPTION
**Pull request by realtimetodie**
Appends a sourceMappingURL comment to the end of the output, containing an URL to the generated source map file.

Example

```bash
$ swc compile input.js --out-file=output.js --source-maps=true
```

Output

```
output.js
output.js.map
```

Show the last line of the generated output.js file

```
$ tail -n=1 output.js
//# sourceMappingURL=output.js.map
```

Summary

- Minimal implementation
- Free of breaking changes to @swc/cli (in comparison to https://github.com/swc-project/swc/pull/6817)

Related

- https://github.com/swc-project/swc/discussions/3859
- https://github.com/swc-project/swc/discussions/6479
- https://github.com/aspect-build/rules_swc/issues/146

### CODE REVIEW

**Comment by realtimetodie** [comment]
@kdy1

**Review by kdy1 — APPROVED** [review]
Thank you!

---

swc-bump:
 - dbg-swc

**Comment by kdy1** [comment]
I published a new version of `swc_cli`

**Comment by realtimetodie** [comment]
Thank you. For Bazel [rules_swc](https://github.com/aspect-build/rules_swc/blob/main/swc/private/versions.bzl), we need an additional binary release https://github.com/swc-project/swc/releases/.

**Comment by realtimetodie** [comment]
Thank you. For Bazel [rules_swc](https://github.com/aspect-build/rules_swc), we need an additional binary release. Bazel uses the attachments from the GitHub release API https://github.com/swc-project/swc/releases/.

https://github.com/aspect-build/rules_swc/blob/main/swc/private/versions.bzl

**Pull request merged**
