### PR TITLE
refactor(common): Change reserved `BytePos` to `u32::MAX`

### PR DESCRIPTION
**Pull request by kdy1**
**Description:**

**Related issue (if exists):**

---

cc @bartlomieju @dsherret 

Let's see which crate breaks

### CODE REVIEW

**Comment by kdy1** [comment]
I decided not to do this as this causes some regression in source map.
I tried patching codes for sourcemap generation but I got no luck

**Comment by dsherret** [comment]
@kdy1 does that indicate that some code is fragile because it is not explicitly relying on spans being dummy? Will that be fixed and this solution still explored?

**Comment by kdy1** [comment]
Yeah, I think those codes should be updated to use `is_dummy` instead.
I may retry this in the future, but I'm not sure

**Comment by kdy1** [comment]
Postponing as `SourceMap` is written under assumption `BytePos(0)` is dummy.
It compares `BytePos` using `cmp::max` or `cmp::min`

**Pull request closed without merging**
