### PR TITLE
fix(es/minifier): Abort function inliner if `keep_fnames` is `true`

### PR DESCRIPTION
**Pull request by kdy1**
**Description:**

**Related issue:**

 - https://github.com/vercel/next.js/issues/56408

### CODE REVIEW

**Comment by kdy1** [comment]
# Investigation

This is a bug of name mangler. `ie` points to different `ie` when the mangler is enalbed.

**Review by kdy1 — COMMENTED** [review]
swc-bump:
 - swc_ecma_minifier

**Review by kdy1 — COMMENTED** [review]
swc-bump:
 - swc_ecma_minifier

**Comment by kdy1** [comment]
Marking as draft because it fixes the bug but the size regression looks too much.

```
default: 89197 bytes
new: 99631 bytes

```

**Review by jridgewell — APPROVED** [review]

**Pull request merged**
