### PR TITLE
String literal line terminator fix when parsing JSON

### PR DESCRIPTION
**Pull request by tmpfs**
This is a proposed fix for https://github.com/swc-project/swc/issues/1754.

Depends on: https://github.com/tc39/test262-parser-tests/pull/30 for parser tests to pass.

Only applies to string literals and further consideration should be given to RegExp parsing and string template parsing.

The `is_line_break()` function has been renamed to `is_line_terminator()` and `is_line_break()` now only tests for carriage return and line feed.

There are other places in the code where `\u2028` and `\u2029` are matched but I am not sure about these conditions and they should be reviewed separately.

### CODE REVIEW

**Comment by tmpfs** [comment]
@kdy1, we got the `test262-parser` tests updated and I have updated the submodule commit hash and verified that the `ecmascript/parser` tests now pass :+1:

**Comment by vovacodes** [comment]
@kdy1 is there anything there preventing this PR from being merged? We are running into this problem in our project and willing to help landing it if there's anything we can do

**Comment by kdy1** [comment]
I didn't merged because tests are failing.
I'll invert this pr and merge it.

**Comment by vovacodes** [comment]
@kdy1 you're a 🌟 Thanks, man!

**Pull request merged**
