### PR TITLE
fix(css/parser): at-rules can be lowercased

### PR DESCRIPTION
**Pull request by alexander-akait**
Name thing in CSS can be lowercased, I can fix more here and in other PRs

### CODE REVIEW

**Comment by alexander-akait** [comment]
I noticed in many PRs they raise versions, it would be nice to show how to do it, not found it in https://github.com/swc-project/swc/blob/master/CONTRIBUTING.md

**Comment by kdy1** [comment]
You can run `cargo mono bump swc_css_parser` after running `cargo install cargo-mono`.

**Comment by alexander-akait** [comment]
@kdy1 thanks, done

**Comment by alexander-akait** [comment]
@kdy1 Also I want to help you with CSS parser/ast/codegen/etc and help to implement autoprefixer/minimizer/etc features (time to migrate from those tools), any roadmap? Maybe you have discord/slack for swc? Have experience with stylelint/postcss/CSS bundling/cssnano and etc.

**Comment by kdy1** [comment]
Thanks!
I'm going to port autoprefixer and css minifier, but I don't have any roadmap.

swc uses github discussions, but if there's a reason you prefer other methods, I can make one.

**Review by kdy1 — APPROVED** [review]
LGTM. Thanks!

**Comment by alexander-akait** [comment]
@kdy1 I am fine with github, but I think discord or slack will be better for faster communications

I'll start by migrating tests from postcss and fixes in parser/ast/codegenerator for now. Simple minimizer is not hard to implement, we can start with removing empty spaces/replace colors on more small variants/removing empty rules, it is safe transformations. In long term would like to deprecate cssnano in favor that solution

**Comment by kdy1** [comment]
I made one. 
Please join at https://discord.gg/fDXWFkM2jY

**Comment by alexander-akait** [comment]
Thanks

> This invite may be expired, or you might not have permission to join.

Weird...

**Comment by kdy1** [comment]
I made it again
https://discord.gg/GnHbXTdZz6

**Pull request merged**
