### PR TITLE
feat(bundler): Extract import / export analyzer

### PR DESCRIPTION
**Pull request by kdy1**

### CODE REVIEW

**Comment by tmpfs** [comment]
This seems like a good idea to extract these structs and functionality into `swc_bundler_analysis` so I can depend upon them but I am unsure the correct way to build up the `Imports` and `Exports` structs.

Should I call `Bundler::resolve_imports()` and `Bundler::resolve_exports()` after I have created `RawImports` and `RawExports`?

**Comment by tmpfs** [comment]
Looking again it appears that all of these should be public for my task:

* `extract_import_info()` / `extract_export_info()`
* `resolve_imports()` . `resolve_exports()`

In addition I know that you closed [this PR](https://github.com/swc-project/swc/pull/1770) without merging but I think it would be really helpful to get those changes in too. I do need to call `load_transformed()` to walk the module graph :+1:

**Comment by kdy1** [comment]
I see. I'll extract those structs and methods too.

**Comment by kdy1** [comment]
I looked at the function codes and noticed that `extract_import_info` and `extract_export_info` are not worth exporting.
Those only invoke visitor.

**Comment by tmpfs** [comment]
Hi @kdy1, is this going to be merged?

I am working on this right now and am very close to getting the `RawImports` and hope soon to have the `Imports` too with a little more assistance.

**Comment by tmpfs** [comment]
So I think i need access to `Scope` in order to mimic what the `Bundler` does when implementing the `Handler` trait.

This is what I have so far:

```rust
//! Helper to extract imports from a module
use swc::Compiler;
use swc_common::{
    FileName, Mark, SyntaxContext,
};
use swc_atoms::JsWord;
use swc_ecma_ast::Module;
use swc_bundler_analysis::{
    handler::Handler as ModuleHandler,
    import::{ImportHandler, RawImports},
    id::ModuleId,
};
use spack::resolvers::NodeResolver;
use swc_bundler::Resolve;
use swc_ecma_visit::VisitMutWith;
use swc_bundler::bundler::scope::Scope;

pub struct ImportExtractor {
    scope: Scope,
    resolver: Box<dyn Resolve>,
    require: bool,
}

impl ImportExtractor {

    pub fn new(require: bool) -> Self {
        Self {
            scope: Default::default(),
            resolver: Box::new(NodeResolver::new()),
            require,
        }
    }

    /// This method de-globs imports if possible and colorizes imported values.
    pub(crate) fn extract_import_info(
        &self,
        compiler: &Compiler,
        path: &FileName,
        module: &mut Module,
        module_local_mark: Mark,
    ) -> RawImports {
        compiler.run(|| {
            let mut v = ImportHandler {
                module_ctxt: SyntaxContext::empty().apply_mark(module_local_mark),
                path,
                handler: &self,
                top_level: false,
                info: Default::default(),
                usages: Default::default(),
                imported_idents: Default::default(),
                deglob_phase: false,
                idents_to_deglob: Default::default(),
                in_obj_of_member: false,
            };
            module.body.visit_mut_with(&mut v);
            v.deglob_phase = true;
            module.body.visit_mut_with(&mut v);

            v.info
        })
    }
}

impl ModuleHandler for &ImportExtractor {
    fn is_external_module(&self, module_specifier: &JsWord) -> bool {
        //self.config.external_modules.contains(module_specifier)
        false
    }

    fn resolve(&self, base: &FileName, src: &JsWord) -> Option<FileName> {
        self.resolver.resolve(base, src).ok()
    }

    fn get_module_info(&self, path: &FileName) -> (ModuleId, Mark, Mark) {
        self.scope.module_id_gen.gen(path)
    }

    fn supports_cjs(&self) -> bool {
        self.require
    }

    fn mark_as_cjs(&self, id: ModuleId) {
        self.scope.mark_as_cjs(id)
    }

    fn mark_as_wrapping_required(&self, id: ModuleId) {
        self.scope.mark_as_wrapping_required(id)
    }
}
```

**Comment by tmpfs** [comment]
One problem I ran into is this error:

```
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `#0`,
 right: `#1`: Exported names should have same (local) context as top-level module items
test/fixtures/static-module-record/main.js
ExportNamedSpecifier { span: Span { lo: BytePos(452), hi: BytePos(466), ctxt: #0 }, orig: Ident { span: Span { lo: BytePos(452), hi: BytePos(457), ctxt: #0 }, sym: Atom('aleph' type=inline), optional: false }, exported: Some(Ident { span: Span { lo: BytePos(461), hi: BytePos(466), ctxt: #0 }, sym: Atom('alpha' type=inline), optional: false }) }', /home/muji/git/consensys/swc/bundler/analysis/src/import.rs:516:17
```

For the moment I am working around it by commenting out the `debug_assert_eq!` but if you can tell me what I am doing wrong to cause the problem would be great, thanks!

**Comment by kdy1** [comment]
> Hi @kdy1, is this going to be merged?

I'll not merge this, as two-context system is an implementation detail of the bundler.

**Comment by kdy1** [comment]
The panic is about two-context system, and you can fix it by using non-modifing visitor

**Pull request closed without merging**
