### PR TITLE
bundler: Handle computed accesses correctly

### PR DESCRIPTION
**Pull request by kdy1**
swc_bundler:
 - Handle computed accesses to imports correctly.
 - Make planning deterministic.
 - Prefer exports over imports while planning.
 - Fix https://deno.land/x/oak@v6.3.1/examples/server.ts

### CODE REVIEW

**Comment by kdy1** [comment]
@kitsonk I think I fixed it. Can you try this branch?

**Comment by kdy1** [comment]
@kitsonk

Currently when I run the generated bundle, `await this.signal` at https://deno.land/std@0.74.0/async/mux_async_iterator.ts#L45 does not resolve.

**Comment by kdy1** [comment]
I fixed it and verified that 127.0.0.1 returns `Hello, world!`

**Comment by kitsonk** [comment]
🎉 🎉 🎉 🎉 

Yes, I can confirm master properly builds that bundle!!!

Thank you @kdy1 great work.

**Pull request merged**
