### PR TITLE
perf(es/parser): Use Cow for `_` in numeric literals

### PR DESCRIPTION
**Pull request by kdy1**
**Description:**

### CODE REVIEW

**Review by kdy1 — COMMENTED** [review]
swc-bump:
 - swc_ecma_parser

**Comment by Boshen** [comment]
Excuse me for the lack of knowledge here, but I don't see how this removes the allocation from `raw_val.replace('_', "")`? 

What I did for my lexer (copied from jsparagus) was to use the `Cow` technique, where we only own the string if there is a `_`.

**Comment by kdy1** [comment]
This PR does not remove allocation of `replace` call

**Comment by kdy1** [comment]
I'll remove it too

**Pull request merged**
