### PR TITLE
chore: Publish `v1.3.41` with swc_core `v0.69.11`

### PR DESCRIPTION
**Pull request by realtimetodie**

### CODE REVIEW

**Comment by realtimetodie** [comment]
Related

- https://github.com/aspect-build/rules_swc/pull/187

**Comment by kdy1** [comment]
Can you rebase/update?

**Comment by realtimetodie** [comment]
Successfully rebased with scw_core v0.69.11.

**Comment by realtimetodie** [comment]
Updated the commit message.

**Review by kdy1 — APPROVED** [review]
Thank you!

---

swc-bump:
 - dbg-swc

**Pull request merged**
