### PR TITLE
refactor(swc/ecma_ast): apply rkyv-bytecheck flag

### PR DESCRIPTION
**Pull request by kwonoj**
**Description:**

Reattempting #5798, but need addtional investigation for the build issue.

I couldn't repro it locally yet unfortunately so hard to dig where / what's happening exactly. When I tried, only one lint error (which seems harmless) were appear.

**BREAKING CHANGE:**

**Related issue (if exists):**

### CODE REVIEW

**Comment by kwonoj** [comment]
The steps I tried repro was

- Checkout PR
- run patch-section, apply path-based dep to `bindings/node`'s Cargo.tml
- `npm run build`

Something I miss or did incorrectly to repro? @kdy1

**Comment by kdy1** [comment]
I added required patch to reproduce

**Comment by kwonoj** [comment]
> I added required patch to reproduce

Oh wow thanks! 🏃 :digging:

**Comment by kdy1** [comment]
Oh I can't reproduce

**Comment by kwonoj** [comment]
:oh-no:

**Review by kdy1 — APPROVED** [review]
swc-bump:
 - ast_node
 - swc_plugin_proxy

**Pull request merged**
