### PR TITLE
feat(trace): add trace spans for es2015 transform

### PR DESCRIPTION
**Pull request by kwonoj**
**Description:**

Adding spans for es2015. Now es3 / bugfixs are left - once it's done and https://github.com/swc-project/swc/pull/3801 gets checked in, we can share this as experimental release.

**BREAKING CHANGE:**

**Related issue (if exists):**

### CODE REVIEW

**Comment by kdy1** [comment]
Can you revert the release_max_level_trace?

**Comment by kwonoj** [comment]
@kdy1, sorry, which part exactly need to be reverted? commit doesn't seem to contain `release_max_level` anywhere.

**Comment by kdy1** [comment]
Ah, it was the wrong comment. Sorry.

**Review by kdy1 — APPROVED** [review]
swc-bump:
 - swc_ecma_transforms_compat

**Pull request merged**
