### PR TITLE
fix(es/parser): no error for trailing comma inside `import(...)` with `import_assertions`

### PR DESCRIPTION
**Pull request by sosukesuzuki**
In [Import Assertions Spec](https://tc39.es/proposal-import-assertions/#prod-ImportCall), trailing comma is allowed inside `import(...)`.

### CODE REVIEW

**Review by kdy1 — APPROVED** [review]
LGTM, thanks!

**Review by kdy1 — CHANGES_REQUESTED** [review]
Oh, is it a breaking change of es?
Is wrong to use a trailing comma in dynamic imports starting from es2022?

**Comment by sosukesuzuki** [comment]
Not a breaking change. Import Assertions proposal fixes the specification to allow trailing commas in dynamic imports.(Also, Import Assertions is still in Stage 3, so ES2022 is not relevant.)

Simply, when the Import Assertions specification is implemented, the following code will be valid:

```js
import("foo" , )
```

Previous codes will not be broken.

**Comment by kdy1** [comment]
Ah, thanks! I was confused

**Review by kdy1 — APPROVED** [review]

**Pull request merged**
