### PR TITLE
feat: compress frequency

### PR DESCRIPTION
**Pull request by alexander-akait**
**Description:**

feat compress `<frequency>`

**BREAKING CHANGE:**

No

**Related issue (if exists):**

No

### CODE REVIEW

**Review by kdy1 — DISMISSED** [review]
LGTM. Thank you!
Can you rebase?


---


swc-bump:
 - swc_css_minifier

**Comment by kdy1** [comment]
Can you rebase, please?

**Review by kdy1 — DISMISSED** [review]
Thank you!

---


swc-bump:
 - swc_css_minifier

**Comment by kdy1** [comment]
Can you rebase?

**Comment by alexander-akait** [comment]
@kdy1 I will rebase after https://github.com/swc-project/swc/pull/3663 :+1:

**Comment by alexander-akait** [comment]
@kdy1 Rebased too

**Review by kdy1 — APPROVED** [review]

**Pull request merged**
