### PR TITLE
feat: parse `@property` at-rule

### PR DESCRIPTION
**Pull request by alexander-akait**
**Description:**

Feat - parse `@property` at-rule https://developer.mozilla.org/en-US/docs/Web/CSS/@property

Currently, after https://github.com/swc-project/swc/pull/3469/ and this PR, we will parse almost all at-rules, except only https://developer.mozilla.org/en-US/docs/Web/CSS/@font-feature-values, but I will finish it today/tomorrow

**BREAKING CHANGE:**

yes, new types

**Related issue (if exists):**

No

### CODE REVIEW

**Review by kdy1 — DISMISSED** [review]
LGTM. Thanks!

**Comment by kdy1** [comment]
Can you rebase?

**Comment by alexander-akait** [comment]
Yes, WIP

**Comment by alexander-akait** [comment]
@kdy1 Done :+1:

**Pull request merged**
