### PR TITLE
Use .mjs extension in helper imports

### PR DESCRIPTION
**Pull request by devongovett**
The imports within the helpers themselves must also have extensions for them to work in node. You can test this by running `await import('@swc/helpers/src/index.mjs')` in a node repl.

One problem with the current approach of replacing `@swc/helpers/src/___.mjs` with `@swc/helpers/lib/___.js` in the CommonJS pass is that these relative imports inside the helpers won't be affected. Any idea on that @kdy1?

### CODE REVIEW

**Comment by kdy1** [comment]
Hmm... Relative imports would be fine I guess?
If we load a common js one, it will use `required` for loading deps and esm one will use esm syntax for loading deps. Am I missing something?

**Comment by devongovett** [comment]
Yeah so I guess we need to add something in the script that builds the SWC helpers package itself so the commonjs version doesn't have .mjs in its compiled requires.

**Comment by kdy1** [comment]
Oh I see
Yeah you are right

**Comment by devongovett** [comment]
Ok did it with a simple sed script. Hopefully that works ok.

**Comment by devongovett** [comment]
Might be good to have a simple smoke test for the helpers too, like 

```js
await import('@swc/helpers/src/index.mjs') // can import
require('@swc/helpers/lib/index.js') // can require
```

but not sure where to put it

**Review by kdy1 — DISMISSED** [review]
Thank you!

---

swc-bump:
 - ''

**Comment by kdy1** [comment]
Oh smoke test would be useful.
We had one, but it was removed because we need to update helper package without publishing sometimes.

https://github.com/swc-project/swc/blob/4b340e2c1bfa00f19be5aecceb5c337487030046/crates/swc/tests/exec.rs#L85

This line is the problem, but I think it's better to have external helpers tested

**Comment by kdy1** [comment]
I'll add one tomorrow

**Review by kdy1 — DISMISSED** [review]

**Review by kdy1 — APPROVED** [review]

**Review by kdy1 — DISMISSED** [review]

**Pull request merged**
