### PR TITLE
refactor(html/minifier): Reorganize minification steps

### PR DESCRIPTION
**Pull request by g-plane**
**Description:**

Re-organize minification steps into different modules to increase maintainability.

cc @alexander-akait

### CODE REVIEW

**Review by alexander-akait — COMMENTED** [review]
I did not do this because it is bad for performance and HTML minifier will be small (there are not many things to compress) - less visitors = better perf, but let's ask @kdy1

**Comment by kdy1** [comment]
I qlso prefer less visitor

2022년 4월 26일 (화) 오전 9:32, Alexander Akait ***@***.***>님이 작성:

**Comment by g-plane** [comment]
Ok, but can we split them into different functions while still keeping one visitor?

**Comment by kdy1** [comment]
Yeah, I think it's better for the minfier.
Actually es minifier does same thing

**Comment by alexander-akait** [comment]
Yes, we can, but currenty we have very many functions :smile: Make sense to revisit it late when we implemented collapsing whitespaces/removing optional tags (i.e. we can remove `</p>`/`</html>`/`</body>` because HTML spec allow to not close them)/ and maybe some more. But HTML minifier will not be big because there are not many things to compress, I am thinking we will finish minifier in near future

**Comment by kdy1** [comment]
I think @alexander-akait is right

**Comment by g-plane** [comment]
> currenty we have very many functions

It looks there're four functions, currently, or am I missing anything?

My motivation is to re-organize them as soon as possible, which avoid messing the single `lib.rs` file, and if there're much logic it will be harder to re-organize.

**Comment by alexander-akait** [comment]
@g-plane There is refactor https://github.com/swc-project/swc/pull/4427 to reduce them

**Comment by g-plane** [comment]
Should I wait for that PR or just close this PR?

**Comment by alexander-akait** [comment]
Let's wait, I will implement more compress features and we will revisit it

**Pull request closed without merging**
