### PR TITLE
fix(es/helpers): Workaround a next.js bug from `@swc/helpers`

### PR DESCRIPTION
**Pull request by kdy1**
**Description:**

This is clearly a bug of next.js, but backporting next.js seems extremely hard.

**Related issue (if exists):**

 - https://github.com/vercel/next.js/issues/48593

### CODE REVIEW

**Comment by kdy1** [comment]
Hmm I found that `@swc/helpers/src` already exists...

**Comment by kdy1** [comment]
I requested for a repro 😄

**Comment by kdy1** [comment]
# Investigation:

I need to tell webpack used by `next@12` to handle require in  `@swc/helpers/lib/_class_apply_descriptor_destructure.js` where `@swc/helpers`  has `"type": "module` but also
```json
"./lib/_class_apply_descriptor_destructure.js": {
    "import": "./esm/_class_apply_descriptor_destructure.js",
    "require": "./cjs/_class_apply_descriptor_destructure.cjs"
},
```

I think this is a bug of webpack (because it can know that imported module is cjs, even though it has `"type": "module"`), but not sure if it's possible to fix this for next@12


cc @alexander-akait Thoughts?

**Comment by magic-akari** [comment]
Are you currently working on resolving https://github.com/vercel/next.js/issues/48593#issuecomment-1677834029 ?

```
Module not found: Can't resolve '@swc/helpers/_/_class_private_field_init'

Import trace for requested module:
./node_modules/@react-aria/calendar/dist/import.mjs
./node_modules/react-aria/dist/import.mjs
./pages/index.js
```

It seems to be related to resolveing ESM. I haven't found anything where it requires the `lib` path.

**Comment by kdy1** [comment]
You need 

```json
"resolutions": {
    "next/@swc/helpers": "0.4.32"
  }
```

in `package.json`. If you specify it, you will get 

```
yarn run v1.22.19
$ /Users/kdy1/projects/next-swc-helpers-repro/node_modules/.bin/next build
info  - Linting and checking validity of types
info  - Creating an optimized production build
info  - Compiled successfully
info  - Collecting page data .Error: Cannot find module '<img width="1840" alt="image" src="https://github.com/swc-project/swc/assets/29931815/46482883-c776-4983-b7f9-8b9376719a53">'
Require stack:
- /Users/kdy1/projects/next-swc-helpers-repro/.next/server/pages/_app.js
- /Users/kdy1/projects/next-swc-helpers-repro/node_modules/next/dist/server/require.js
- /Users/kdy1/projects/next-swc-helpers-repro/node_modules/next/dist/server/load-components.js
- /Users/kdy1/projects/next-swc-helpers-repro/node_modules/next/dist/export/worker.js
- /Users/kdy1/projects/next-swc-helpers-repro/node_modules/next/dist/build/worker.js
- /Users/kdy1/projects/next-swc-helpers-repro/node_modules/next/dist/compiled/jest-worker/processChild.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
    at mod._resolveFilename (/Users/kdy1/projects/next-swc-helpers-repro/node_modules/next/dist/build/webpack/require-hook.js:27:32)
    at mod._resolveFilename (/Users/kdy1/projects/next-swc-helpers-repro/node_modules/next/dist/build/webpack/require-hook.js:27:32)
    at Module._load (node:internal/modules/cjs/loader:920:27)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at 653 (/Users/kdy1/projects/next-swc-helpers-repro/.next/server/pages/_app.js:94:27)
    at __webpack_require__ (/Users/kdy1/projects/next-swc-helpers-repro/.next/server/webpack-runtime.js:25:42)
    at 29 (/Users/kdy1/projects/next-swc-helpers-repro/.next/server/pages/_app.js:34:28)
    at __webpack_require__ (/Users/kdy1/projects/next-swc-helpers-repro/.next/server/webpack-runtime.js:25:42) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/kdy1/projects/next-swc-helpers-repro/.next/server/pages/_app.js',
    '/Users/kdy1/projects/next-swc-helpers-repro/node_modules/next/dist/server/require.js',
    '/Users/kdy1/projects/next-swc-helpers-repro/node_modules/next/dist/server/load-components.js',
    '/Users/kdy1/projects/next-swc-helpers-repro/node_modules/next/dist/export/worker.js',
    '/Users/kdy1/projects/next-swc-helpers-repro/node_modules/next/dist/build/worker.js',
    '/Users/kdy1/projects/next-swc-helpers-repro/node_modules/next/dist/compiled/jest-worker/processChild.js'
  ]
}

> Build error occurred
Error: Failed to collect page data for /
    at /Users/kdy1/projects/next-swc-helpers-repro/node_modules/next/dist/build/utils.js:916:15
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  type: 'Error'
}
```

and `require("../esm/_async_to_generator.js")` comes from `next/node_modules/@swc/helpers/lib/_async_to_generator.js`.

image

**Comment by magic-akari** [comment]
@kdy1  I have attempted a solution that may fix it.

https://github.com/magic-akari/swc/tree/fix/lagacy-swc-helpers

**Comment by kdy1** [comment]
Will `npm:@swc/helpers@0.4.14` work? We should publish this fix as `0.4.x`, so I think it may clash.

**Comment by magic-akari** [comment]
Here are some reasons why we must use version `0.4.14` of swc/helpers:

In the older versions, we incorrectly used default imports like this:
```
var _construct = require("swc/helpers/lib/_construct.js").default;
```

This caused the default reference to be cached in the caller, and updates to `exports.default` were no longer had an effect on the caller. 
Therefore, we need to use the older implementation where there are no updates to default. 
Versions 0.4.14 and earlier of swc/helpers meet this requirement.

**Comment by kdy1** [comment]
@magic-akari It worked! Thank you!
image

**Comment by magic-akari** [comment]
Should I create a pull request ?

**Pull request closed without merging**
