### PR TITLE
feat(es/ast): Support import attributes proposal

### LINKED ISSUE #7179: `import '...' with {...}`
### Describe the feature

The `import '...' assert {...}` syntax got changed into `import '...' with {...}` at the [last tc39 meeting](https://dev.to/hemanth/updates-from-the-95th-tc39-meeting-ne5).

### Babel plugin or link to the feature description

https://github.com/tc39/proposal-import-attributes

### Additional context

The purpose of this change was only to explicitly allow runtimes to include the attributes in the module cache key (instead of just validating that the target module was matching the constraint), so it shouldn't need other changes in SWC other than adding support for the new syntax.

### PR DESCRIPTION
**Pull request by kdy1**
**Description:**

**Related issue:**

 - Closes #7179

### CODE REVIEW

**Comment by chentsulin** [comment]
Hi @kdy1, I use `@swc/core` 1.3.82 with `ts-node` and have some problems due to this feature.

This feature transform the `assert` keyword to the `with` keyword, like below:

```js
import data from "./data.json" assert { type: "json" };
```

https://github.com/kdy1/swc/blob/c6a477d528a5e844680f85606a2f146d9a41f8d0/crates/swc_ecma_codegen/tests/fixture/issues/3110/input.js

```js
import data from "./data.json" with {
    type: "json"
};
```

https://github.com/kdy1/swc/blob/c6a477d528a5e844680f85606a2f146d9a41f8d0/crates/swc_ecma_codegen/tests/fixture/issues/3110/output.js 

However, there are a lot of environments (including our node 18/20) only support import assertions and not import attributes. So  it causes a SyntaxError:

```sh
SyntaxError: Unexpected token 'with'
           at CustomizedModuleLoader.moduleStrategy (node:internal/modules/esm/translators:116:18)
           at CustomizedModuleLoader.moduleProvider (node:internal/modules/esm/loader:190:14)
           at async link (node:internal/modules/esm/module_job:67:21)
```

Is it as expected?

**Comment by kdy1** [comment]
I didn't expect it

**Comment by chentsulin** [comment]
There is a babel plugin supporting transform from `with` to `assert`: https://babeljs.io/docs/babel-plugin-proposal-import-attributes-to-assertions

In my case, avoiding transforming from `assert` to `with` is enough.

**Comment by nicolo-ribaudo** [comment]
The status currently is that:
- V8 supports `with` behind a flag (so does Chrome dev, Deno when it will upgrade swc, and Node.js when it will upgrade V8), and it supports `assert`
- JSC only supports `with`, but I do not think it's in safari TP yet
- SpiderMonkey is implementing `with`

**Pull request merged**
