### PR TITLE
fix(transform): calculate class member fn args identifier collision

### LINKED ISSUE #1948: Multiple argument destructuring on a method definition inside object initializer causes clashed argument names
**Describe the bug**

Multiple argument destructuring on a method definition inside object initializer causes clashed argument names.

**Input code**

```js
function fn1(arg1, {opt1, opt2}, ...arg2) {
    console.log(arg1, opt1, opt2, arg2);
}

function fn2(arg1, {opt1, opt2}, arg2, {opt3, opt4}, ...arg3) {
    console.log(arg1, opt1, opt2, arg2, opt3, opt4, arg3);
}

const fn3 = (arg1, {opt1, opt2}, arg2, {opt3, opt4}, ...arg3) => {
    console.log(arg1, opt1, opt2, arg2, opt3, opt4, arg3);
};

class cls {
    constructor(arg1, {opt1, opt2}, arg2, {opt3, opt4}, ...arg3) {
        console.log(arg1, opt1, opt2, arg2, opt3, opt4, arg3);
    }

    fn4(arg1, {opt1, opt2}, arg2, {opt3, opt4}, ...arg3) {
        console.log(arg1, opt1, opt2, arg2, opt3, opt4, arg3);
    }
}

export default {
    fn5(arg1, {opt1, opt2}, arg2, {opt3, opt4}, ...arg3) {
        console.log(arg1, opt1, opt2, arg2, opt3, opt4, arg3);
    },
    fn7: function*(arg1, {opt1, opt2}, arg2, {opt3, opt4}, ...arg3) {
        console.log(arg1, opt1, opt2, arg2, opt3, opt4, arg3);
        yield null;
    },
    *fn6(arg1, {opt1, opt2}, arg2, {opt3, opt4}, ...arg3) {
        console.log(arg1, opt1, opt2, arg2, opt3, opt4, arg3);
        yield null;
    },
};
```

**Config**

```json
{
  "env": {
    "targets": {
      "chrome": "49",
      "firefox": "45",
      "safari": "10",
      "edge": "13"
    },
    "mode": "entry",
    "coreJs": 2
  },
  "jsc": {
    "parser": {
      "syntax": "ecmascript",
      "jsx": true,
      "dynamicImport": true,
      "privateMethod": true,
      "functionBind": true,
      "classPrivateProperty": true,
      "exportDefaultFrom": true,
      "exportNamespaceFrom": true,
      "decorators": true,
      "decoratorsBeforeExport": true,
      "importMeta": true
    }
  },
  "minify": false,
  "sourceMaps": false
}
```

**Result**

```js
import   "core-js/modules/web.timers";
import   "core-js/modules/web.immediate";
import   "core-js/modules/web.dom.iterable";
import   "regenerator-runtime/runtime";
import regeneratorRuntime from "regenerator-runtime";
function fn1(arg1, param) {
    var opt1 = param.opt1, opt2 = param.opt2;
    for(var _len = arguments.length, arg2 = new Array(_len > 2 ? _len - 2 : 0), _key = 2; _key < _len; _key++){
        arg2[_key - 2] = arguments[_key];
    }
    console.log(arg1, opt1, opt2, arg2);
}
function fn2(arg1, param, arg2, param1) {
    var opt1 = param.opt1, opt2 = param.opt2, opt3 = param1.opt3, opt4 = param1.opt4;
    for(var _len = arguments.length, arg3 = new Array(_len > 4 ? _len - 4 : 0), _key = 4; _key < _len; _key++){
        arg3[_key - 4] = arguments[_key];
    }
    console.log(arg1, opt1, opt2, arg2, opt3, opt4, arg3);
}
var fn3 = function(arg1, param, arg2, param1) {
    var opt1 = param.opt1, opt2 = param.opt2, opt3 = param1.opt3, opt4 = param1.opt4;
    for(var _len = arguments.length, arg3 = new Array(_len > 4 ? _len - 4 : 0), _key = 4; _key < _len; _key++){
        arg3[_key - 4] = arguments[_key];
    }
    console.log(arg1, opt1, opt2, arg2, opt3, opt4, arg3);
};
class cls {
    fn4(arg1, param, arg2, param) {
        var opt1 = param.opt1, opt2 = param.opt2, opt3 = param.opt3, opt4 = param.opt4;
        for(var _len = arguments.length, arg3 = new Array(_len > 4 ? _len - 4 : 0), _key = 4; _key < _len; _key++){
            arg3[_key - 4] = arguments[_key];
        }
        console.log(arg1, opt1, opt2, arg2, opt3, opt4, arg3);
    }
    constructor(arg11, param2, arg21, param1){
        var opt1 = param2.opt1, opt2 = param2.opt2, opt3 = param1.opt3, opt4 = param1.opt4;
        for(var _len = arguments.length, arg3 = new Array(_len > 4 ? _len - 4 : 0), _key = 4; _key < _len; _key++){
            arg3[_key - 4] = arguments[_key];
        }
        console.log(arg11, opt1, opt2, arg21, opt3, opt4, arg3);
    }
}
export default {
    fn5 (arg1, param, arg2, param) {
        var opt11 = param.opt1, opt21 = param.opt2, opt31 = param.opt3, opt41 = param.opt4;
        for(var _len1 = arguments.length, arg31 = new Array(_len1 > 4 ? _len1 - 4 : 0), _key1 = 4; _key1 < _len1; _key1++){
            arg31[_key1 - 4] = arguments[_key1];
        }
        console.log(arg1, opt11, opt21, arg2, opt31, opt41, arg31);
    },
    fn7: regeneratorRuntime.mark(function fn7(arg12, param3, arg22, param4) {
        var opt12, opt22, opt32, opt42, _len2, arg32, _key2, _args = arguments;
        return regeneratorRuntime.wrap(function fn7$(_ctx) {
            while(1)switch(_ctx.prev = _ctx.next){
                case 0:
                    opt12 = param3.opt1, opt22 = param3.opt2, opt32 = param4.opt3, opt42 = param4.opt4;
                    for(_len2 = _args.length, arg32 = new Array(_len2 > 4 ? _len2 - 4 : 0), _key2 = 4; _key2 < _len2; _key2++){
                        arg32[_key2 - 4] = _args[_key2];
                    }
                    console.log(arg12, opt12, opt22, arg22, opt32, opt42, arg32);
                    _ctx.next = 5;
                    return null;
                case 5:
                case "end":
                    return _ctx.stop();
            }
        }, fn7);
    }),
    fn6 () {
        return regeneratorRuntime.mark(function _callee(arg12, param3, arg22, param4) {
            var opt12, opt22, opt32, opt42, _len2, arg32, _key2, _args = arguments;
            return regeneratorRuntime.wrap(function _callee$(_ctx) {
                while(1)switch(_ctx.prev = _ctx.next){
                    case 0:
                        opt12 = param3.opt1, opt22 = param3.opt2, opt32 = param4.opt3, opt42 = param4.opt4;
                        for(_len2 = _args.length, arg32 = new Array(_len2 > 4 ? _len2 - 4 : 0), _key2 = 4; _key2 < _len2; _key2++){
                            arg32[_key2 - 4] = _args[_key2];
                        }
                        console.log(arg12, opt12, opt22, arg22, opt32, opt42, arg32);
                        _ctx.next = 5;
                        return null;
                    case 5:
                    case "end":
                        return _ctx.stop();
                }
            }, _callee);
        })();
    }
};


//#sourceMappingURL=data:application/json;charset=utf-8;base64,IntcInZlcnNpb25cIjozLFwic291cmNlc1wiOltdLFwibmFtZXNcIjpbXSxcIm1hcHBpbmdzXCI6XCJcIixcImZpbGVcIjpcInN0ZG91dFwifSI=
```

**Expected behavior**

The transpile results of `fn4` and `fn5` is wrong, duplicated placeholder argument `param` is generated.

Interestingly, only method definitions in object initializer or class body could reproduce the problem.

**Version**
```
    "@swc/cli": "^0.1.46",
    "@swc/core": "^1.2.66",
```

**Additional context**

`@swc/cli` is utilized to inspect the transpile result of my sample input.

### PR DESCRIPTION
**Pull request by kwonoj**
- closes #1948

This PR is an attempt to close #1948 - class identifier is considered as ref which skips collision / conflict calculation for the renaming. PR changes behavior to declare identifiers then calculate collisions.

In result, this requires to change existing test fixtures having classes inside of it to amend generated member fn param names. I've peeked manually and for me it looks ok, but this change may not be desired still - would like to update PR if that's the case.

### CODE REVIEW

**Review by kdy1 — CHANGES_REQUESTED** [review]
I think it should control ident type in mehods like `visit_mut_class_method` instead of changing all for them of class members.
I'm saying this because diff seems like a regression.

**Comment by kwonoj** [comment]
I'll try to peek more. Mind if I ask some starting place I should look into?

**Comment by kdy1** [comment]
I think [`visit_mut_class_method`](https://rustdoc.swc.rs/swc_ecma_visit/trait.VisitMut.html#method.visit_mut_class_method) and [`visit_mut_class_prop`](https://rustdoc.swc.rs/swc_ecma_visit/trait.VisitMut.html#method.visit_mut_class_prop) should be overrided, and identifiers should be visited with correct `IdentType`.

Idea would be very similar to this PR. But I want to make it more explicit to prevent unrelated changes, e.g. changing IdentType from class member handler, from breaking lots of things.

**Comment by kwonoj** [comment]
Thanks for the pointers, I'll try to peek those. Closing PR for now to avoid branch update keep triggers upstream CI, also it's possible I may not resolve this in time before someone else takes a look.

**Comment by kwonoj** [comment]
I'll create new one if I think I have feasible changes.

**Pull request closed without merging**
